import { TopicPack } from '../topic-pack.types';

export const apisPack: TopicPack = {
  topicId: 'apis',
  label: 'APIs',
  description: 'Designing resilient, evolvable APIs and gateways.',
  archetypes: ['architecture', 'integration', 'reliability', 'performance'],
  concepts: [
    { id: 'api-contracts', topicId: 'apis', title: 'Contracts & Schemas', summary: 'Versioning, breaking changes, and backward compatibility.', stage: 'foundation' },
    { id: 'api-authz', topicId: 'apis', title: 'AuthN/AuthZ', summary: 'Token choices, scopes, and delegation (OAuth2, JWT, mTLS).', stage: 'foundation' },
    { id: 'api-rate-limit', topicId: 'apis', title: 'Rate Limiting', summary: 'Token bucket vs leaky bucket, per-tenant quotas, and abuse signals.', stage: 'foundation' },
    { id: 'api-pagination', topicId: 'apis', title: 'Pagination & Filtering', summary: 'Cursor vs offset, determinism, and cost controls.', stage: 'foundation' },
    { id: 'api-idempotency', topicId: 'apis', title: 'Idempotency', summary: 'Idempotency keys, safe retries, and dedupe storage.', stage: 'intermediate' },
    { id: 'api-error-model', topicId: 'apis', title: 'Error Model', summary: 'Consistent status codes, retryable vs fatal classes, and tracing IDs.', stage: 'foundation' },
    { id: 'api-n-plus-one', topicId: 'apis', title: 'N+1 & Data Loader Patterns', summary: 'Batching, joins, and cache hints to reduce chatter.', stage: 'intermediate' },
    { id: 'api-gateway-patterns', topicId: 'apis', title: 'Gateway Patterns', summary: 'Routing, auth offload, caching, canarying, and circuit breakers.', stage: 'intermediate' },
    { id: 'api-observability', topicId: 'apis', title: 'Observability', summary: 'Structured logs, trace propagation, and per-route metrics.', stage: 'foundation' },
    { id: 'api-slo', topicId: 'apis', title: 'SLOs & Error Budgets', summary: 'Per-endpoint SLOs, burn alerts, and traffic shedding.', stage: 'advanced' },
    { id: 'api-docs', topicId: 'apis', title: 'Documentation & SDKs', summary: 'OpenAPI/GraphQL SDL, examples, and contract tests.', stage: 'intermediate' },
    { id: 'api-versioning', topicId: 'apis', title: 'Versioning Strategy', summary: 'URI vs header, backward compatibility windows, and deprecation.', stage: 'advanced' },
  ],
  scenarioHooks: [
    {
      id: 'api-breaking-change',
      topicId: 'apis',
      title: 'Breaking change pressure',
      backdrop: 'New field required for fraud checks.',
      trigger: 'Mobile clients will take 3 months to update.',
      relatedConcepts: ['api-versioning', 'api-contracts'],
    },
    {
      id: 'api-abuse',
      topicId: 'apis',
      title: 'Abuse spike',
      backdrop: 'Public API attacked by scrapers.',
      trigger: 'P99 latency and error rates rise.',
      relatedConcepts: ['api-rate-limit', 'api-gateway-patterns'],
    },
    {
      id: 'api-nplusone',
      topicId: 'apis',
      title: 'N+1 in aggregate endpoint',
      backdrop: 'Dashboard endpoint issues dozens of downstream calls.',
      trigger: 'Latency blows past SLOs.',
      relatedConcepts: ['api-n-plus-one', 'api-pagination'],
    },
    {
      id: 'api-idempotency-failure',
      topicId: 'apis',
      title: 'Duplicate payments',
      backdrop: 'Retries during outages double-charge customers.',
      trigger: 'Idempotency strategy missing.',
      relatedConcepts: ['api-idempotency', 'api-error-model'],
    },
    {
      id: 'api-incomplete-logs',
      topicId: 'apis',
      title: 'Missing traces',
      backdrop: 'Incident review finds gaps in request correlation.',
      trigger: 'Hard to root-cause errors.',
      relatedConcepts: ['api-observability', 'api-error-model'],
    },
  ],
  constraintTemplates: [
    { id: 'api-latency', topicId: 'apis', label: 'Latency', text: 'p99 under 150ms for GETs', tags: ['latency'] },
    { id: 'api-compat', topicId: 'apis', label: 'Compatibility', text: 'No breaking changes for at least 6 months', tags: ['versioning'] },
    { id: 'api-security', topicId: 'apis', label: 'Security', text: 'All endpoints require auth + audit trail', tags: ['security'] },
    { id: 'api-cost', topicId: 'apis', label: 'Cost', text: 'Reduce downstream calls by 30%', tags: ['performance'] },
  ],
  rubricTemplates: [
    {
      id: 'api-architecture-rubric',
      topicId: 'apis',
      archetype: 'architecture',
      mustHave: ['Clear contracts', 'Versioning and deprecation', 'Auth & rate limiting'],
      niceToHave: ['SDK/doc updates'],
      redFlags: ['Breaking changes with no plan', 'No pagination strategy'],
      scoringWeights: { clarity: 0.2, correctness: 0.25, depth: 0.2, pragmatism: 0.2, safety: 0.15 },
    },
    {
      id: 'api-reliability-rubric',
      topicId: 'apis',
      archetype: 'reliability',
      mustHave: ['Idempotency for unsafe verbs', 'Error model with retries', 'Observability'],
      niceToHave: ['Circuit breakers at edge'],
      redFlags: ['200 for errors', 'No correlation IDs'],
      scoringWeights: { clarity: 0.2, correctness: 0.22, depth: 0.2, pragmatism: 0.2, safety: 0.18 },
    },
  ],
  questionFamilies: [
    {
      key: 'api-gateway-design',
      topicId: 'apis',
      archetype: 'architecture',
      stem: 'Design an API gateway strategy.',
      framing: 'Routing, auth offload, caching, and traffic controls.',
      primaryConcepts: ['api-gateway-patterns', 'api-rate-limit'],
      supportingConcepts: ['api-error-model'],
      defaultConstraints: ['api-security', 'api-latency'],
      defaultRubricId: 'api-architecture-rubric',
      phrasingSkeleton: 'Outline an API gateway/edge design with safeguards.',
    },
    {
      key: 'api-versioning-plan',
      topicId: 'apis',
      archetype: 'integration',
      stem: 'Ship a breaking change safely.',
      framing: 'Compatibility period, headers vs URI, and client rollout.',
      primaryConcepts: ['api-versioning', 'api-contracts'],
      supportingConcepts: ['api-docs'],
      defaultConstraints: ['api-compat'],
      defaultRubricId: 'api-architecture-rubric',
      phrasingSkeleton: 'Plan an API change without breaking existing clients.',
    },
    {
      key: 'api-idempotency-family',
      topicId: 'apis',
      archetype: 'reliability',
      stem: 'Prevent duplicate side effects.',
      framing: 'Idempotency keys, retry policy, and storage needs.',
      primaryConcepts: ['api-idempotency', 'api-error-model'],
      defaultConstraints: ['api-security'],
      defaultRubricId: 'api-reliability-rubric',
      phrasingSkeleton: 'Explain idempotent API design under retries.',
    },
    {
      key: 'api-query-efficiency',
      topicId: 'apis',
      archetype: 'performance',
      stem: 'Reduce chattiness and N+1 issues.',
      framing: 'Batching, pagination, and data loader strategies.',
      primaryConcepts: ['api-n-plus-one', 'api-pagination'],
      defaultConstraints: ['api-cost'],
      defaultRubricId: 'api-architecture-rubric',
      phrasingSkeleton: 'Improve an API endpoint suffering from N+1 calls.',
    },
    {
      key: 'api-observability-family',
      topicId: 'apis',
      archetype: 'reliability',
      stem: 'Add observability for incident response.',
      framing: 'Traces, metrics per route, and error taxonomy.',
      primaryConcepts: ['api-observability', 'api-error-model'],
      defaultConstraints: ['api-security'],
      defaultRubricId: 'api-reliability-rubric',
      phrasingSkeleton: 'Instrument APIs with traces and consistent errors.',
    },
  ],
  learningResources: [
    { title: 'API Design Guide', note: 'Internal checklist placeholder' },
    { title: 'OWASP API Security Top 10', url: 'https://owasp.org/www-project-api-security/' },
    { title: 'Stripe API Changelog', url: 'https://stripe.com/docs/upgrades' },
  ],
};

export default apisPack;
