import { TopicPack } from '../topic-pack.types';

export const apisPack: TopicPack = {
  topicId: 'apis',
  label: 'APIs',
  description: 'Designing resilient, evolvable APIs and gateways.',
  archetypes: ['architecture', 'integration', 'reliability', 'performance'],
  concepts: [
    { id: 'api-contracts', topicId: 'apis', title: 'Contracts & Schemas', summary: 'Versioning, breaking changes, and backward compatibility.', stage: 'foundation' },
    { id: 'api-authz', topicId: 'apis', title: 'AuthN/AuthZ', summary: 'Token choices, scopes, and delegation (OAuth2, JWT, mTLS).', stage: 'foundation' },
    { id: 'api-rate-limit', topicId: 'apis', title: 'Rate Limiting', summary: 'Token bucket vs leaky bucket, per-tenant quotas, and abuse signals.', stage: 'foundation' },
    { id: 'api-pagination', topicId: 'apis', title: 'Pagination & Filtering', summary: 'Cursor vs offset, determinism, and cost controls.', stage: 'foundation' },
    { id: 'api-idempotency', topicId: 'apis', title: 'Idempotency', summary: 'Idempotency keys, safe retries, and dedupe storage.', stage: 'intermediate' },
    { id: 'api-error-model', topicId: 'apis', title: 'Error Model', summary: 'Consistent status codes, retryable vs fatal classes, and tracing IDs.', stage: 'foundation' },
    { id: 'api-n-plus-one', topicId: 'apis', title: 'N+1 & Data Loader Patterns', summary: 'Batching, joins, and cache hints to reduce chatter.', stage: 'intermediate' },
    { id: 'api-gateway-patterns', topicId: 'apis', title: 'Gateway Patterns', summary: 'Routing, auth offload, caching, canarying, and circuit breakers.', stage: 'intermediate' },
    { id: 'api-observability', topicId: 'apis', title: 'Observability', summary: 'Structured logs, trace propagation, and per-route metrics.', stage: 'foundation' },
    { id: 'api-slo', topicId: 'apis', title: 'SLOs & Error Budgets', summary: 'Per-endpoint SLOs, burn alerts, and traffic shedding.', stage: 'advanced' },
    { id: 'api-docs', topicId: 'apis', title: 'Documentation & SDKs', summary: 'OpenAPI/GraphQL SDL, examples, and contract tests.', stage: 'intermediate' },
    { id: 'api-versioning', topicId: 'apis', title: 'Versioning Strategy', summary: 'URI vs header, backward compatibility windows, and deprecation.', stage: 'advanced' },
  ],
  scenarioHooks: [
    {
      id: 'api-breaking-change',
      topicId: 'apis',
      title: 'Breaking change pressure',
      backdrop: 'New field required for fraud checks.',
      trigger: 'Mobile clients will take 3 months to update.',
      compatibleFamilies: ['api-versioning-plan'],
      relatedConcepts: ['api-versioning', 'api-contracts'],
    },
    {
      id: 'api-abuse',
      topicId: 'apis',
      title: 'Abuse spike',
      backdrop: 'Public API attacked by scrapers.',
      trigger: 'P99 latency and error rates rise.',
      compatibleFamilies: ['api-gateway-design', 'api-observability-family'],
      relatedConcepts: ['api-rate-limit', 'api-gateway-patterns'],
    },
    {
      id: 'api-nplusone',
      topicId: 'apis',
      title: 'N+1 in aggregate endpoint',
      backdrop: 'Dashboard endpoint issues dozens of downstream calls.',
      trigger: 'Latency blows past SLOs.',
      compatibleFamilies: ['api-query-efficiency'],
      relatedConcepts: ['api-n-plus-one', 'api-pagination'],
    },
    {
      id: 'api-idempotency-failure',
      topicId: 'apis',
      title: 'Duplicate payments',
      backdrop: 'Retries during outages double-charge customers.',
      trigger: 'Idempotency strategy missing.',
      compatibleFamilies: ['api-idempotency-family'],
      relatedConcepts: ['api-idempotency', 'api-error-model'],
    },
    {
      id: 'api-incomplete-logs',
      topicId: 'apis',
      title: 'Missing traces',
      backdrop: 'Incident review finds gaps in request correlation.',
      trigger: 'Hard to root-cause errors.',
      compatibleFamilies: ['api-observability-family'],
      relatedConcepts: ['api-observability', 'api-error-model'],
    },
    {
      id: 'api-token-scope-breach',
      topicId: 'apis',
      title: 'Over-scoped partner token',
      backdrop: 'A partner integration leaks an access token that can call more endpoints than intended.',
      trigger: 'Security review finds broad scopes and no tenant boundary checks at the gateway.',
      compatibleFamilies: ['api-auth-boundaries', 'api-gateway-design'],
      relatedConcepts: ['api-authz', 'api-gateway-patterns'],
    },
    {
      id: 'api-webhook-retries',
      topicId: 'apis',
      title: 'Webhook retry storm',
      backdrop: 'Customers receive duplicate webhook notifications after intermittent 5xx responses from their receivers.',
      trigger: 'Retry behavior is inconsistent and signature validation is missing on some consumers.',
      compatibleFamilies: ['api-webhook-signature-family', 'api-idempotency-family', 'api-error-contract-family'],
      relatedConcepts: ['api-idempotency', 'api-error-model'],
    },
    {
      id: 'api-deprecation-deadline',
      topicId: 'apis',
      title: 'Deprecation deadline pressure',
      backdrop: 'A legacy field must be removed to unblock a new platform model, but several clients still depend on it.',
      trigger: 'Product sets a hard sunset date before consumer migration is complete.',
      compatibleFamilies: ['api-deprecation-governance', 'api-versioning-plan'],
      relatedConcepts: ['api-versioning', 'api-docs'],
    },
  ],
  constraintTemplates: [
    { id: 'api-latency', topicId: 'apis', label: 'Latency', text: 'p99 under 150ms for GETs', tags: ['latency'] },
    { id: 'api-compat', topicId: 'apis', label: 'Compatibility', text: 'No breaking changes for at least 6 months', tags: ['versioning'] },
    { id: 'api-security', topicId: 'apis', label: 'Security', text: 'All endpoints require auth + audit trail', tags: ['security'] },
    { id: 'api-cost', topicId: 'apis', label: 'Cost', text: 'Reduce downstream calls by 30%', tags: ['performance'] },
  ],
  rubricTemplates: [
    {
      id: 'api-architecture-rubric',
      topicId: 'apis',
      archetype: 'architecture',
      mustHave: ['Clear contracts', 'Versioning and deprecation', 'Auth & rate limiting'],
      niceToHave: ['SDK/doc updates'],
      redFlags: ['Breaking changes with no plan', 'No pagination strategy'],
      scoringWeights: { clarity: 0.2, correctness: 0.25, depth: 0.2, pragmatism: 0.2, safety: 0.15 },
    },
    {
      id: 'api-reliability-rubric',
      topicId: 'apis',
      archetype: 'reliability',
      mustHave: ['Idempotency for unsafe verbs', 'Error model with retries', 'Observability'],
      niceToHave: ['Circuit breakers at edge'],
      redFlags: ['200 for errors', 'No correlation IDs'],
      scoringWeights: { clarity: 0.2, correctness: 0.22, depth: 0.2, pragmatism: 0.2, safety: 0.18 },
    },
    {
      id: 'api-auth-boundaries-rubric',
      topicId: 'apis',
      archetype: 'architecture',
      mustHave: [
        'Separates authentication from authorization and tenant boundary enforcement',
        'Chooses token scope, claim, or mTLS strategy that maps cleanly to the caller permissions model',
        'Explains where authorization is enforced at the gateway versus the service to avoid confused deputy problems',
      ],
      niceToHave: ['Mentions short-lived tokens or token introspection for revocation-sensitive flows'],
      redFlags: ['Treats a valid JWT as sufficient authorization for every endpoint'],
      scoringWeights: { clarity: 0.2, correctness: 0.25, depth: 0.21, pragmatism: 0.18, safety: 0.16 },
    },
    {
      id: 'api-rate-limit-strategy-rubric',
      topicId: 'apis',
      archetype: 'performance',
      mustHave: [
        'Chooses a rate-limiting algorithm such as token bucket or leaky bucket based on burst behavior',
        'Defines the partition key for limits such as tenant, user, IP, or method',
        'Explains how clients learn limit state through headers, retries, or backoff guidance',
      ],
      niceToHave: ['Mentions separate abuse controls for writes versus reads'],
      redFlags: ['Uses one global limit that lets one noisy tenant starve everyone else'],
      scoringWeights: { clarity: 0.2, correctness: 0.24, depth: 0.2, pragmatism: 0.2, safety: 0.16 },
    },
    {
      id: 'api-error-contract-family-rubric',
      topicId: 'apis',
      archetype: 'integration',
      mustHave: [
        'Defines stable error codes or types in addition to HTTP status codes',
        'Distinguishes retryable failures from validation or authorization failures explicitly',
        'Includes trace or request identifiers so clients and operators can correlate incidents',
      ],
      niceToHave: ['Mentions machine-readable field-level validation details'],
      redFlags: ['Returns inconsistent shapes or ambiguous 500 errors for user mistakes'],
      scoringWeights: { clarity: 0.2, correctness: 0.24, depth: 0.19, pragmatism: 0.2, safety: 0.17 },
    },
    {
      id: 'api-webhook-signature-family-rubric',
      topicId: 'apis',
      archetype: 'reliability',
      mustHave: [
        'Signs webhook payloads with a shared secret or asymmetric key and verifies the signature before processing',
        'Uses idempotency or delivery identifiers so receivers can deduplicate retries safely',
        'Explains timestamp tolerance or replay protection for captured webhook requests',
      ],
      niceToHave: ['Mentions secret rotation strategy without dropping deliveries'],
      redFlags: ['Trusts source IP alone instead of verifying webhook authenticity'],
      scoringWeights: { clarity: 0.2, correctness: 0.25, depth: 0.2, pragmatism: 0.19, safety: 0.16 },
    },
    {
      id: 'api-deprecation-governance-rubric',
      topicId: 'apis',
      archetype: 'architecture',
      mustHave: [
        'Defines a deprecation timeline with communication, observability, and enforcement milestones',
        'Measures client usage of the deprecated field or endpoint before removal',
        'Provides a migration path such as replacement fields, versioned routes, or SDK updates',
      ],
      niceToHave: ['Mentions automated contract tests or changelog gating for deprecated behavior'],
      redFlags: ['Removes behavior on a calendar date with no client-usage evidence or fallback plan'],
      scoringWeights: { clarity: 0.2, correctness: 0.24, depth: 0.21, pragmatism: 0.19, safety: 0.16 },
    },
  ],
  questionFamilies: [
    {
      key: 'api-gateway-design',
      topicId: 'apis',
      archetype: 'architecture',
      difficulty: 'hard',
      stem: 'Design an API gateway strategy.',
      framing: 'Routing, auth offload, caching, and traffic controls.',
      primaryConcepts: ['api-gateway-patterns', 'api-rate-limit'],
      supportingConcepts: ['api-error-model'],
      defaultConstraints: ['api-security', 'api-latency'],
      defaultRubricId: 'api-gateway-design-rubric',
      phrasingSkeleton: 'Outline an API gateway/edge design with safeguards.',
    },
    {
      key: 'api-versioning-plan',
      topicId: 'apis',
      archetype: 'integration',
      difficulty: 'medium',
      stem: 'Ship a breaking change safely.',
      framing: 'Compatibility period, headers vs URI, and client rollout.',
      primaryConcepts: ['api-versioning', 'api-contracts'],
      supportingConcepts: ['api-docs'],
      defaultConstraints: ['api-compat'],
      defaultRubricId: 'api-versioning-plan-rubric',
      phrasingSkeleton: 'Plan an API change without breaking existing clients.',
    },
    {
      key: 'api-idempotency-family',
      topicId: 'apis',
      archetype: 'reliability',
      difficulty: 'medium',
      stem: 'Prevent duplicate side effects.',
      framing: 'Idempotency keys, retry policy, and storage needs.',
      primaryConcepts: ['api-idempotency', 'api-error-model'],
      defaultConstraints: ['api-security'],
      defaultRubricId: 'api-idempotency-family-rubric',
      phrasingSkeleton: 'Explain idempotent API design under retries.',
    },
    {
      key: 'api-query-efficiency',
      topicId: 'apis',
      archetype: 'performance',
      difficulty: 'medium',
      stem: 'Reduce chattiness and N+1 issues.',
      framing: 'Batching, pagination, and data loader strategies.',
      primaryConcepts: ['api-n-plus-one', 'api-pagination'],
      defaultConstraints: ['api-cost'],
      defaultRubricId: 'api-query-efficiency-rubric',
      phrasingSkeleton: 'Improve an API endpoint suffering from N+1 calls.',
    },
    {
      key: 'api-observability-family',
      topicId: 'apis',
      archetype: 'reliability',
      difficulty: 'medium',
      stem: 'Add observability for incident response.',
      framing: 'Traces, metrics per route, and error taxonomy.',
      primaryConcepts: ['api-observability', 'api-error-model'],
      defaultConstraints: ['api-security'],
      defaultRubricId: 'api-observability-family-rubric',
      phrasingSkeleton: 'Instrument APIs with traces and consistent errors.',
    },
    {
      key: 'api-auth-boundaries',
      topicId: 'apis',
      archetype: 'architecture',
      difficulty: 'hard',
      stem: 'Design authorization boundaries that match API trust zones.',
      framing: 'Scopes, claims, tenant isolation, and gateway-versus-service enforcement points.',
      primaryConcepts: ['api-authz', 'api-gateway-patterns'],
      supportingConcepts: ['api-observability'],
      defaultConstraints: ['api-security'],
      defaultRubricId: 'api-auth-boundaries-rubric',
      phrasingSkeleton: 'A partner token should access only one tenant and a narrow set of endpoints; how would you design the auth and enforcement model so leaked credentials have limited blast radius?',
    },
    {
      key: 'api-rate-limit-strategy',
      topicId: 'apis',
      archetype: 'performance',
      difficulty: 'medium',
      stem: 'Rate-limit APIs without punishing healthy clients.',
      framing: 'Burst control, tenant fairness, and actionable client feedback.',
      primaryConcepts: ['api-rate-limit', 'api-slo'],
      supportingConcepts: ['api-gateway-patterns'],
      defaultConstraints: ['api-latency'],
      defaultRubricId: 'api-rate-limit-strategy-rubric',
      phrasingSkeleton: 'How would you rate-limit a public API during abuse spikes while still preserving good traffic for well-behaved tenants?',
    },
    {
      key: 'api-error-contract-family',
      topicId: 'apis',
      archetype: 'integration',
      difficulty: 'medium',
      stem: 'Make API errors predictable for clients and operators.',
      framing: 'Stable error shapes, retry guidance, and correlation identifiers.',
      primaryConcepts: ['api-error-model', 'api-contracts'],
      supportingConcepts: ['api-observability'],
      defaultConstraints: ['api-security'],
      defaultRubricId: 'api-error-contract-family-rubric',
      phrasingSkeleton: 'What should a robust API error contract include so clients know whether to retry and support teams can trace the request quickly?',
    },
    {
      key: 'api-webhook-signature-family',
      topicId: 'apis',
      archetype: 'reliability',
      difficulty: 'medium',
      stem: 'Deliver webhooks safely to third parties.',
      framing: 'Signing, replay protection, retries, and receiver-side deduplication.',
      primaryConcepts: ['api-idempotency', 'api-authz'],
      supportingConcepts: ['api-error-model'],
      defaultConstraints: ['api-security'],
      defaultRubricId: 'api-webhook-signature-family-rubric',
      phrasingSkeleton: 'How would you design a webhook system so receivers can verify authenticity, reject replays, and survive duplicate deliveries?',
    },
    {
      key: 'api-deprecation-governance',
      topicId: 'apis',
      archetype: 'architecture',
      difficulty: 'hard',
      stem: 'Retire deprecated API behavior without guesswork.',
      framing: 'Usage measurement, migration tooling, and enforcement milestones.',
      primaryConcepts: ['api-versioning', 'api-docs'],
      supportingConcepts: ['api-contracts'],
      defaultConstraints: ['api-compat'],
      defaultRubricId: 'api-deprecation-governance-rubric',
      phrasingSkeleton: 'A deprecated API field must be removed this quarter; how would you decide when it is safe to enforce the removal and how would you drive consumer migration?',
    },
  ],
  learningResources: [
    { title: 'API Design Guide', note: 'Internal checklist placeholder' },
    { title: 'OWASP API Security Top 10', url: 'https://owasp.org/www-project-api-security/' },
    { title: 'Stripe API Changelog', url: 'https://stripe.com/docs/upgrades' },
  ],
};

export default apisPack;
