import { TopicPack } from '../topic-pack.types';

export const cachingPack: TopicPack = {
  topicId: 'caching',
  label: 'Caching',
  description: 'Design and operate caches that balance freshness, cost, and reliability.',
  archetypes: ['performance', 'reliability', 'architecture', 'integration'],
  concepts: [
    {
      id: 'cache-layering',
      topicId: 'caching',
      title: 'Cache Layering',
      summary: 'Client, CDN, edge, and service-level caches with coherent policies.',
      stage: 'foundation',
    },
    {
      id: 'cache-invalidation',
      topicId: 'caching',
      title: 'Invalidation & TTLs',
      summary: 'Time-based expiry, write-through/back, versioned keys, and explicit busting.',
      stage: 'foundation',
    },
    {
      id: 'cache-stampede',
      topicId: 'caching',
      title: 'Cache Stampede Protection',
      summary: 'Request coalescing, jittered TTLs, mutex + stale-while-revalidate.',
      stage: 'intermediate',
    },
    {
      id: 'cache-consistency',
      topicId: 'caching',
      title: 'Cache Consistency',
      summary: 'Read-after-write guarantees, write ordering, and source-of-truth rules.',
      stage: 'intermediate',
    },
    {
      id: 'cache-hot-keys',
      topicId: 'caching',
      title: 'Hot Key Mitigation',
      summary: 'Sharding, batching, local caches, and admission control for popular keys.',
      stage: 'intermediate',
    },
    {
      id: 'cache-serialization',
      topicId: 'caching',
      title: 'Serialization & Compression',
      summary: 'Payload shape, compression tradeoffs, and partial responses.',
      stage: 'foundation',
    },
    {
      id: 'cache-eviction-policies',
      topicId: 'caching',
      title: 'Eviction Policies',
      summary: 'LRU/LFU, ARC, and sizing strategies based on workload.',
      stage: 'foundation',
    },
    {
      id: 'cache-observability',
      topicId: 'caching',
      title: 'Observability',
      summary: 'Hit/miss rates, latency, churn, and stampede signals.',
      stage: 'foundation',
    },
    {
      id: 'cache-resilience',
      topicId: 'caching',
      title: 'Failure Behavior',
      summary: 'Fail-open vs fail-closed, throttling, and fallback data sources.',
      stage: 'intermediate',
    },
    {
      id: 'cache-population',
      topicId: 'caching',
      title: 'Warming & Prefetch',
      summary: 'Startup warming, predictive prefetch, and cohort-level cache building.',
      stage: 'advanced',
    },
    {
      id: 'cache-ownership',
      topicId: 'caching',
      title: 'Ownership & Governance',
      summary: 'Who owns keys, lifecycle, and cost accounting.',
      stage: 'advanced',
    },
  ],
  scenarioHooks: [
    {
      id: 'cache-traffic-spike',
      topicId: 'caching',
      title: 'Traffic spike reduces hit rate',
      backdrop: 'Marketing campaign doubles traffic.',
      trigger: 'Hit rate drops from 85% to 40% in 10 minutes.',
      relatedConcepts: ['cache-stampede', 'cache-population'],
    },
    {
      id: 'cache-stale-user',
      topicId: 'caching',
      title: 'User sees stale profile',
      backdrop: 'Profile edits take minutes to appear.',
      trigger: 'Write-through cache updates compete with heavy reads.',
      relatedConcepts: ['cache-consistency', 'cache-invalidation'],
    },
    {
      id: 'cache-hot-key',
      topicId: 'caching',
      title: 'Single key dominates traffic',
      backdrop: 'A trending product detail page drives 70% of requests.',
      trigger: 'Redis CPU spikes and tail latencies rise.',
      relatedConcepts: ['cache-hot-keys', 'cache-resilience'],
    },
    {
      id: 'cache-outage',
      topicId: 'caching',
      title: 'Cache node eviction',
      backdrop: 'A cache shard is evicted after a deployment.',
      trigger: 'Cold cache leads to cascading DB load.',
      relatedConcepts: ['cache-resilience', 'cache-population'],
    },
    {
      id: 'cache-compression',
      topicId: 'caching',
      title: 'Payload compression choice',
      backdrop: 'Bandwidth costs growing; cache fill takes longer.',
      trigger: 'Considering compressing cached payloads.',
      relatedConcepts: ['cache-serialization'],
    },
    {
       id: 'cache-launch-spike',
       topicId: 'caching',
       title: 'Product launch traffic spike',
       backdrop: 'Brand-new feature launches globally with cold caches.',
       trigger: 'DB write load and cache miss rate surge at launch hour.',
       relatedConcepts: ['cache-population', 'cache-stampede'],
     },
    {
       id: 'cache-stale-incident',
       topicId: 'caching',
       title: 'Stale profile incident',
       backdrop: 'Users complain that profile changes take hours to show.',
       trigger: 'Invalidation events drop during a deploy window.',
       relatedConcepts: ['cache-invalidation', 'cache-consistency'],
     },
    {
       id: 'cache-memory-pressure',
       topicId: 'caching',
       title: 'Memory pressure on cache cluster',
       backdrop: 'Evictions spike during peak traffic as node memory fills.',
       trigger: 'Hot keys crowd out long-tail items, increasing misses.',
       relatedConcepts: ['cache-eviction-policies', 'cache-hot-keys'],
     },
  ],
  constraintTemplates: [
    { id: 'cache-slo-30ms', topicId: 'caching', label: 'Latency', text: 'Cached reads must be <30ms p99', tags: ['latency'] },
    { id: 'cache-cost-cap', topicId: 'caching', label: 'Cost cap', text: 'No more than 3 additional cache nodes', tags: ['cost'] },
    { id: 'cache-freshness', topicId: 'caching', label: 'Freshness', text: 'User-facing data must be <5s stale after writes', tags: ['freshness'] },
    { id: 'cache-multi-tenant', topicId: 'caching', label: 'Multi-tenant', text: 'Keep tenants isolated; no cross-tenant key bleed', tags: ['multi-tenant'] },
    { id: 'cache-fail-open', topicId: 'caching', label: 'Fallback', text: 'When cache fails, service must degrade gracefully without cascading DB overload', tags: ['reliability'] },
  ],
  rubricTemplates: [
    {
      id: 'cache-performance-rubric',
      topicId: 'caching',
      archetype: 'performance',
      mustHave: ['Explains hit/miss math', 'Addresses stampede risks', 'Sizes cache with workload awareness'],
      niceToHave: ['Mentions prefetch or admission control'],
      redFlags: ['Blindly caches everything', 'Ignores invalidation plan'],
      scoringWeights: { clarity: 0.2, correctness: 0.25, depth: 0.2, pragmatism: 0.2, safety: 0.15 },
    },
    {
      id: 'cache-reliability-rubric',
      topicId: 'caching',
      archetype: 'reliability',
      mustHave: ['Defines failure behavior', 'Considers consistency and fallbacks', 'Covers observability signals'],
      niceToHave: ['Testing or chaos plan'],
      redFlags: ['Single point of failure cache', 'No fallback path'],
      scoringWeights: { clarity: 0.2, correctness: 0.2, depth: 0.2, pragmatism: 0.2, safety: 0.2 },
    },
    {
      id: 'cache-invalidation-rubric',
      topicId: 'caching',
      archetype: 'reliability',
      mustHave: [
        'Distinguishes TTL-based from event-driven invalidation',
        'Explains write-through vs write-behind tradeoffs',
        'Identifies consistency risk when cache and DB diverge',
      ],
      niceToHave: ['Mentions idempotent invalidation events'],
      redFlags: ['Assumes cache is always source of truth', 'No plan for partial failures'],
      scoringWeights: { clarity: 0.2, correctness: 0.2, depth: 0.2, pragmatism: 0.2, safety: 0.2 },
    },
    {
      id: 'cache-stampede-rubric',
      topicId: 'caching',
      archetype: 'performance',
      mustHave: [
        'Describes probabilistic early expiry or jitter',
        'Covers request coalescing or mutex to serialize refresh',
        'Explains fallback behavior during origin slowness',
      ],
      niceToHave: ['Mentions stale-while-revalidate'],
      redFlags: ['All traffic refreshes the same key simultaneously'],
      scoringWeights: { clarity: 0.2, correctness: 0.2, depth: 0.2, pragmatism: 0.2, safety: 0.2 },
    },
    {
      id: 'cache-eviction-rubric',
      topicId: 'caching',
      archetype: 'architecture',
      mustHave: [
        'Compares LRU, LFU, FIFO with workload fit',
        'Identifies hot-key skew impact on eviction',
        'Sizes cache or partitioning to reduce churn',
      ],
      niceToHave: ['Mentions admission control or segmented LRU'],
      redFlags: ['Picks policy without workload justification'],
      scoringWeights: { clarity: 0.2, correctness: 0.2, depth: 0.2, pragmatism: 0.2, safety: 0.2 },
    },
    {
      id: 'cache-consistency-rubric',
      topicId: 'caching',
      archetype: 'architecture',
      mustHave: [
        'Contrasts cache-aside, read-through, and write-through',
        'Explains strong vs eventual consistency implications',
        'Describes ordering/invalidations to avoid stale reads',
      ],
      niceToHave: ['Mentions versioned keys or write fencing'],
      redFlags: ['Ignores race between DB write and cache refill'],
      scoringWeights: { clarity: 0.2, correctness: 0.2, depth: 0.2, pragmatism: 0.2, safety: 0.2 },
    },
    {
      id: 'cache-monitoring-rubric',
      topicId: 'caching',
      archetype: 'reliability',
      mustHave: [
        'Tracks hit/miss and eviction rates with thresholds',
        'Observes latency percentiles for cache and origin',
        'Defines alerts for stampede and key skew signals',
      ],
      niceToHave: ['Breaks down metrics by key space or tenant'],
      redFlags: ['No telemetry for cache effectiveness'],
      scoringWeights: { clarity: 0.2, correctness: 0.2, depth: 0.2, pragmatism: 0.2, safety: 0.2 },
    },
  ],
  questionFamilies: [
    {
      key: 'cache-layer-plan',
      topicId: 'caching',
      archetype: 'architecture',
      stem: 'Design layered caches for a read-heavy API.',
      framing: 'Edge vs service cache responsibilities and invalidation.',
      primaryConcepts: ['cache-layering', 'cache-invalidation'],
      supportingConcepts: ['cache-serialization'],
      defaultConstraints: ['cache-slo-30ms'],
      defaultRubricId: 'cache-performance-rubric',
      phrasingSkeleton: 'Describe a layered caching approach and invalidation story.',
    },
    {
      key: 'cache-stampede-guard',
      topicId: 'caching',
      archetype: 'performance',
      stem: 'Prevent stampedes during expiry.',
      framing: 'Request coalescing, jitter, and stale-while-revalidate plan.',
      primaryConcepts: ['cache-stampede', 'cache-resilience'],
      defaultConstraints: ['cache-fail-open'],
      defaultRubricId: 'cache-reliability-rubric',
      phrasingSkeleton: 'Guard against cache stampedes with a concrete plan.',
    },
    {
      key: 'cache-hotspot-strategy',
      topicId: 'caching',
      archetype: 'performance',
      stem: 'Handle hot keys without melting the cache.',
      framing: 'Sharding, batching, or local caches for skew.',
      primaryConcepts: ['cache-hot-keys', 'cache-eviction-policies'],
      defaultConstraints: ['cache-cost-cap'],
      defaultRubricId: 'cache-performance-rubric',
      phrasingSkeleton: 'Mitigate a hot cache key under heavy load.',
    },
    {
      key: 'cache-consistency-plan',
      topicId: 'caching',
      archetype: 'reliability',
      stem: 'Guarantee freshness bounds after writes.',
      framing: 'Write-through/back choice, TTLs, and ordering controls.',
      primaryConcepts: ['cache-consistency', 'cache-invalidation'],
      defaultConstraints: ['cache-freshness'],
      defaultRubricId: 'cache-reliability-rubric',
      phrasingSkeleton: 'Explain cache consistency and freshness strategy.',
    },
    {
      key: 'cache-warmup',
      topicId: 'caching',
      archetype: 'architecture',
      stem: 'Warm and monitor caches after deploys.',
      framing: 'Prefetch strategy, health checks, and rollback triggers.',
      primaryConcepts: ['cache-population', 'cache-observability'],
      defaultConstraints: ['cache-fail-open'],
      defaultRubricId: 'cache-reliability-rubric',
      phrasingSkeleton: 'Describe cache warmup and rollback signals.',
    },
    {
      key: 'cache-invalidation',
      topicId: 'caching',
      archetype: 'reliability',
      stem: 'Plan cache invalidation that keeps data fresh.',
      framing: 'TTL vs event-driven invalidation; write-through vs write-behind.',
      primaryConcepts: ['cache-invalidation', 'cache-consistency'],
      defaultConstraints: ['cache-freshness'],
      defaultRubricId: 'cache-invalidation-rubric',
      phrasingSkeleton: 'Choose invalidation (TTL or events) and justify write-through vs write-behind; outline failure-safe path. / How do you keep cache and DB consistent during updates and deploys?'
    },
    {
      key: 'cache-stampede',
      topicId: 'caching',
      archetype: 'performance',
      stem: 'Stop thundering herds on popular keys.',
      framing: 'Probabilistic early expiry, mutex/locking, background refresh.',
      primaryConcepts: ['cache-stampede', 'cache-resilience'],
      defaultConstraints: ['cache-fail-open'],
      defaultRubricId: 'cache-stampede-rubric',
      phrasingSkeleton: 'Design stampede protection: jittered TTL + request coalescing + stale-while-revalidate. / How will you prevent many workers from refreshing the same hot key together?'
    },
    {
      key: 'cache-eviction',
      topicId: 'caching',
      archetype: 'architecture',
      stem: 'Pick the right eviction policy.',
      framing: 'LRU vs LFU vs FIFO and when to use each.',
      primaryConcepts: ['cache-eviction-policies', 'cache-hot-keys'],
      defaultConstraints: ['cache-cost-cap'],
      defaultRubricId: 'cache-eviction-rubric',
      phrasingSkeleton: 'Choose and tune eviction for this workload; defend tradeoffs. / How would you mitigate churn and hot-key dominance when picking an eviction policy?'
    },
    {
      key: 'cache-consistency',
      topicId: 'caching',
      archetype: 'architecture',
      stem: 'Keep distributed caches consistent enough.',
      framing: 'Strong vs eventual consistency; cache-aside vs read-through.',
      primaryConcepts: ['cache-consistency', 'cache-invalidation'],
      defaultConstraints: ['cache-freshness'],
      defaultRubricId: 'cache-consistency-rubric',
      phrasingSkeleton: 'Pick cache-aside/read-through and explain consistency + ordering; include fallback when origin lags. / How do you avoid stale reads when multiple regions update the same keys?'
    },
    {
      key: 'cache-monitoring',
      topicId: 'caching',
      archetype: 'reliability',
      stem: 'Instrument cache effectiveness and risk.',
      framing: 'Hit/miss, eviction rate, latency percentiles, alerts.',
      primaryConcepts: ['cache-observability', 'cache-resilience'],
      defaultConstraints: ['cache-slo-30ms'],
      defaultRubricId: 'cache-monitoring-rubric',
      phrasingSkeleton: 'Define cache SLOs and dashboards (hit/miss, evictions, latency); alert on stampede risk. / How do you prove the cache is helping and detect regressions quickly?'
    },
  ],
  learningResources: [
    { title: 'Redis Patterns', url: 'https://redis.io/resources' },
    { title: 'Caching at Scale Notes', note: 'Internal placeholder' },
    { title: 'Stale-While-Revalidate primer', url: 'https://web.dev/stale-while-revalidate/' },
  ],
};

export default cachingPack;
