import { TopicPack } from '../topic-pack.types';

export const concurrencyPack: TopicPack = {
  topicId: 'concurrency',
  label: 'Concurrency',
  description: 'Reasoning about correctness and performance under concurrent execution.',
  archetypes: ['runtime', 'reliability', 'performance', 'architecture'],
  concepts: [
    { id: 'conc-race-conditions', topicId: 'concurrency', title: 'Race Conditions', summary: 'Lost updates, read-modify-write hazards, and detection.', stage: 'foundation' },
    { id: 'conc-deadlocks', topicId: 'concurrency', title: 'Deadlocks', summary: 'Coffman conditions, avoidance, and detection tooling.', stage: 'foundation' },
    { id: 'conc-locking', topicId: 'concurrency', title: 'Locking Strategies', summary: 'Mutex, RW locks, optimistic vs pessimistic control.', stage: 'foundation' },
    { id: 'conc-atomicity', topicId: 'concurrency', title: 'Atomic Primitives', summary: 'CAS, fences, and memory ordering basics.', stage: 'intermediate' },
    { id: 'conc-scheduling', topicId: 'concurrency', title: 'Scheduling', summary: 'Thread pools, cooperative vs preemptive models.', stage: 'foundation' },
    { id: 'conc-async-models', topicId: 'concurrency', title: 'Async Models', summary: 'Futures/promises, async/await, and reactor patterns.', stage: 'intermediate' },
    { id: 'conc-parallelism', topicId: 'concurrency', title: 'Parallelism vs Concurrency', summary: 'CPU-bound vs IO-bound distinctions and work stealing.', stage: 'foundation' },
    { id: 'conc-idempotency', topicId: 'concurrency', title: 'Idempotency & Reentrancy', summary: 'Safe retries and reentrant code requirements.', stage: 'intermediate' },
    { id: 'conc-shared-resources', topicId: 'concurrency', title: 'Shared Resource Management', summary: 'Connection pools, file descriptors, and limits.', stage: 'intermediate' },
    { id: 'conc-observability', topicId: 'concurrency', title: 'Observability', summary: 'Tracing async boundaries, contention metrics, and profiling.', stage: 'foundation' },
    { id: 'conc-failure-modes', topicId: 'concurrency', title: 'Failure Modes', summary: 'Livelock, starvation, and priority inversion.', stage: 'advanced' },
  ],
  scenarioHooks: [
    { id: 'conc-deadlock-incident', topicId: 'concurrency', title: 'Deadlock in production', backdrop: 'Release introduces a deadlock in payment service.', trigger: 'Threads pile up waiting on locks.', relatedConcepts: ['conc-deadlocks', 'conc-locking'] },
    { id: 'conc-cpu-saturation', topicId: 'concurrency', title: 'CPU-bound tasks block progress', backdrop: 'Background reports hog CPU.', trigger: 'Async tasks run on limited thread pool.', relatedConcepts: ['conc-parallelism', 'conc-scheduling'] },
    { id: 'conc-starvation', topicId: 'concurrency', title: 'Starvation under priority queue', backdrop: 'Low priority tasks never execute.', trigger: 'Workers always pick urgent jobs.', relatedConcepts: ['conc-failure-modes', 'conc-scheduling'] },
    { id: 'conc-race', topicId: 'concurrency', title: 'Race in counters', backdrop: 'Metrics counters double-count intermittently.', trigger: 'Concurrent updates missing atomicity.', relatedConcepts: ['conc-atomicity', 'conc-race-conditions'] },
    { id: 'conc-retry-storm', topicId: 'concurrency', title: 'Retry storm after outage', backdrop: 'Clients retry aggressively after partial outage.', trigger: 'Shared DB pool exhausted.', relatedConcepts: ['conc-idempotency', 'conc-shared-resources'] },
  ],
  constraintTemplates: [
    { id: 'conc-latency', topicId: 'concurrency', label: 'Latency', text: 'Keep p99 under 120ms despite contention', tags: ['latency'] },
    { id: 'conc-safety', topicId: 'concurrency', label: 'Safety', text: 'No lost updates under concurrent writers', tags: ['correctness'] },
    { id: 'conc-resource-cap', topicId: 'concurrency', label: 'Resources', text: 'Thread pool cannot exceed 32 workers', tags: ['performance'] },
    { id: 'conc-rollback', topicId: 'concurrency', label: 'Recovery', text: 'Must be safe to retry operations after failure', tags: ['reliability'] },
  ],
  rubricTemplates: [
    {
      id: 'conc-correctness-rubric',
      topicId: 'concurrency',
      archetype: 'reliability',
      mustHave: ['Identifies shared mutable state', 'Proposes locking or atomic fixes', 'Covers deadlock/starvation risks'],
      niceToHave: ['Mentions testing/profiling tools'],
      redFlags: ['Hand-wavy thread safety claims'],
      scoringWeights: { clarity: 0.2, correctness: 0.28, depth: 0.22, pragmatism: 0.15, safety: 0.15 },
    },
    {
      id: 'conc-performance-rubric',
      topicId: 'concurrency',
      archetype: 'performance',
      mustHave: ['Distinguishes CPU vs IO bound', 'Tunes pools/batching', 'Mitigates contention'],
      niceToHave: ['Load test or profiling plan'],
      redFlags: ['Infinite pooling', 'Blocking inside async loops'],
      scoringWeights: { clarity: 0.2, correctness: 0.24, depth: 0.2, pragmatism: 0.2, safety: 0.16 },
    },
  ],
  questionFamilies: [
    {
      key: 'conc-deadlock-diagnosis',
      topicId: 'concurrency',
      archetype: 'reliability',
      stem: 'Diagnose and prevent a deadlock.',
      framing: 'Detection, ordering rules, and refactor plan.',
      primaryConcepts: ['conc-deadlocks', 'conc-locking'],
      defaultConstraints: ['conc-safety'],
      defaultRubricId: 'conc-correctness-rubric',
      phrasingSkeleton: 'Find and prevent a deadlock in a service.',
    },
    {
      key: 'conc-throughput-tuning',
      topicId: 'concurrency',
      archetype: 'performance',
      stem: 'Tune throughput for a mixed workload.',
      framing: 'Separate CPU and IO work, adjust pools, and avoid starvation.',
      primaryConcepts: ['conc-parallelism', 'conc-scheduling'],
      supportingConcepts: ['conc-observability'],
      defaultConstraints: ['conc-resource-cap'],
      defaultRubricId: 'conc-performance-rubric',
      phrasingSkeleton: 'Increase throughput with correct pool and batching choices.',
    },
    {
      key: 'conc-idempotent-retries',
      topicId: 'concurrency',
      archetype: 'reliability',
      stem: 'Make operations retry-safe.',
      framing: 'Idempotency keys, dedupe, and compensating actions.',
      primaryConcepts: ['conc-idempotency', 'conc-race-conditions'],
      defaultConstraints: ['conc-rollback'],
      defaultRubricId: 'conc-correctness-rubric',
      phrasingSkeleton: 'Design retry-safe logic without double work.',
    },
    {
      key: 'conc-contention-reduction',
      topicId: 'concurrency',
      archetype: 'performance',
      stem: 'Reduce lock contention in shared state.',
      framing: 'Data partitioning, lock granularity, and optimistic paths.',
      primaryConcepts: ['conc-locking', 'conc-shared-resources'],
      defaultConstraints: ['conc-latency'],
      defaultRubricId: 'conc-performance-rubric',
      phrasingSkeleton: 'Lower contention on a hot shared resource.',
    },
    {
      key: 'conc-observability-family',
      topicId: 'concurrency',
      archetype: 'runtime',
      stem: 'Expose signals for async correctness.',
      framing: 'Tracing async boundaries, surfacing lag, and profiling.',
      primaryConcepts: ['conc-observability', 'conc-failure-modes'],
      defaultConstraints: ['conc-safety'],
      defaultRubricId: 'conc-correctness-rubric',
      phrasingSkeleton: 'Instrument concurrency issues for fast debugging.',
    },
  ],
  learningResources: [
    { title: 'Mechanical Sympathy Blog', url: 'https://mechanical-sympathy.blogspot.com/' },
    { title: 'Concurrency Testing Patterns', note: 'Internal guide placeholder' },
    { title: 'Go Concurrency Patterns (conceptual)', url: 'https://go.dev/blog/pipelines' },
  ],
};

export default concurrencyPack;
