import { TopicPack } from '../topic-pack.types';

export const concurrencyPack: TopicPack = {
  topicId: 'concurrency',
  label: 'Concurrency',
  description: 'Reasoning about correctness and performance under concurrent execution.',
  archetypes: ['runtime', 'reliability', 'performance', 'architecture'],
  concepts: [
    { id: 'conc-race-conditions', topicId: 'concurrency', title: 'Race Conditions', summary: 'Lost updates, read-modify-write hazards, and detection.', stage: 'foundation' },
    { id: 'conc-deadlocks', topicId: 'concurrency', title: 'Deadlocks', summary: 'Coffman conditions, avoidance, and detection tooling.', stage: 'foundation' },
    { id: 'conc-locking', topicId: 'concurrency', title: 'Locking Strategies', summary: 'Mutex, RW locks, optimistic vs pessimistic control.', stage: 'foundation' },
    { id: 'conc-atomicity', topicId: 'concurrency', title: 'Atomic Primitives', summary: 'CAS, fences, and memory ordering basics.', stage: 'intermediate' },
    { id: 'conc-scheduling', topicId: 'concurrency', title: 'Scheduling', summary: 'Thread pools, cooperative vs preemptive models.', stage: 'foundation' },
    { id: 'conc-async-models', topicId: 'concurrency', title: 'Async Models', summary: 'Futures/promises, async/await, and reactor patterns.', stage: 'intermediate' },
    { id: 'conc-parallelism', topicId: 'concurrency', title: 'Parallelism vs Concurrency', summary: 'CPU-bound vs IO-bound distinctions and work stealing.', stage: 'foundation' },
    { id: 'conc-idempotency', topicId: 'concurrency', title: 'Idempotency & Reentrancy', summary: 'Safe retries and reentrant code requirements.', stage: 'intermediate' },
    { id: 'conc-shared-resources', topicId: 'concurrency', title: 'Shared Resource Management', summary: 'Connection pools, file descriptors, and limits.', stage: 'intermediate' },
    { id: 'conc-observability', topicId: 'concurrency', title: 'Observability', summary: 'Tracing async boundaries, contention metrics, and profiling.', stage: 'foundation' },
    { id: 'conc-failure-modes', topicId: 'concurrency', title: 'Failure Modes', summary: 'Livelock, starvation, and priority inversion.', stage: 'advanced' },
  ],
  scenarioHooks: [
    { id: 'conc-deadlock-incident', topicId: 'concurrency', title: 'Deadlock in production', backdrop: 'Release introduces a deadlock in payment service.', trigger: 'Threads pile up waiting on locks.', compatibleFamilies: ['conc-deadlock-diagnosis'], relatedConcepts: ['conc-deadlocks', 'conc-locking'] },
    { id: 'conc-cpu-saturation', topicId: 'concurrency', title: 'CPU-bound tasks block progress', backdrop: 'Background reports hog CPU.', trigger: 'Async tasks run on limited thread pool.', compatibleFamilies: ['conc-throughput-tuning'], relatedConcepts: ['conc-parallelism', 'conc-scheduling'] },
    { id: 'conc-starvation', topicId: 'concurrency', title: 'Starvation under priority queue', backdrop: 'Low priority tasks never execute.', trigger: 'Workers always pick urgent jobs.', compatibleFamilies: ['conc-throughput-tuning', 'conc-observability-family'], relatedConcepts: ['conc-failure-modes', 'conc-scheduling'] },
    { id: 'conc-race', topicId: 'concurrency', title: 'Race in counters', backdrop: 'Metrics counters double-count intermittently.', trigger: 'Concurrent updates missing atomicity.', compatibleFamilies: ['conc-contention-reduction', 'conc-observability-family'], relatedConcepts: ['conc-atomicity', 'conc-race-conditions'] },
    { id: 'conc-retry-storm', topicId: 'concurrency', title: 'Retry storm after outage', backdrop: 'Clients retry aggressively after partial outage.', trigger: 'Shared DB pool exhausted.', compatibleFamilies: ['conc-idempotent-retries', 'conc-contention-reduction'], relatedConcepts: ['conc-idempotency', 'conc-shared-resources'] },
    { id: 'conc-lock-order-inversion', topicId: 'concurrency', title: 'Lock order inversion', backdrop: 'Two hot code paths acquire the same locks in opposite order after a refactor.', trigger: 'Only a subset of workers freeze under peak traffic, making the deadlock intermittent.', compatibleFamilies: ['conc-lock-ordering-family', 'conc-deadlock-diagnosis'], relatedConcepts: ['conc-deadlocks', 'conc-locking'] },
    { id: 'conc-cancellation-leak', topicId: 'concurrency', title: 'Cancellation leak', backdrop: 'Client requests time out, but the background work they started keeps running for minutes.', trigger: 'Abandoned tasks continue holding semaphores and DB connections.', compatibleFamilies: ['conc-async-cancellation-family', 'conc-contention-reduction'], relatedConcepts: ['conc-async-models', 'conc-shared-resources'] },
    { id: 'conc-head-of-line-blocking', topicId: 'concurrency', title: 'Head-of-line blocking', backdrop: 'A single thread pool handles cheap requests and expensive batch jobs together.', trigger: 'Short operations wait behind long-running work even though CPU still has headroom.', compatibleFamilies: ['conc-thread-pool-isolation', 'conc-throughput-tuning', 'conc-livelock-starvation-family'], relatedConcepts: ['conc-scheduling', 'conc-parallelism'] },
  ],
  constraintTemplates: [
    { id: 'conc-latency', topicId: 'concurrency', label: 'Latency', text: 'Keep p99 under 120ms despite contention', tags: ['latency'] },
    { id: 'conc-safety', topicId: 'concurrency', label: 'Safety', text: 'No lost updates under concurrent writers', tags: ['correctness'] },
    { id: 'conc-resource-cap', topicId: 'concurrency', label: 'Resources', text: 'Thread pool cannot exceed 32 workers', tags: ['performance'] },
    { id: 'conc-rollback', topicId: 'concurrency', label: 'Recovery', text: 'Must be safe to retry operations after failure', tags: ['reliability'] },
  ],
  rubricTemplates: [
    {
      id: 'conc-correctness-rubric',
      topicId: 'concurrency',
      archetype: 'reliability',
      mustHave: ['Identifies shared mutable state', 'Proposes locking or atomic fixes', 'Covers deadlock/starvation risks'],
      niceToHave: ['Mentions testing/profiling tools'],
      redFlags: ['Hand-wavy thread safety claims'],
      scoringWeights: { clarity: 0.2, correctness: 0.28, depth: 0.22, pragmatism: 0.15, safety: 0.15 },
    },
    {
      id: 'conc-performance-rubric',
      topicId: 'concurrency',
      archetype: 'performance',
      mustHave: ['Distinguishes CPU vs IO bound', 'Tunes pools/batching', 'Mitigates contention'],
      niceToHave: ['Load test or profiling plan'],
      redFlags: ['Infinite pooling', 'Blocking inside async loops'],
      scoringWeights: { clarity: 0.2, correctness: 0.24, depth: 0.2, pragmatism: 0.2, safety: 0.16 },
    },
    {
      id: 'conc-lock-ordering-family-rubric',
      topicId: 'concurrency',
      archetype: 'reliability',
      mustHave: [
        'Defines a global lock acquisition order or hierarchy for shared resources',
        'Explains how try-lock, timeouts, or deadlock detection fit into the operational plan',
        'Shows how code review or instrumentation would catch order inversions before production',
      ],
      niceToHave: ['Mentions narrowing critical sections to reduce lock hold time'],
      redFlags: ['Relies on developer memory alone with no documented ordering rule'],
      scoringWeights: { clarity: 0.2, correctness: 0.25, depth: 0.2, pragmatism: 0.19, safety: 0.16 },
    },
    {
      id: 'conc-optimistic-concurrency-family-rubric',
      topicId: 'concurrency',
      archetype: 'architecture',
      mustHave: [
        'Explains compare-and-swap or version-check semantics for contested updates',
        'Describes retry behavior or user-visible conflict handling after optimistic failures',
        'Contrasts optimistic control with mutex-based serialization under different contention levels',
      ],
      niceToHave: ['Mentions ABA risk or version overflow in long-lived objects'],
      redFlags: ['Calls optimistic concurrency safe without any conflict detection primitive'],
      scoringWeights: { clarity: 0.2, correctness: 0.25, depth: 0.21, pragmatism: 0.18, safety: 0.16 },
    },
    {
      id: 'conc-thread-pool-isolation-rubric',
      topicId: 'concurrency',
      archetype: 'performance',
      mustHave: [
        'Separates CPU-bound work from latency-sensitive IO tasks using distinct pools or queues',
        'Sizes pools against core count, blocking behavior, and downstream resource caps',
        'Defines metrics such as queue depth and task wait time to detect head-of-line blocking',
      ],
      niceToHave: ['Mentions admission control or work shedding for oversized jobs'],
      redFlags: ['Puts all work on one large pool and expects fairness to emerge automatically'],
      scoringWeights: { clarity: 0.2, correctness: 0.24, depth: 0.21, pragmatism: 0.19, safety: 0.16 },
    },
    {
      id: 'conc-livelock-starvation-family-rubric',
      topicId: 'concurrency',
      archetype: 'runtime',
      mustHave: [
        'Distinguishes starvation or livelock from deadlock using observable system behavior',
        'Explains how scheduling policy, backoff, or priority inheritance changes progress guarantees',
        'Identifies the signal to monitor such as wait time skew or tasks making no forward progress',
      ],
      niceToHave: ['Mentions fairness tests under synthetic load'],
      redFlags: ['Diagnoses every blocked system as a deadlock without checking for forward progress'],
      scoringWeights: { clarity: 0.2, correctness: 0.24, depth: 0.2, pragmatism: 0.2, safety: 0.16 },
    },
    {
      id: 'conc-async-cancellation-family-rubric',
      topicId: 'concurrency',
      archetype: 'reliability',
      mustHave: [
        'Propagates cancellation or timeout signals to the actual work instead of only the caller',
        'Releases shared resources such as semaphores, DB connections, or file handles on cancellation paths',
        'Explains how partial side effects remain safe if a task is cancelled mid-flight',
      ],
      niceToHave: ['Mentions structured concurrency or cancellation scopes'],
      redFlags: ['Drops the caller request while background work continues mutating shared state unchecked'],
      scoringWeights: { clarity: 0.2, correctness: 0.25, depth: 0.2, pragmatism: 0.19, safety: 0.16 },
    },
  ],
  questionFamilies: [
    {
      key: 'conc-deadlock-diagnosis',
      topicId: 'concurrency',
      archetype: 'reliability',
      difficulty: 'hard',
      stem: 'Diagnose and prevent a deadlock.',
      framing: 'Detection, ordering rules, and refactor plan.',
      primaryConcepts: ['conc-deadlocks', 'conc-locking'],
      defaultConstraints: ['conc-safety'],
      defaultRubricId: 'conc-deadlock-diagnosis-rubric',
      phrasingSkeleton: 'Find and prevent a deadlock in a service.',
    },
    {
      key: 'conc-throughput-tuning',
      topicId: 'concurrency',
      archetype: 'performance',
      difficulty: 'hard',
      stem: 'Tune throughput for a mixed workload.',
      framing: 'Separate CPU and IO work, adjust pools, and avoid starvation.',
      primaryConcepts: ['conc-parallelism', 'conc-scheduling'],
      supportingConcepts: ['conc-observability'],
      defaultConstraints: ['conc-resource-cap'],
      defaultRubricId: 'conc-throughput-tuning-rubric',
      phrasingSkeleton: 'Increase throughput with correct pool and batching choices.',
    },
    {
      key: 'conc-idempotent-retries',
      topicId: 'concurrency',
      archetype: 'reliability',
      difficulty: 'medium',
      stem: 'Make operations retry-safe.',
      framing: 'Idempotency keys, dedupe, and compensating actions.',
      primaryConcepts: ['conc-idempotency', 'conc-race-conditions'],
      defaultConstraints: ['conc-rollback'],
      defaultRubricId: 'conc-idempotent-retries-rubric',
      phrasingSkeleton: 'Design retry-safe logic without double work.',
    },
    {
      key: 'conc-contention-reduction',
      topicId: 'concurrency',
      archetype: 'performance',
      difficulty: 'hard',
      stem: 'Reduce lock contention in shared state.',
      framing: 'Data partitioning, lock granularity, and optimistic paths.',
      primaryConcepts: ['conc-locking', 'conc-shared-resources'],
      defaultConstraints: ['conc-latency'],
      defaultRubricId: 'conc-contention-reduction-rubric',
      phrasingSkeleton: 'Lower contention on a hot shared resource.',
    },
    {
      key: 'conc-observability-family',
      topicId: 'concurrency',
      archetype: 'runtime',
      difficulty: 'medium',
      stem: 'Expose signals for async correctness.',
      framing: 'Tracing async boundaries, surfacing lag, and profiling.',
      primaryConcepts: ['conc-observability', 'conc-failure-modes'],
      defaultConstraints: ['conc-safety'],
      defaultRubricId: 'conc-observability-family-rubric',
      phrasingSkeleton: 'Instrument concurrency issues for fast debugging.',
    },
    {
      key: 'conc-lock-ordering-family',
      topicId: 'concurrency',
      archetype: 'reliability',
      difficulty: 'medium',
      stem: 'Prevent deadlocks with explicit lock ordering rules.',
      framing: 'Lock hierarchies, critical-section minimization, and detection of order inversions.',
      primaryConcepts: ['conc-locking', 'conc-deadlocks'],
      supportingConcepts: ['conc-observability'],
      defaultConstraints: ['conc-safety'],
      defaultRubricId: 'conc-lock-ordering-family-rubric',
      phrasingSkeleton: 'Two services now acquire account and ledger locks in different orders; how would you define and enforce a lock-ordering strategy that prevents intermittent deadlocks?',
    },
    {
      key: 'conc-optimistic-concurrency-family',
      topicId: 'concurrency',
      archetype: 'architecture',
      difficulty: 'hard',
      stem: 'Choose optimistic concurrency when locking is too costly.',
      framing: 'CAS/version checks, retry policy, and contention thresholds.',
      primaryConcepts: ['conc-atomicity', 'conc-race-conditions'],
      supportingConcepts: ['conc-idempotency'],
      defaultConstraints: ['conc-safety'],
      defaultRubricId: 'conc-optimistic-concurrency-family-rubric',
      phrasingSkeleton: 'A hot counter update path is spending too much time under locks; when would you switch to optimistic concurrency, and what conflict-handling strategy would you use?',
    },
    {
      key: 'conc-thread-pool-isolation',
      topicId: 'concurrency',
      archetype: 'performance',
      difficulty: 'hard',
      stem: 'Isolate workloads so long tasks stop blocking short ones.',
      framing: 'Separate pools, queueing policy, and admission control under mixed load.',
      primaryConcepts: ['conc-scheduling', 'conc-parallelism'],
      supportingConcepts: ['conc-shared-resources'],
      defaultConstraints: ['conc-resource-cap', 'conc-latency'],
      defaultRubricId: 'conc-thread-pool-isolation-rubric',
      phrasingSkeleton: 'A single worker pool serves short RPC work and expensive batch jobs; how would you redesign concurrency controls so tail latency drops without oversubscribing the machine?',
    },
    {
      key: 'conc-livelock-starvation-family',
      topicId: 'concurrency',
      archetype: 'runtime',
      difficulty: 'hard',
      stem: 'Diagnose systems that are active but not making progress.',
      framing: 'Livelock, starvation, priority inversion, and fairness signals.',
      primaryConcepts: ['conc-failure-modes', 'conc-scheduling'],
      supportingConcepts: ['conc-observability'],
      defaultConstraints: ['conc-latency'],
      defaultRubricId: 'conc-livelock-starvation-family-rubric',
      phrasingSkeleton: 'Workers are busy and nothing is technically deadlocked, yet low-priority tasks never finish; how would you tell whether this is starvation, livelock, or priority inversion, and what would you change?',
    },
    {
      key: 'conc-async-cancellation-family',
      topicId: 'concurrency',
      archetype: 'reliability',
      difficulty: 'medium',
      stem: 'Cancel concurrent work safely when callers disappear.',
      framing: 'Timeout propagation, cleanup, and preventing orphaned side effects.',
      primaryConcepts: ['conc-async-models', 'conc-shared-resources'],
      supportingConcepts: ['conc-idempotency'],
      defaultConstraints: ['conc-rollback'],
      defaultRubricId: 'conc-async-cancellation-family-rubric',
      phrasingSkeleton: 'A request times out, but the tasks it launched keep running and holding resources; how would you propagate cancellation and keep the system safe?',
    },
  ],
  learningResources: [
    { title: 'Mechanical Sympathy Blog', url: 'https://mechanical-sympathy.blogspot.com/' },
    { title: 'Concurrency Testing Patterns', note: 'Internal guide placeholder' },
    { title: 'Go Concurrency Patterns (conceptual)', url: 'https://go.dev/blog/pipelines' },
  ],
};

export default concurrencyPack;
