import { TopicPack } from '../topic-pack.types';

export const databasesPack: TopicPack = {
  topicId: 'databases',
  label: 'Databases',
  description: 'Physical design, query behavior, and operational patterns for transactional and analytical stores.',
  archetypes: ['data', 'performance', 'reliability', 'integration'],
  concepts: [
    {
      id: 'db-indexing-btree',
      topicId: 'databases',
      title: 'Indexing (B-Tree & Hash)',
      summary: 'How indexes are laid out, fan out, selectivity, and maintenance cost.',
      stage: 'foundation',
    },
    {
      id: 'db-query-plans',
      topicId: 'databases',
      title: 'Query Plans',
      summary: 'Optimizer choices, cardinality estimates, join order, and parameter sniffing.',
      stage: 'intermediate',
    },
    {
      id: 'db-transaction-isolation',
      topicId: 'databases',
      title: 'Isolation & MVCC',
      summary: 'Phantoms, snapshot isolation, write skew, and conflict resolution.',
      stage: 'foundation',
    },
    {
      id: 'db-locking',
      topicId: 'databases',
      title: 'Locks & Latches',
      summary: 'Row/page locks, intent locks, deadlocks, and lock escalation.',
      stage: 'intermediate',
      prerequisites: ['db-transaction-isolation'],
    },
    {
      id: 'db-sharding',
      topicId: 'databases',
      title: 'Sharding & Partitioning',
      summary: 'Keys, rebalancing, co-location of hot rows, and cross-shard queries.',
      stage: 'advanced',
      prerequisites: ['db-indexing-btree'],
    },
    {
      id: 'db-replication',
      topicId: 'databases',
      title: 'Replication Topologies',
      summary: 'Leader/follower, multi-leader, async vs sync, and lag handling.',
      stage: 'intermediate',
    },
    {
      id: 'db-backups',
      topicId: 'databases',
      title: 'Backups & PITR',
      summary: 'Base backups, WAL archiving, RPO/RTO, and verification drills.',
      stage: 'intermediate',
    },
    {
      id: 'db-connection-pooling',
      topicId: 'databases',
      title: 'Connection Management',
      summary: 'Pool sizing, queueing, transaction timeouts, and cancellation.',
      stage: 'foundation',
    },
    {
      id: 'db-data-modeling',
      topicId: 'databases',
      title: 'Data Modeling',
      summary: 'Normalization, denormalization, JSON columns, and migration paths.',
      stage: 'foundation',
    },
    {
      id: 'db-analytics-vs-oltp',
      topicId: 'databases',
      title: 'OLTP vs OLAP',
      summary: 'Workload separation, columnar stores, ingestion tradeoffs.',
      stage: 'intermediate',
    },
    {
      id: 'db-hotspot-mitigation',
      topicId: 'databases',
      title: 'Hotspot Mitigation',
      summary: 'Randomized keys, hash vs range splits, and throttling strategies.',
      stage: 'advanced',
    },
    {
      id: 'db-observability',
      topicId: 'databases',
      title: 'Observability & Tuning',
      summary: 'Slow query logs, plan cache analysis, and index health metrics.',
      stage: 'foundation',
    },
  ],
  scenarioHooks: [
    {
      id: 'db-slow-report',
      topicId: 'databases',
      title: 'Slow monthly report',
      backdrop: 'A monthly revenue report now takes 40 minutes and blocks other jobs.',
      trigger: 'CPU and I/O surge during report window.',
      compatibleFamilies: ['db-index-strategy'],
      relatedConcepts: ['db-query-plans', 'db-analytics-vs-oltp'],
    },
    {
      id: 'db-hot-tenant',
      topicId: 'databases',
      title: 'Noisy tenant',
      backdrop: 'One SaaS tenant produces 60% of writes.',
      trigger: 'Other tenants see latency spikes and lock waits.',
      compatibleFamilies: ['db-partitioning'],
      relatedConcepts: ['db-sharding', 'db-hotspot-mitigation'],
    },
    {
      id: 'db-read-lag',
      topicId: 'databases',
      title: 'Replica lag',
      backdrop: 'Read replicas fall behind during traffic spikes.',
      trigger: 'Stale reads break dashboards.',
      compatibleFamilies: ['db-connection-safety', 'db-replication-plan'],
      relatedConcepts: ['db-replication', 'db-connection-pooling'],
    },
    {
      id: 'db-long-tx',
      topicId: 'databases',
      title: 'Long transaction',
      backdrop: 'An ETL job holds transactions for minutes.',
      trigger: 'Deadlocks and autovacuum bloat show up.',
      compatibleFamilies: ['db-connection-safety'],
      relatedConcepts: ['db-locking', 'db-transaction-isolation'],
    },
    {
      id: 'db-restore-drill',
      topicId: 'databases',
      title: 'Restore drill',
      backdrop: 'Compliance asks for a 1-hour RPO and 30-minute RTO proof.',
      trigger: 'Backups exist but have not been validated in months.',
      compatibleFamilies: ['db-replication-plan'],
      relatedConcepts: ['db-backups'],
    },
    {
      id: 'db-plan-regression',
      topicId: 'databases',
      title: 'Plan regression after release',
      backdrop: 'A previously fast query slows down immediately after a schema and app deployment.',
      trigger: 'Cardinality estimates shift and the optimizer starts choosing a nested loop over a large table.',
      compatibleFamilies: ['db-query-plan-regression', 'db-index-strategy'],
      relatedConcepts: ['db-query-plans', 'db-indexing-btree'],
    },
    {
      id: 'db-write-skew',
      topicId: 'databases',
      title: 'Write skew incident',
      backdrop: 'Two schedulers update on-call coverage records at the same time and both succeed.',
      trigger: 'Snapshot isolation allows a correctness bug even though no row-level conflict fires.',
      compatibleFamilies: ['db-isolation-anomalies', 'db-replication-plan'],
      relatedConcepts: ['db-transaction-isolation', 'db-locking'],
    },
    {
      id: 'db-backup-gap',
      topicId: 'databases',
      title: 'Backup restore gap',
      backdrop: 'The team has nightly backups and WAL archives, but nobody knows whether point-in-time recovery still works.',
      trigger: 'An auditor asks for evidence that a tenant can be restored to a precise timestamp.',
      compatibleFamilies: ['db-backup-restore-drill', 'db-migration-path'],
      relatedConcepts: ['db-backups', 'db-data-modeling'],
    },
  ],
  constraintTemplates: [
    { id: 'db-slo-50ms', topicId: 'databases', label: 'Latency', text: 'p99 read latency under 50ms', tags: ['latency'] },
    { id: 'db-cost-cap', topicId: 'databases', label: 'Cost', text: 'Must fit within existing cluster; no new primary nodes this quarter', tags: ['cost'] },
    { id: 'db-migration-compat', topicId: 'databases', label: 'Migration', text: 'Zero-downtime schema changes; dual-write if needed', tags: ['delivery'] },
    { id: 'db-audit', topicId: 'databases', label: 'Auditability', text: 'All writes need audit trail with actor and timestamp', tags: ['compliance'] },
    { id: 'db-multi-tenant', topicId: 'databases', label: 'Multi-tenant', text: 'Tenants isolated at logical level; avoid noisy neighbor bleed', tags: ['multi-tenant'] },
  ],
  rubricTemplates: [
    {
      id: 'db-performance-rubric',
      topicId: 'databases',
      archetype: 'performance',
      mustHave: ['States target latency/throughput', 'Chooses suitable indexes or partitions', 'Addresses plan regressions'],
      niceToHave: ['Mentions plan cache/parameter sniffing fixes'],
      redFlags: ['Suggests adding indexes without workload analysis', 'Ignores write amplification'],
      scoringWeights: { clarity: 0.2, correctness: 0.25, depth: 0.2, pragmatism: 0.2, safety: 0.15 },
    },
    {
      id: 'db-reliability-rubric',
      topicId: 'databases',
      archetype: 'reliability',
      mustHave: ['Describes backup + restore', 'Covers replication lag/failover', 'Considers data correctness'],
      niceToHave: ['Runbook or drill cadence'],
      redFlags: ['Writes to replicas', 'Assumes failover is free'],
      scoringWeights: { clarity: 0.2, correctness: 0.2, depth: 0.2, pragmatism: 0.2, safety: 0.2 },
    },
    {
      id: 'db-data-rubric',
      topicId: 'databases',
      archetype: 'data',
      mustHave: ['Explains data model impact', 'Addresses migration path', 'Talks about correctness/constraints'],
      niceToHave: ['Considers observability of data drift'],
      redFlags: ['Hand-wavy consistency claims'],
      scoringWeights: { clarity: 0.2, correctness: 0.25, depth: 0.2, pragmatism: 0.2, safety: 0.15 },
    },
    {
      id: 'db-isolation-anomalies-rubric',
      topicId: 'databases',
      archetype: 'reliability',
      mustHave: [
        'Identifies the specific anomaly such as write skew, phantom read, or lost update',
        'Maps the problem to a concrete isolation level or locking behavior',
        'Proposes a fix using stronger isolation, explicit locking, or constraint-based correctness checks',
      ],
      niceToHave: ['Mentions retry handling for serialization failures'],
      redFlags: ['Claims snapshot isolation prevents all business-level races', 'Uses SERIALIZABLE everywhere without discussing cost'],
      scoringWeights: { clarity: 0.2, correctness: 0.26, depth: 0.21, pragmatism: 0.17, safety: 0.16 },
    },
    {
      id: 'db-covering-index-family-rubric',
      topicId: 'databases',
      archetype: 'performance',
      mustHave: [
        'Explains how key column order affects seekability for the target predicates',
        'Uses included columns or covering indexes to avoid extra heap lookups when appropriate',
        'Accounts for write amplification and index maintenance cost on hot tables',
      ],
      niceToHave: ['Mentions partial indexes for skewed predicates'],
      redFlags: ['Adds overlapping indexes without checking whether one can satisfy multiple query shapes'],
      scoringWeights: { clarity: 0.2, correctness: 0.25, depth: 0.2, pragmatism: 0.19, safety: 0.16 },
    },
    {
      id: 'db-backup-restore-drill-rubric',
      topicId: 'databases',
      archetype: 'reliability',
      mustHave: [
        'Defines RPO and RTO using base backups plus WAL/binlog recovery steps',
        'Verifies backups by restoring into an isolated environment and checking data correctness',
        'Explains how to restore a specific tenant or point in time without overwriting the primary',
      ],
      niceToHave: ['Mentions checksum verification or restore automation runbooks'],
      redFlags: ['Counts a successful backup job as proof that restores work'],
      scoringWeights: { clarity: 0.2, correctness: 0.24, depth: 0.2, pragmatism: 0.2, safety: 0.16 },
    },
    {
      id: 'db-query-plan-regression-rubric',
      topicId: 'databases',
      archetype: 'performance',
      mustHave: [
        'Compares old and new execution plans to isolate the operator causing the regression',
        'Explains how stale statistics, skew, or parameter sniffing changed optimizer behavior',
        'Proposes a durable fix such as stats refresh, query rewrite, or index adjustment',
      ],
      niceToHave: ['Mentions plan forcing only as a short-term mitigation with review'],
      redFlags: ['Treats adding CPU as the primary fix for a bad execution plan'],
      scoringWeights: { clarity: 0.2, correctness: 0.26, depth: 0.21, pragmatism: 0.18, safety: 0.15 },
    },
    {
      id: 'db-audit-trail-model-rubric',
      topicId: 'databases',
      archetype: 'data',
      mustHave: [
        'Captures actor, timestamp, and before/after values or immutable event payloads for writes',
        'Explains how audit records stay transactionally aligned with the source write path',
        'Designs indexes or retention strategy so audit queries do not overload OLTP traffic',
      ],
      niceToHave: ['Mentions tamper evidence or append-only storage boundaries'],
      redFlags: ['Stores audit data only in application logs with no durability or query path'],
      scoringWeights: { clarity: 0.2, correctness: 0.24, depth: 0.2, pragmatism: 0.2, safety: 0.16 },
    },
  ],
  questionFamilies: [
    {
      key: 'db-index-strategy',
      topicId: 'databases',
      archetype: 'performance',
      difficulty: 'medium',
      stem: 'Tune a read-heavy workload with the right index shape.',
      framing: 'Balance read speed, write cost, and maintenance.',
      primaryConcepts: ['db-indexing-btree', 'db-query-plans'],
      supportingConcepts: ['db-data-modeling'],
      defaultConstraints: ['db-slo-50ms'],
      defaultRubricId: 'db-index-strategy-rubric',
      phrasingSkeleton: 'Pick and justify indexes for a slow query pattern.',
    },
    {
      key: 'db-connection-safety',
      topicId: 'databases',
      archetype: 'reliability',
      difficulty: 'medium',
      stem: 'Stabilize database connections under spiky traffic.',
      framing: 'Pool sizing, timeouts, cancellations, and protection of primaries.',
      primaryConcepts: ['db-connection-pooling', 'db-backpressure'],
      supportingConcepts: ['db-replication'],
      defaultConstraints: ['db-cost-cap'],
      defaultRubricId: 'db-connection-safety-rubric',
      phrasingSkeleton: 'Control connections and protect the primary under load.',
    },
    {
      key: 'db-partitioning',
      topicId: 'databases',
      archetype: 'data',
      difficulty: 'hard',
      stem: 'Partition data to remove hotspots without breaking queries.',
      framing: 'Choose keys, mitigate skew, and plan rebalancing.',
      primaryConcepts: ['db-sharding', 'db-hotspot-mitigation'],
      defaultConstraints: ['db-multi-tenant'],
      defaultRubricId: 'db-partitioning-rubric',
      phrasingSkeleton: 'Partition a multi-tenant workload and avoid hot shards.',
    },
    {
      key: 'db-migration-path',
      topicId: 'databases',
      archetype: 'delivery',
      difficulty: 'medium',
      stem: 'Ship a schema change safely.',
      framing: 'Zero-downtime path, rollbacks, and compatibility windows.',
      primaryConcepts: ['db-data-modeling', 'db-backups'],
      supportingConcepts: ['db-transaction-isolation'],
      defaultConstraints: ['db-migration-compat'],
      defaultRubricId: 'db-migration-path-rubric',
      phrasingSkeleton: 'Explain a safe migration plan with rollback.',
    },
    {
      key: 'db-replication-plan',
      topicId: 'databases',
      archetype: 'reliability',
      difficulty: 'hard',
      stem: 'Design replication and failover for mixed workloads.',
      framing: 'Read replicas, lag handling, and promotion rules.',
      primaryConcepts: ['db-replication', 'db-transaction-isolation'],
      supportingConcepts: ['db-query-plans'],
      defaultConstraints: ['db-audit'],
      defaultRubricId: 'db-replication-plan-rubric',
      phrasingSkeleton: 'Plan replication and failover without corrupting data.',
    },
    {
      key: 'db-isolation-anomalies',
      topicId: 'databases',
      archetype: 'reliability',
      difficulty: 'hard',
      stem: 'Prevent correctness bugs caused by transaction isolation gaps.',
      framing: 'Write skew, phantoms, explicit locks, and retries after serialization conflicts.',
      primaryConcepts: ['db-transaction-isolation', 'db-locking'],
      supportingConcepts: ['db-data-modeling'],
      defaultConstraints: ['db-audit'],
      defaultRubricId: 'db-isolation-anomalies-rubric',
      phrasingSkeleton: 'Two concurrent transactions both pass validation and create an invalid state; how would you diagnose the isolation anomaly and fix it?',
    },
    {
      key: 'db-covering-index-family',
      topicId: 'databases',
      archetype: 'performance',
      difficulty: 'medium',
      stem: 'Design a covering index for a high-value query path.',
      framing: 'Column order, included columns, and the read-versus-write cost trade-off.',
      primaryConcepts: ['db-indexing-btree', 'db-query-plans'],
      supportingConcepts: ['db-observability'],
      defaultConstraints: ['db-slo-50ms', 'db-cost-cap'],
      defaultRubricId: 'db-covering-index-family-rubric',
      phrasingSkeleton: 'How would you choose the key order and included columns for an index that must speed up one hot query without crushing write performance?',
    },
    {
      key: 'db-backup-restore-drill',
      topicId: 'databases',
      archetype: 'reliability',
      difficulty: 'medium',
      stem: 'Prove backup and point-in-time recovery actually work.',
      framing: 'Restore drills, tenant-scoped recovery, and measurable RPO/RTO evidence.',
      primaryConcepts: ['db-backups', 'db-replication'],
      supportingConcepts: ['db-observability'],
      defaultConstraints: ['db-audit'],
      defaultRubricId: 'db-backup-restore-drill-rubric',
      phrasingSkeleton: 'What restore drill would you run to prove you can recover a production database to a specific timestamp within the promised RTO?',
    },
    {
      key: 'db-query-plan-regression',
      topicId: 'databases',
      archetype: 'performance',
      difficulty: 'hard',
      stem: 'Debug a sudden query plan regression.',
      framing: 'Compare execution plans, inspect estimates, and choose a durable remediation.',
      primaryConcepts: ['db-query-plans', 'db-observability'],
      supportingConcepts: ['db-indexing-btree'],
      defaultConstraints: ['db-slo-50ms'],
      defaultRubricId: 'db-query-plan-regression-rubric',
      phrasingSkeleton: 'A query that used to run in 80ms now takes 8 seconds after a release; how would you prove whether the execution plan changed and fix it safely?',
    },
    {
      key: 'db-audit-trail-model',
      topicId: 'databases',
      archetype: 'data',
      difficulty: 'medium',
      stem: 'Model an audit trail that is queryable and correct.',
      framing: 'Transactional consistency, append-only history, and retention/indexing trade-offs.',
      primaryConcepts: ['db-data-modeling', 'db-transaction-isolation'],
      supportingConcepts: ['db-backups'],
      defaultConstraints: ['db-audit'],
      defaultRubricId: 'db-audit-trail-model-rubric',
      phrasingSkeleton: 'How would you store audit history for regulated writes so investigators can reconstruct who changed what without slowing down the primary workload?',
    },
  ],
  learningResources: [
    { title: 'Use The Index, Luke!', url: 'https://use-the-index-luke.com/' },
    { title: 'Jepsen Analyses', url: 'https://jepsen.io/' },
    { title: 'Zero-downtime Migration Playbook', note: 'Internal placeholder' },
  ],
};

export default databasesPack;
