import { TopicPack } from '../topic-pack.types';

export const databasesPack: TopicPack = {
  topicId: 'databases',
  label: 'Databases',
  description: 'Physical design, query behavior, and operational patterns for transactional and analytical stores.',
  archetypes: ['data', 'performance', 'reliability', 'integration'],
  concepts: [
    {
      id: 'db-indexing-btree',
      topicId: 'databases',
      title: 'Indexing (B-Tree & Hash)',
      summary: 'How indexes are laid out, fan out, selectivity, and maintenance cost.',
      stage: 'foundation',
    },
    {
      id: 'db-query-plans',
      topicId: 'databases',
      title: 'Query Plans',
      summary: 'Optimizer choices, cardinality estimates, join order, and parameter sniffing.',
      stage: 'intermediate',
    },
    {
      id: 'db-transaction-isolation',
      topicId: 'databases',
      title: 'Isolation & MVCC',
      summary: 'Phantoms, snapshot isolation, write skew, and conflict resolution.',
      stage: 'foundation',
    },
    {
      id: 'db-locking',
      topicId: 'databases',
      title: 'Locks & Latches',
      summary: 'Row/page locks, intent locks, deadlocks, and lock escalation.',
      stage: 'intermediate',
      prerequisites: ['db-transaction-isolation'],
    },
    {
      id: 'db-sharding',
      topicId: 'databases',
      title: 'Sharding & Partitioning',
      summary: 'Keys, rebalancing, co-location of hot rows, and cross-shard queries.',
      stage: 'advanced',
      prerequisites: ['db-indexing-btree'],
    },
    {
      id: 'db-replication',
      topicId: 'databases',
      title: 'Replication Topologies',
      summary: 'Leader/follower, multi-leader, async vs sync, and lag handling.',
      stage: 'intermediate',
    },
    {
      id: 'db-backups',
      topicId: 'databases',
      title: 'Backups & PITR',
      summary: 'Base backups, WAL archiving, RPO/RTO, and verification drills.',
      stage: 'intermediate',
    },
    {
      id: 'db-connection-pooling',
      topicId: 'databases',
      title: 'Connection Management',
      summary: 'Pool sizing, queueing, transaction timeouts, and cancellation.',
      stage: 'foundation',
    },
    {
      id: 'db-data-modeling',
      topicId: 'databases',
      title: 'Data Modeling',
      summary: 'Normalization, denormalization, JSON columns, and migration paths.',
      stage: 'foundation',
    },
    {
      id: 'db-analytics-vs-oltp',
      topicId: 'databases',
      title: 'OLTP vs OLAP',
      summary: 'Workload separation, columnar stores, ingestion tradeoffs.',
      stage: 'intermediate',
    },
    {
      id: 'db-hotspot-mitigation',
      topicId: 'databases',
      title: 'Hotspot Mitigation',
      summary: 'Randomized keys, hash vs range splits, and throttling strategies.',
      stage: 'advanced',
    },
    {
      id: 'db-observability',
      topicId: 'databases',
      title: 'Observability & Tuning',
      summary: 'Slow query logs, plan cache analysis, and index health metrics.',
      stage: 'foundation',
    },
  ],
  scenarioHooks: [
    {
      id: 'db-slow-report',
      topicId: 'databases',
      title: 'Slow monthly report',
      backdrop: 'A monthly revenue report now takes 40 minutes and blocks other jobs.',
      trigger: 'CPU and I/O surge during report window.',
      relatedConcepts: ['db-query-plans', 'db-analytics-vs-oltp'],
    },
    {
      id: 'db-hot-tenant',
      topicId: 'databases',
      title: 'Noisy tenant',
      backdrop: 'One SaaS tenant produces 60% of writes.',
      trigger: 'Other tenants see latency spikes and lock waits.',
      relatedConcepts: ['db-sharding', 'db-hotspot-mitigation'],
    },
    {
      id: 'db-read-lag',
      topicId: 'databases',
      title: 'Replica lag',
      backdrop: 'Read replicas fall behind during traffic spikes.',
      trigger: 'Stale reads break dashboards.',
      relatedConcepts: ['db-replication', 'db-connection-pooling'],
    },
    {
      id: 'db-long-tx',
      topicId: 'databases',
      title: 'Long transaction',
      backdrop: 'An ETL job holds transactions for minutes.',
      trigger: 'Deadlocks and autovacuum bloat show up.',
      relatedConcepts: ['db-locking', 'db-transaction-isolation'],
    },
    {
      id: 'db-restore-drill',
      topicId: 'databases',
      title: 'Restore drill',
      backdrop: 'Compliance asks for a 1-hour RPO and 30-minute RTO proof.',
      trigger: 'Backups exist but have not been validated in months.',
      relatedConcepts: ['db-backups'],
    },
  ],
  constraintTemplates: [
    { id: 'db-slo-50ms', topicId: 'databases', label: 'Latency', text: 'p99 read latency under 50ms', tags: ['latency'] },
    { id: 'db-cost-cap', topicId: 'databases', label: 'Cost', text: 'Must fit within existing cluster; no new primary nodes this quarter', tags: ['cost'] },
    { id: 'db-migration-compat', topicId: 'databases', label: 'Migration', text: 'Zero-downtime schema changes; dual-write if needed', tags: ['delivery'] },
    { id: 'db-audit', topicId: 'databases', label: 'Auditability', text: 'All writes need audit trail with actor and timestamp', tags: ['compliance'] },
    { id: 'db-multi-tenant', topicId: 'databases', label: 'Multi-tenant', text: 'Tenants isolated at logical level; avoid noisy neighbor bleed', tags: ['multi-tenant'] },
  ],
  rubricTemplates: [
    {
      id: 'db-performance-rubric',
      topicId: 'databases',
      archetype: 'performance',
      mustHave: ['States target latency/throughput', 'Chooses suitable indexes or partitions', 'Addresses plan regressions'],
      niceToHave: ['Mentions plan cache/parameter sniffing fixes'],
      redFlags: ['Suggests adding indexes without workload analysis', 'Ignores write amplification'],
      scoringWeights: { clarity: 0.2, correctness: 0.25, depth: 0.2, pragmatism: 0.2, safety: 0.15 },
    },
    {
      id: 'db-reliability-rubric',
      topicId: 'databases',
      archetype: 'reliability',
      mustHave: ['Describes backup + restore', 'Covers replication lag/failover', 'Considers data correctness'],
      niceToHave: ['Runbook or drill cadence'],
      redFlags: ['Writes to replicas', 'Assumes failover is free'],
      scoringWeights: { clarity: 0.2, correctness: 0.2, depth: 0.2, pragmatism: 0.2, safety: 0.2 },
    },
    {
      id: 'db-data-rubric',
      topicId: 'databases',
      archetype: 'data',
      mustHave: ['Explains data model impact', 'Addresses migration path', 'Talks about correctness/constraints'],
      niceToHave: ['Considers observability of data drift'],
      redFlags: ['Hand-wavy consistency claims'],
      scoringWeights: { clarity: 0.2, correctness: 0.25, depth: 0.2, pragmatism: 0.2, safety: 0.15 },
    },
  ],
  questionFamilies: [
    {
      key: 'db-index-strategy',
      topicId: 'databases',
      archetype: 'performance',
      stem: 'Tune a read-heavy workload with the right index shape.',
      framing: 'Balance read speed, write cost, and maintenance.',
      primaryConcepts: ['db-indexing-btree', 'db-query-plans'],
      supportingConcepts: ['db-data-modeling'],
      defaultConstraints: ['db-slo-50ms'],
      defaultRubricId: 'db-performance-rubric',
      phrasingSkeleton: 'Pick and justify indexes for a slow query pattern.',
    },
    {
      key: 'db-connection-safety',
      topicId: 'databases',
      archetype: 'reliability',
      stem: 'Stabilize database connections under spiky traffic.',
      framing: 'Pool sizing, timeouts, cancellations, and protection of primaries.',
      primaryConcepts: ['db-connection-pooling', 'db-backpressure'],
      supportingConcepts: ['db-replication'],
      defaultConstraints: ['db-cost-cap'],
      defaultRubricId: 'db-reliability-rubric',
      phrasingSkeleton: 'Control connections and protect the primary under load.',
    },
    {
      key: 'db-partitioning',
      topicId: 'databases',
      archetype: 'data',
      stem: 'Partition data to remove hotspots without breaking queries.',
      framing: 'Choose keys, mitigate skew, and plan rebalancing.',
      primaryConcepts: ['db-sharding', 'db-hotspot-mitigation'],
      defaultConstraints: ['db-multi-tenant'],
      defaultRubricId: 'db-data-rubric',
      phrasingSkeleton: 'Partition a multi-tenant workload and avoid hot shards.',
    },
    {
      key: 'db-migration-path',
      topicId: 'databases',
      archetype: 'delivery',
      stem: 'Ship a schema change safely.',
      framing: 'Zero-downtime path, rollbacks, and compatibility windows.',
      primaryConcepts: ['db-data-modeling', 'db-backups'],
      supportingConcepts: ['db-transaction-isolation'],
      defaultConstraints: ['db-migration-compat'],
      defaultRubricId: 'db-data-rubric',
      phrasingSkeleton: 'Explain a safe migration plan with rollback.',
    },
    {
      key: 'db-replication-plan',
      topicId: 'databases',
      archetype: 'reliability',
      stem: 'Design replication and failover for mixed workloads.',
      framing: 'Read replicas, lag handling, and promotion rules.',
      primaryConcepts: ['db-replication', 'db-transaction-isolation'],
      supportingConcepts: ['db-query-plans'],
      defaultConstraints: ['db-audit'],
      defaultRubricId: 'db-reliability-rubric',
      phrasingSkeleton: 'Plan replication and failover without corrupting data.',
    },
  ],
  learningResources: [
    { title: 'Use The Index, Luke!', url: 'https://use-the-index-luke.com/' },
    { title: 'Jepsen Analyses', url: 'https://jepsen.io/' },
    { title: 'Zero-downtime Migration Playbook', note: 'Internal placeholder' },
  ],
};

export default databasesPack;
