import { TopicPack } from '../topic-pack.types';

export const javascriptPack: TopicPack = {
  topicId: 'javascript',
  label: 'JavaScript',
  description: 'Language foundations, runtime behavior, and practical patterns.',
  archetypes: ['runtime', 'performance', 'architecture', 'reliability'],
  concepts: [
    { id: 'js-closures', topicId: 'javascript', title: 'Closures & Scope', summary: 'Lexical scope, closure creation, and memory implications.', stage: 'foundation' },
    { id: 'js-prototype', topicId: 'javascript', title: 'Prototype Chain', summary: 'Prototype lookup, inheritance, and Object.create semantics.', stage: 'foundation' },
    { id: 'js-this-binding', topicId: 'javascript', title: '`this` Binding', summary: 'Call/apply/bind, arrow function behavior, and implicit binding.', stage: 'foundation' },
    { id: 'js-event-loop', topicId: 'javascript', title: 'Event Loop', summary: 'Task vs microtask queues, rendering frames, and ordering.', stage: 'foundation' },
    { id: 'js-promises', topicId: 'javascript', title: 'Promises & Async/Await', summary: 'Promise states, chaining, error propagation, and cancellation patterns.', stage: 'foundation' },
    { id: 'js-memory', topicId: 'javascript', title: 'Memory & GC', summary: 'Mark-and-sweep basics, leaks via closures or DOM references.', stage: 'intermediate' },
    { id: 'js-iterators', topicId: 'javascript', title: 'Iterators & Generators', summary: 'Custom iterables, lazy sequences, and async iterators.', stage: 'intermediate' },
    { id: 'js-modules', topicId: 'javascript', title: 'Modules', summary: 'ESM vs CJS semantics, import/export timing, tree-shaking basics.', stage: 'intermediate' },
    { id: 'js-types', topicId: 'javascript', title: 'Type Coercion', summary: '== vs ===, truthiness, and structural typing basics.', stage: 'foundation' },
    { id: 'js-dom-performance', topicId: 'javascript', title: 'DOM & Rendering Performance', summary: 'Layout thrash, debounce/throttle, and event delegation.', stage: 'intermediate' },
    { id: 'js-observability', topicId: 'javascript', title: 'Observability', summary: 'Console tracing, performance marks, and error boundaries.', stage: 'foundation' },
  ],
  scenarioHooks: [
    {
      id: 'js-memory-leak',
      topicId: 'javascript',
      title: 'Memory leak in SPA',
      backdrop: 'Long-running SPA slows down.',
      trigger: 'Heap grows after navigation.',
      compatibleFamilies: ['javascript.closures', 'javascript.memory_leaks'],
      relatedConcepts: ['js-memory', 'js-closures'],
    },
    {
      id: 'js-async-bug',
      topicId: 'javascript',
      title: 'Async ordering bug',
      backdrop: 'Animations stutter during async work.',
      trigger: 'Microtasks starve rendering.',
      compatibleFamilies: ['javascript.event_loop', 'javascript.promises_async', 'js-error-handling'],
      relatedConcepts: ['js-event-loop', 'js-promises'],
    },
    {
      id: 'js-nplusone-fetch',
      topicId: 'javascript',
      title: 'N+1 fetch in UI',
      backdrop: 'List view triggers many fetches.',
      trigger: 'Network waterfall hurts TTI.',
      compatibleFamilies: ['javascript.promises_async', 'javascript.event_loop', 'js-error-handling'],
      relatedConcepts: ['js-promises', 'js-event-loop'],
    },
    {
      id: 'js-module-conflict',
      topicId: 'javascript',
      title: 'Module type mismatch',
      backdrop: 'Bundler errors when mixing CJS and ESM.',
      trigger: 'Dynamic import path fails.',
      compatibleFamilies: ['js-modules'],
      relatedConcepts: ['js-modules'],
    },
    {
      id: 'js-debounce',
      topicId: 'javascript',
      title: 'Expensive input handler',
      backdrop: 'Search input floods network.',
      trigger: 'Need debounce/memoization.',
      compatibleFamilies: ['javascript.promises_async', 'javascript.event_loop'],
      relatedConcepts: ['js-dom-performance', 'js-promises'],
    },
    {
      id: 'js-prod-leak',
      topicId: 'javascript',
      title: 'Production memory leak',
      backdrop: 'Node service runs for days then restarts.',
      trigger: 'Heap grows with each cron batch.',
      compatibleFamilies: ['javascript.closures', 'javascript.memory_leaks'],
      relatedConcepts: ['js-memory', 'js-closures'],
    },
    {
      id: 'js-pr-async-bug',
      topicId: 'javascript',
      title: 'Async bug in PR review',
      backdrop: 'Reviewer spots inconsistent loading states.',
      trigger: 'Promise chain mixes await and then()',
      compatibleFamilies: ['javascript.promises_async', 'javascript.event_loop', 'js-error-handling'],
      relatedConcepts: ['js-promises', 'js-event-loop'],
    },
    {
      id: 'js-esm-migration',
      topicId: 'javascript',
      title: 'CommonJS to ESM migration',
      backdrop: 'Repo standardizes on ESM.',
      trigger: 'Circular dependency breaks after refactor.',
      compatibleFamilies: ['js-modules'],
      relatedConcepts: ['js-modules'],
    },
    {
      id: 'js-let-var-const-teammate-review',
      topicId: 'javascript',
      title: 'Variable declaration review',
      backdrop: 'You are reviewing JavaScript code with a teammate.',
      trigger: 'They ask you to explain when to use let, var, and const in everyday code.',
      compatibleFamilies: ['javascript.let-var-const'],
      relatedConcepts: ['js-types', 'js-closures'],
    },
    {
      id: 'js-let-var-const-colleague-explainer',
      topicId: 'javascript',
      title: 'Explaining scope rules',
      backdrop: 'A colleague asks you to explain JavaScript variable declarations before a refactor.',
      trigger: 'They want a crisp explanation of block scope, function scope, and reassignment rules.',
      compatibleFamilies: ['javascript.let-var-const'],
      relatedConcepts: ['js-types', 'js-closures'],
    },
    {
      id: 'js-null-undefined-review',
      topicId: 'javascript',
      title: 'Value state explanation',
      backdrop: 'You are reviewing JavaScript code with a teammate.',
      trigger: 'They ask how null, undefined, and undeclared variables differ during debugging.',
      compatibleFamilies: ['javascript.null-undefined'],
      relatedConcepts: ['js-types'],
    },
    {
      id: 'js-null-undefined-colleague-question',
      topicId: 'javascript',
      title: 'Checking missing values',
      backdrop: 'A colleague asks you to explain missing-value states in JavaScript.',
      trigger: 'They want to know how to identify null, undefined, and undeclared values safely.',
      compatibleFamilies: ['javascript.null-undefined'],
      relatedConcepts: ['js-types'],
    },
    {
      id: 'js-equality-teammate-review',
      topicId: 'javascript',
      title: 'Comparison operator review',
      backdrop: 'You are reviewing JavaScript code with a teammate.',
      trigger: 'They ask why one part of the codebase uses === almost everywhere instead of ==.',
      compatibleFamilies: ['javascript.equality'],
      relatedConcepts: ['js-types'],
    },
    {
      id: 'js-equality-colleague-explainer',
      topicId: 'javascript',
      title: 'Type coercion explainer',
      backdrop: 'A colleague asks you to explain JavaScript comparison behavior.',
      trigger: 'They want a simple explanation of strict equality, loose equality, and type coercion.',
      compatibleFamilies: ['javascript.equality'],
      relatedConcepts: ['js-types'],
    },
    {
      id: 'js-closures-private-state',
      topicId: 'javascript',
      title: 'Private state in a helper module',
      backdrop: 'A small helper module needs internal state that other files should not mutate directly.',
      trigger: 'You need to explain how closures can preserve private data across calls and where loop-related bugs can appear.',
      compatibleFamilies: ['javascript.closures-deep'],
      relatedConcepts: ['js-closures', 'js-memory'],
    },
    {
      id: 'js-closures-loop-bug',
      topicId: 'javascript',
      title: 'Loop callback bug',
      backdrop: 'A UI feature creates callbacks inside a loop and every callback prints the same value.',
      trigger: 'You need to explain why the closure captured the wrong binding and how to fix it safely.',
      compatibleFamilies: ['javascript.closures-deep'],
      relatedConcepts: ['js-closures', 'js-types'],
    },
    {
      id: 'js-event-delegation-dynamic-list',
      topicId: 'javascript',
      title: 'Dynamic list click handling',
      backdrop: 'A page renders dozens of interactive child elements and more can be added dynamically.',
      trigger: 'You need a cleaner event-handling approach than attaching a separate click listener to every child.',
      compatibleFamilies: ['javascript.event-delegation'],
      relatedConcepts: ['js-dom-performance'],
    },
    {
      id: 'js-event-delegation-form-controls',
      topicId: 'javascript',
      title: 'Large form interaction cleanup',
      backdrop: 'A form has many controls, each with its own event listener, and maintenance is getting messy.',
      trigger: 'You need to explain when delegation works, how event.target helps, and which events do not bubble.',
      compatibleFamilies: ['javascript.event-delegation'],
      relatedConcepts: ['js-dom-performance'],
    },
    {
      id: 'js-debounce-throttle-search',
      topicId: 'javascript',
      title: 'Search input floods requests',
      backdrop: 'A search box fires requests on every keystroke and the UI feels noisy and wasteful.',
      trigger: 'You need to choose between debounce and throttle to reduce high-frequency calls.',
      compatibleFamilies: ['javascript.debounce-throttle'],
      relatedConcepts: ['js-dom-performance', 'js-promises'],
    },
    {
      id: 'js-debounce-throttle-scroll',
      topicId: 'javascript',
      title: 'Scroll handler runs too often',
      backdrop: 'A scroll-driven feature performs expensive work continuously during user interaction.',
      trigger: 'You need to explain how debounce and throttle differ and which one fits this event stream.',
      compatibleFamilies: ['javascript.debounce-throttle'],
      relatedConcepts: ['js-dom-performance', 'js-observability'],
    },
  ],
  constraintTemplates: [
    { id: 'js-bundle-size', topicId: 'javascript', label: 'Bundle size', text: 'Keep bundle increase under 50KB', tags: ['performance'] },
    { id: 'js-compat', topicId: 'javascript', label: 'Compatibility', text: 'Must work on evergreen browsers + Node 18+', tags: ['compatibility'] },
    { id: 'js-latency', topicId: 'javascript', label: 'Responsiveness', text: 'UI thread must not block more than 16ms per frame', tags: ['latency'] },
  ],
  rubricTemplates: [
    {
      id: 'js-runtime-rubric',
      topicId: 'javascript',
      archetype: 'runtime',
      mustHave: ['Explains event loop ordering', 'Handles async errors', 'Considers memory impact'],
      niceToHave: ['Mentions profiling tooling'],
      redFlags: ['Blocking UI thread', 'Ignoring promise rejection'],
      scoringWeights: { clarity: 0.2, correctness: 0.26, depth: 0.2, pragmatism: 0.18, safety: 0.16 },
    },
    {
      id: 'js-architecture-rubric',
      topicId: 'javascript',
      archetype: 'architecture',
      mustHave: ['Chooses appropriate abstractions', 'Avoids over-fetching', 'Considers module boundaries'],
      niceToHave: ['Progressive enhancement mention'],
      redFlags: ['Global mutable state without isolation'],
      scoringWeights: { clarity: 0.2, correctness: 0.24, depth: 0.2, pragmatism: 0.2, safety: 0.16 },
    },
    {
      id: 'js-error-handling-rubric',
      topicId: 'javascript',
      archetype: 'reliability',
      mustHave: [
        'Explains async/await try-catch and promise rejection handling',
        'Shows error propagation through middleware or handlers',
        'Covers logging/monitoring for unhandled rejections',
      ],
      niceToHave: ['Mentions structured error objects or error boundaries'],
      redFlags: ['Ignores unhandled rejections', 'Swallows errors without logging'],
      scoringWeights: { clarity: 0.2, correctness: 0.24, depth: 0.2, pragmatism: 0.2, safety: 0.16 },
    },
    {
      id: 'js-modules-rubric',
      topicId: 'javascript',
      archetype: 'architecture',
      mustHave: [
        'Contrasts CommonJS and ESM loading and scope',
        'Identifies and resolves circular dependency risks',
        'Explains tree-shaking / bundling impact of module format',
      ],
      niceToHave: ['Mentions dynamic import() and code splitting'],
      redFlags: ['Mixes require/import without considering evaluation order'],
      scoringWeights: { clarity: 0.2, correctness: 0.24, depth: 0.2, pragmatism: 0.2, safety: 0.16 },
    },
    {
      id: 'javascript.let-var-const-rubric',
      topicId: 'javascript',
      archetype: 'runtime',
      mustHave: [
        'var is function-scoped and hoisted with undefined; let/const are block-scoped and in temporal dead zone until declaration',
        'const prevents reassignment but does not make objects immutable',
        'let and const cannot be redeclared in the same scope; var can',
      ],
      niceToHave: ['Mentions global object behavior differences for var vs let/const', 'Notes that const requires initialization at declaration time'],
      redFlags: ['Claims const makes nested object properties immutable', 'Says let behaves like var except for syntax'],
      scoringWeights: { clarity: 0.22, correctness: 0.28, depth: 0.18, pragmatism: 0.16, safety: 0.16 },
    },
    {
      id: 'javascript.null-undefined-rubric',
      topicId: 'javascript',
      archetype: 'runtime',
      mustHave: [
        'undefined means a variable is declared but not assigned a value',
        'null is an explicit assignment meaning intentional absence of value',
        "typeof null returns 'object' — a known JavaScript bug, not a feature",
      ],
      niceToHave: ['Explains that referencing an undeclared variable throws a ReferenceError', 'Shows safe checks such as x === null, x === undefined, or typeof x === "undefined"'],
      redFlags: ['Claims null and undefined are the same state', 'Says typeof null returns null'],
      scoringWeights: { clarity: 0.22, correctness: 0.28, depth: 0.18, pragmatism: 0.16, safety: 0.16 },
    },
    {
      id: 'javascript.equality-rubric',
      topicId: 'javascript',
      archetype: 'runtime',
      mustHave: [
        '== performs type coercion before comparison; === does not',
        '0 == false is true; 0 === false is false',
        'Use === by default to avoid unexpected coercion bugs',
      ],
      niceToHave: ['Explains that loose equality follows specific coercion rules rather than random behavior', 'Mentions rare intentional uses of == such as checking null and undefined together'],
      redFlags: ['Claims == and === are interchangeable for primitives', 'Says === still coerces values before comparison'],
      scoringWeights: { clarity: 0.22, correctness: 0.28, depth: 0.18, pragmatism: 0.16, safety: 0.16 },
    },
    {
      id: 'javascript.closures-deep-rubric',
      topicId: 'javascript',
      archetype: 'runtime',
      mustHave: [
        'A closure is a function that retains access to its lexical scope even after the outer function has returned',
        'Common use cases: data privacy, factory functions, partial application, module pattern',
        'Classic loop pitfall: var in a loop captures the same binding; fix with let or an IIFE',
      ],
      niceToHave: ['Connects closures to lexical environment rather than copying values', 'Mentions that closures can accidentally retain memory if references are kept too long'],
      redFlags: ['Defines a closure as a function calling itself', 'Claims each var loop iteration gets a fresh binding automatically'],
      scoringWeights: { clarity: 0.2, correctness: 0.27, depth: 0.21, pragmatism: 0.16, safety: 0.16 },
    },
    {
      id: 'javascript.event-delegation-rubric',
      topicId: 'javascript',
      archetype: 'performance',
      mustHave: [
        'Attach a single listener to a parent; events bubble up from children to the parent',
        'Use event.target to identify which child triggered the event',
        'Non-bubbling events (focus, blur, mouseenter, mouseleave) cannot be delegated',
      ],
      niceToHave: ['Mentions filtering with matches() or closest() before acting on event.target', 'Explains delegation works well for dynamic child elements added after initial render'],
      redFlags: ['Claims delegation requires a listener on every child', 'Says focus and blur bubble like click events'],
      scoringWeights: { clarity: 0.2, correctness: 0.26, depth: 0.2, pragmatism: 0.18, safety: 0.16 },
    },
    {
      id: 'javascript.debounce-throttle-rubric',
      topicId: 'javascript',
      archetype: 'performance',
      mustHave: [
        'Debounce delays execution until a specified time has passed since the last call — good for search input, resize handlers',
        'Throttle limits execution to once per time window regardless of call frequency — good for scroll handlers, API rate limits',
        'Both prevent excessive function calls from high-frequency events',
      ],
      niceToHave: ['Mentions leading vs trailing edge behavior as an implementation detail', 'Explains the UX tradeoff between responsiveness and request volume'],
      redFlags: ['Says debounce and throttle are identical patterns', 'Uses debounce for a continuous scroll update without discussing lost intermediate events'],
      scoringWeights: { clarity: 0.2, correctness: 0.26, depth: 0.2, pragmatism: 0.18, safety: 0.16 },
    },
  ],
  questionFamilies: [
    {
      key: 'javascript.event_loop',
      topicId: 'javascript',
      archetype: 'runtime',
      difficulty: 'medium',
      stem: 'Explain and apply the event loop ordering.',
      framing: 'Timers vs microtasks vs rendering frames.',
      primaryConcepts: ['js-event-loop', 'js-promises'],
      defaultConstraints: ['js-latency'],
      defaultRubricId: 'javascript.event_loop-rubric',
      phrasingSkeleton: 'Walk through event loop ordering in a concrete bug.',
    },
    {
      key: 'javascript.closures',
      topicId: 'javascript',
      archetype: 'reliability',
      difficulty: 'medium',
      stem: 'Fix a leak caused by closures.',
      framing: 'Identify retaining paths and cleanup strategy.',
      primaryConcepts: ['js-closures', 'js-memory'],
      defaultConstraints: ['js-compat'],
      defaultRubricId: 'javascript.closures-rubric',
      phrasingSkeleton: 'Resolve a memory leak tied to closures or listeners.',
    },
    {
      key: 'javascript.scope_chain',
      topicId: 'javascript',
      archetype: 'runtime',
      difficulty: 'warm_up',
      stem: 'Trace JavaScript scope resolution.',
      framing: 'Nested functions shadowing and lookup rules.',
      primaryConcepts: ['js-closures', 'js-types'],
      defaultConstraints: ['js-compat'],
      defaultRubricId: 'javascript.scope_chain-rubric',
      phrasingSkeleton:
        'What is the JavaScript scope chain and how does it work? / How does JavaScript resolve variables across nested scopes? / Explain how lexical scope affects identifier lookup in JavaScript.',
    },
    {
      key: 'javascript.hoisting',
      topicId: 'javascript',
      archetype: 'runtime',
      difficulty: 'warm_up',
      stem: 'Diagnose hoisting issues.',
      framing: 'TDZ, var vs let/const, and functions.',
      primaryConcepts: ['js-types', 'js-closures'],
      defaultConstraints: ['js-compat'],
      defaultRubricId: 'javascript.hoisting-rubric',
      phrasingSkeleton:
        'What is hoisting in JavaScript and how does it affect var declarations? / How does JavaScript hoist function declarations vs variables? / What is the difference between hoisting for var, let, and const?',
    },
    {
      key: 'javascript.promises_async',
      topicId: 'javascript',
      archetype: 'runtime',
      difficulty: 'medium',
      stem: 'Repair async sequencing and error handling.',
      framing: 'Promise chains, async/await, cancellation.',
      primaryConcepts: ['js-promises', 'js-event-loop'],
      defaultConstraints: ['js-compat'],
      defaultRubricId: 'javascript.promises_async-rubric',
      phrasingSkeleton: 'Sequence async work without starving rendering.',
    },
    {
      key: 'javascript.prototype_chain',
      topicId: 'javascript',
      archetype: 'architecture',
      difficulty: 'warm_up',
      stem: 'Diagnose prototype chain issues.',
      framing: 'Inheritance lookup and object creation.',
      primaryConcepts: ['js-prototype'],
      defaultConstraints: ['js-compat'],
      defaultRubricId: 'javascript.prototype_chain-rubric',
      phrasingSkeleton:
        'What is the prototype chain in JavaScript and how does it work? / How does JavaScript look up a property through the prototype chain? / Explain the difference between an object’s own properties and inherited properties in JavaScript.',
    },
    {
      key: 'javascript.this_binding',
      topicId: 'javascript',
      archetype: 'runtime',
      difficulty: 'warm_up',
      stem: 'Fix a this-binding bug.',
      framing: 'call/apply/bind, arrow functions, and context loss.',
      primaryConcepts: ['js-this-binding'],
      defaultConstraints: ['js-compat'],
      defaultRubricId: 'javascript.this_binding-rubric',
      phrasingSkeleton:
        'What does this refer to in a regular function vs an arrow function? / How does the value of this change depending on how a function is called? / What is explicit binding in JavaScript and how do call, apply, and bind differ?',
    },
    {
      key: 'javascript.memory_leaks',
      topicId: 'javascript',
      archetype: 'reliability',
      difficulty: 'medium',
      stem: 'Locate and prevent memory leaks.',
      framing: 'Detached DOM, listeners, and retained closures.',
      primaryConcepts: ['js-memory', 'js-closures'],
      defaultConstraints: ['js-compat'],
      defaultRubricId: 'javascript.memory_leaks-rubric',
      phrasingSkeleton: 'Show leak sources and cleanup strategy.',
    },
    {
      key: 'js-error-handling',
      topicId: 'javascript',
      archetype: 'reliability',
      difficulty: 'medium',
      stem: 'Handle errors in async JavaScript safely.',
      framing: 'try/catch with async/await, unhandled promise rejections, middleware chains.',
      primaryConcepts: ['js-promises', 'js-event-loop'],
      defaultConstraints: ['js-latency'],
      defaultRubricId: 'js-error-handling-rubric',
      phrasingSkeleton: 'Show how errors flow through async/await and promises; prevent unhandled rejections. / How do you design error propagation and logging in a Node/SPA stack?'
    },
    {
      key: 'js-modules',
      topicId: 'javascript',
      archetype: 'architecture',
      difficulty: 'medium',
      stem: 'Choose and migrate module systems safely.',
      framing: 'CommonJS vs ESM, circular deps, dynamic import, tree shaking.',
      primaryConcepts: ['js-modules'],
      defaultConstraints: ['js-compat'],
      defaultRubricId: 'js-modules-rubric',
      phrasingSkeleton: 'Compare CJS and ESM loading, then plan a migration avoiding circular deps. / How would you refactor a mixed CJS/ESM codebase to support tree-shaking?'
    },
    {
      key: 'javascript.let-var-const',
      topicId: 'javascript',
      archetype: 'runtime',
      difficulty: 'warm_up',
      stem: 'Explain JavaScript variable declarations clearly.',
      framing: 'Scope, hoisting, TDZ, and reassignment rules.',
      primaryConcepts: ['js-types'],
      supportingConcepts: ['js-closures'],
      defaultConstraints: ['js-compat'],
      defaultRubricId: 'javascript.let-var-const-rubric',
      phrasingSkeleton:
        'What are the differences between JavaScript variables created using let, var, or const? / When would you use const vs let in JavaScript? / What is the difference between block scope and function scope in JavaScript?',
    },
    {
      key: 'javascript.null-undefined',
      topicId: 'javascript',
      archetype: 'runtime',
      difficulty: 'warm_up',
      stem: 'Differentiate null, undefined, and undeclared values.',
      framing: 'Declared state, intentional emptiness, and safe checks.',
      primaryConcepts: ['js-types'],
      supportingConcepts: ['js-observability'],
      defaultConstraints: ['js-compat'],
      defaultRubricId: 'javascript.null-undefined-rubric',
      phrasingSkeleton:
        "What's the difference between a variable that is null, undefined, or undeclared? / How would you check for null, undefined, and undeclared states in JavaScript? / What does typeof return for null, and why?",
    },
    {
      key: 'javascript.equality',
      topicId: 'javascript',
      archetype: 'runtime',
      difficulty: 'warm_up',
      stem: 'Explain JavaScript equality and coercion.',
      framing: 'Loose equality, strict equality, and surprising coercions.',
      primaryConcepts: ['js-types'],
      supportingConcepts: ['js-observability'],
      defaultConstraints: ['js-compat'],
      defaultRubricId: 'javascript.equality-rubric',
      phrasingSkeleton:
        'What is the difference between == and === in JavaScript? / What is type coercion in JavaScript and when does it happen? / Why is === preferred over == in most JavaScript code?',
    },
    {
      key: 'javascript.closures-deep',
      topicId: 'javascript',
      archetype: 'runtime',
      difficulty: 'medium',
      stem: 'Explain closures deeply and apply them to real code.',
      framing: 'Lexical scope retention, private state, and loop pitfalls.',
      primaryConcepts: ['js-closures'],
      supportingConcepts: ['js-memory', 'js-types'],
      defaultConstraints: ['js-compat'],
      defaultRubricId: 'javascript.closures-deep-rubric',
      phrasingSkeleton:
        'A teammate wants to hide internal state inside a helper without exposing mutable globals. How would you explain closures and use them for data privacy? / You are reviewing a factory-function pattern that depends on closures for configuration. Explain why it works and what tradeoffs it introduces. / A loop creates callbacks and they all log the same value later. Explain the closure bug and how you would fix it.',
    },
    {
      key: 'javascript.event-delegation',
      topicId: 'javascript',
      archetype: 'performance',
      difficulty: 'medium',
      stem: 'Apply event delegation to simplify UI event handling.',
      framing: 'Bubbling, target inspection, and listener count reduction.',
      primaryConcepts: ['js-dom-performance'],
      supportingConcepts: ['js-observability'],
      defaultConstraints: ['js-latency'],
      defaultRubricId: 'javascript.event-delegation-rubric',
      phrasingSkeleton:
        'A dynamic list has many clickable child elements and keeps growing after render. How would you use event delegation instead of individual listeners? / A large form has dozens of child controls with repetitive event handlers. Explain how delegation works, why it is more efficient, and how event.target is used. / When reviewing delegated handlers on a parent element, how would you explain which DOM events can and cannot be delegated?',
    },
    {
      key: 'javascript.debounce-throttle',
      topicId: 'javascript',
      archetype: 'performance',
      difficulty: 'medium',
      stem: 'Choose between debounce and throttle for noisy events.',
      framing: 'High-frequency events, timing control, and UX tradeoffs.',
      primaryConcepts: ['js-dom-performance'],
      supportingConcepts: ['js-promises', 'js-observability'],
      defaultConstraints: ['js-latency'],
      defaultRubricId: 'javascript.debounce-throttle-rubric',
      phrasingSkeleton:
        'A search input is causing excessive API calls on every keystroke. Would you use debounce or throttle, and why? / A scroll handler performs expensive work many times per second. How would you explain the difference between debounce and throttle for this case? / In a UI with high-frequency resize and scroll events, when would you choose debounce vs throttle and what problem do both patterns solve?',
    },
  ],
  learningResources: [
    { title: 'MDN Event Loop', url: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Event_loop' },
    { title: 'Jake Archibald: In The Loop', url: 'https://www.youtube.com/watch?v=cCOL7MC4Pl0' },
    { title: 'JavaScript Memory Management', url: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Memory_Management' },
  ],
};

export default javascriptPack;
