import { TopicPack } from '../topic-pack.types';

export const javascriptPack: TopicPack = {
  topicId: 'javascript',
  label: 'JavaScript',
  description: 'Language foundations, runtime behavior, and practical patterns.',
  archetypes: ['runtime', 'performance', 'architecture', 'reliability'],
  concepts: [
    { id: 'js-closures', topicId: 'javascript', title: 'Closures & Scope', summary: 'Lexical scope, closure creation, and memory implications.', stage: 'foundation' },
    { id: 'js-prototype', topicId: 'javascript', title: 'Prototype Chain', summary: 'Prototype lookup, inheritance, and Object.create semantics.', stage: 'foundation' },
    { id: 'js-this-binding', topicId: 'javascript', title: '`this` Binding', summary: 'Call/apply/bind, arrow function behavior, and implicit binding.', stage: 'foundation' },
    { id: 'js-event-loop', topicId: 'javascript', title: 'Event Loop', summary: 'Task vs microtask queues, rendering frames, and ordering.', stage: 'foundation' },
    { id: 'js-promises', topicId: 'javascript', title: 'Promises & Async/Await', summary: 'Promise states, chaining, error propagation, and cancellation patterns.', stage: 'foundation' },
    { id: 'js-memory', topicId: 'javascript', title: 'Memory & GC', summary: 'Mark-and-sweep basics, leaks via closures or DOM references.', stage: 'intermediate' },
    { id: 'js-iterators', topicId: 'javascript', title: 'Iterators & Generators', summary: 'Custom iterables, lazy sequences, and async iterators.', stage: 'intermediate' },
    { id: 'js-modules', topicId: 'javascript', title: 'Modules', summary: 'ESM vs CJS semantics, import/export timing, tree-shaking basics.', stage: 'intermediate' },
    { id: 'js-types', topicId: 'javascript', title: 'Type Coercion', summary: '== vs ===, truthiness, and structural typing basics.', stage: 'foundation' },
    { id: 'js-dom-performance', topicId: 'javascript', title: 'DOM & Rendering Performance', summary: 'Layout thrash, debounce/throttle, and event delegation.', stage: 'intermediate' },
    { id: 'js-observability', topicId: 'javascript', title: 'Observability', summary: 'Console tracing, performance marks, and error boundaries.', stage: 'foundation' },
  ],
  scenarioHooks: [
    {
      id: 'js-memory-leak',
      topicId: 'javascript',
      title: 'Memory leak in SPA',
      backdrop: 'Long-running SPA slows down.',
      trigger: 'Heap grows after navigation.',
      compatibleFamilies: ['javascript.closures', 'javascript.memory_leaks'],
      relatedConcepts: ['js-memory', 'js-closures'],
    },
    {
      id: 'js-async-bug',
      topicId: 'javascript',
      title: 'Async ordering bug',
      backdrop: 'Animations stutter during async work.',
      trigger: 'Microtasks starve rendering.',
      compatibleFamilies: ['javascript.event_loop', 'javascript.promises_async', 'js-error-handling'],
      relatedConcepts: ['js-event-loop', 'js-promises'],
    },
    {
      id: 'js-nplusone-fetch',
      topicId: 'javascript',
      title: 'N+1 fetch in UI',
      backdrop: 'List view triggers many fetches.',
      trigger: 'Network waterfall hurts TTI.',
      compatibleFamilies: ['javascript.promises_async', 'javascript.event_loop', 'js-error-handling'],
      relatedConcepts: ['js-promises', 'js-event-loop'],
    },
    {
      id: 'js-module-conflict',
      topicId: 'javascript',
      title: 'Module type mismatch',
      backdrop: 'Bundler errors when mixing CJS and ESM.',
      trigger: 'Dynamic import path fails.',
      compatibleFamilies: ['js-modules'],
      relatedConcepts: ['js-modules'],
    },
    {
      id: 'js-debounce',
      topicId: 'javascript',
      title: 'Expensive input handler',
      backdrop: 'Search input floods network.',
      trigger: 'Need debounce/memoization.',
      compatibleFamilies: ['javascript.promises_async', 'javascript.event_loop'],
      relatedConcepts: ['js-dom-performance', 'js-promises'],
    },
    {
      id: 'js-prod-leak',
      topicId: 'javascript',
      title: 'Production memory leak',
      backdrop: 'Node service runs for days then restarts.',
      trigger: 'Heap grows with each cron batch.',
      compatibleFamilies: ['javascript.closures', 'javascript.memory_leaks'],
      relatedConcepts: ['js-memory', 'js-closures'],
    },
    {
      id: 'js-pr-async-bug',
      topicId: 'javascript',
      title: 'Async bug in PR review',
      backdrop: 'Reviewer spots inconsistent loading states.',
      trigger: 'Promise chain mixes await and then()',
      compatibleFamilies: ['javascript.promises_async', 'javascript.event_loop', 'js-error-handling'],
      relatedConcepts: ['js-promises', 'js-event-loop'],
    },
    {
      id: 'js-esm-migration',
      topicId: 'javascript',
      title: 'CommonJS to ESM migration',
      backdrop: 'Repo standardizes on ESM.',
      trigger: 'Circular dependency breaks after refactor.',
      compatibleFamilies: ['js-modules'],
      relatedConcepts: ['js-modules'],
    },
  ],
  constraintTemplates: [
    { id: 'js-bundle-size', topicId: 'javascript', label: 'Bundle size', text: 'Keep bundle increase under 50KB', tags: ['performance'] },
    { id: 'js-compat', topicId: 'javascript', label: 'Compatibility', text: 'Must work on evergreen browsers + Node 18+', tags: ['compatibility'] },
    { id: 'js-latency', topicId: 'javascript', label: 'Responsiveness', text: 'UI thread must not block more than 16ms per frame', tags: ['latency'] },
  ],
  rubricTemplates: [
    {
      id: 'js-runtime-rubric',
      topicId: 'javascript',
      archetype: 'runtime',
      mustHave: ['Explains event loop ordering', 'Handles async errors', 'Considers memory impact'],
      niceToHave: ['Mentions profiling tooling'],
      redFlags: ['Blocking UI thread', 'Ignoring promise rejection'],
      scoringWeights: { clarity: 0.2, correctness: 0.26, depth: 0.2, pragmatism: 0.18, safety: 0.16 },
    },
    {
      id: 'js-architecture-rubric',
      topicId: 'javascript',
      archetype: 'architecture',
      mustHave: ['Chooses appropriate abstractions', 'Avoids over-fetching', 'Considers module boundaries'],
      niceToHave: ['Progressive enhancement mention'],
      redFlags: ['Global mutable state without isolation'],
      scoringWeights: { clarity: 0.2, correctness: 0.24, depth: 0.2, pragmatism: 0.2, safety: 0.16 },
    },
    {
      id: 'js-error-handling-rubric',
      topicId: 'javascript',
      archetype: 'reliability',
      mustHave: [
        'Explains async/await try-catch and promise rejection handling',
        'Shows error propagation through middleware or handlers',
        'Covers logging/monitoring for unhandled rejections',
      ],
      niceToHave: ['Mentions structured error objects or error boundaries'],
      redFlags: ['Ignores unhandled rejections', 'Swallows errors without logging'],
      scoringWeights: { clarity: 0.2, correctness: 0.24, depth: 0.2, pragmatism: 0.2, safety: 0.16 },
    },
    {
      id: 'js-modules-rubric',
      topicId: 'javascript',
      archetype: 'architecture',
      mustHave: [
        'Contrasts CommonJS and ESM loading and scope',
        'Identifies and resolves circular dependency risks',
        'Explains tree-shaking / bundling impact of module format',
      ],
      niceToHave: ['Mentions dynamic import() and code splitting'],
      redFlags: ['Mixes require/import without considering evaluation order'],
      scoringWeights: { clarity: 0.2, correctness: 0.24, depth: 0.2, pragmatism: 0.2, safety: 0.16 },
    },
  ],
  questionFamilies: [
    {
      key: 'javascript.event_loop',
      topicId: 'javascript',
      archetype: 'runtime',
      difficulty: 'medium',
      stem: 'Explain and apply the event loop ordering.',
      framing: 'Timers vs microtasks vs rendering frames.',
      primaryConcepts: ['js-event-loop', 'js-promises'],
      defaultConstraints: ['js-latency'],
      defaultRubricId: 'js-runtime-rubric',
      phrasingSkeleton: 'Walk through event loop ordering in a concrete bug.',
    },
    {
      key: 'javascript.closures',
      topicId: 'javascript',
      archetype: 'reliability',
      difficulty: 'medium',
      stem: 'Fix a leak caused by closures.',
      framing: 'Identify retaining paths and cleanup strategy.',
      primaryConcepts: ['js-closures', 'js-memory'],
      defaultConstraints: ['js-compat'],
      defaultRubricId: 'js-runtime-rubric',
      phrasingSkeleton: 'Resolve a memory leak tied to closures or listeners.',
    },
    {
      key: 'javascript.scope_chain',
      topicId: 'javascript',
      archetype: 'runtime',
      difficulty: 'warm_up',
      stem: 'Trace JavaScript scope resolution.',
      framing: 'Nested functions shadowing and lookup rules.',
      primaryConcepts: ['js-closures', 'js-types'],
      defaultConstraints: ['js-compat'],
      defaultRubricId: 'js-runtime-rubric',
      phrasingSkeleton: 'Explain how identifiers resolve across scopes.',
    },
    {
      key: 'javascript.hoisting',
      topicId: 'javascript',
      archetype: 'runtime',
      difficulty: 'warm_up',
      stem: 'Diagnose hoisting issues.',
      framing: 'TDZ, var vs let/const, and functions.',
      primaryConcepts: ['js-types', 'js-closures'],
      defaultConstraints: ['js-compat'],
      defaultRubricId: 'js-runtime-rubric',
      phrasingSkeleton: 'Show why a value is undefined or throws before init.',
    },
    {
      key: 'javascript.promises_async',
      topicId: 'javascript',
      archetype: 'runtime',
      difficulty: 'medium',
      stem: 'Repair async sequencing and error handling.',
      framing: 'Promise chains, async/await, cancellation.',
      primaryConcepts: ['js-promises', 'js-event-loop'],
      defaultConstraints: ['js-compat'],
      defaultRubricId: 'js-runtime-rubric',
      phrasingSkeleton: 'Sequence async work without starving rendering.',
    },
    {
      key: 'javascript.prototype_chain',
      topicId: 'javascript',
      archetype: 'architecture',
      difficulty: 'warm_up',
      stem: 'Diagnose prototype chain issues.',
      framing: 'Inheritance lookup and object creation.',
      primaryConcepts: ['js-prototype'],
      defaultConstraints: ['js-compat'],
      defaultRubricId: 'js-architecture-rubric',
      phrasingSkeleton: 'Trace property resolution across prototypes.',
    },
    {
      key: 'javascript.this_binding',
      topicId: 'javascript',
      archetype: 'runtime',
      difficulty: 'warm_up',
      stem: 'Fix a this-binding bug.',
      framing: 'call/apply/bind, arrow functions, and context loss.',
      primaryConcepts: ['js-this-binding'],
      defaultConstraints: ['js-compat'],
      defaultRubricId: 'js-runtime-rubric',
      phrasingSkeleton: 'Explain how this is determined and fixed.',
    },
    {
      key: 'javascript.memory_leaks',
      topicId: 'javascript',
      archetype: 'reliability',
      difficulty: 'medium',
      stem: 'Locate and prevent memory leaks.',
      framing: 'Detached DOM, listeners, and retained closures.',
      primaryConcepts: ['js-memory', 'js-closures'],
      defaultConstraints: ['js-compat'],
      defaultRubricId: 'js-runtime-rubric',
      phrasingSkeleton: 'Show leak sources and cleanup strategy.',
    },
    {
      key: 'js-error-handling',
      topicId: 'javascript',
      archetype: 'reliability',
      difficulty: 'medium',
      stem: 'Handle errors in async JavaScript safely.',
      framing: 'try/catch with async/await, unhandled promise rejections, middleware chains.',
      primaryConcepts: ['js-promises', 'js-event-loop'],
      defaultConstraints: ['js-latency'],
      defaultRubricId: 'js-error-handling-rubric',
      phrasingSkeleton: 'Show how errors flow through async/await and promises; prevent unhandled rejections. / How do you design error propagation and logging in a Node/SPA stack?'
    },
    {
      key: 'js-modules',
      topicId: 'javascript',
      archetype: 'architecture',
      difficulty: 'medium',
      stem: 'Choose and migrate module systems safely.',
      framing: 'CommonJS vs ESM, circular deps, dynamic import, tree shaking.',
      primaryConcepts: ['js-modules'],
      defaultConstraints: ['js-compat'],
      defaultRubricId: 'js-modules-rubric',
      phrasingSkeleton: 'Compare CJS and ESM loading, then plan a migration avoiding circular deps. / How would you refactor a mixed CJS/ESM codebase to support tree-shaking?'
    },
  ],
  learningResources: [
    { title: 'MDN Event Loop', url: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Event_loop' },
    { title: 'Jake Archibald: In The Loop', url: 'https://www.youtube.com/watch?v=cCOL7MC4Pl0' },
    { title: 'JavaScript Memory Management', url: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Memory_Management' },
  ],
};

export default javascriptPack;
