import { TopicPack } from '../topic-pack.types';

export const nodeJsPack: TopicPack = {
  topicId: 'nodejs',
  label: 'Node.js',
  description: 'Runtime internals, reliability, and performance patterns for Node.js services.',
  archetypes: ['runtime', 'performance', 'reliability', 'architecture'],
  concepts: [
    { id: 'node-event-loop', topicId: 'nodejs', title: 'Event Loop Phases', summary: 'Timers, I/O callbacks, check, close, and microtask queues.', stage: 'foundation' },
    { id: 'node-streams', topicId: 'nodejs', title: 'Streams & Backpressure', summary: 'Flowing vs paused, highWaterMark, pipeline(), and buffering.', stage: 'foundation' },
    { id: 'node-module-resolution', topicId: 'nodejs', title: 'Module Resolution', summary: 'CJS vs ESM, package exports, and conditional exports.', stage: 'foundation' },
    { id: 'node-error-handling', topicId: 'nodejs', title: 'Error Handling', summary: 'Operational vs programmer errors, domains vs async_hooks, and process guards.', stage: 'foundation' },
    { id: 'node-worker-threads', topicId: 'nodejs', title: 'Workers & Clustering', summary: 'Thread pools, message passing, and clustering impact on state.', stage: 'intermediate' },
    { id: 'node-performance', topicId: 'nodejs', title: 'Profiling & Hot Paths', summary: 'CPU profiling, flamegraphs, perf_hooks, and bottleneck hunting.', stage: 'intermediate' },
    { id: 'node-memory', topicId: 'nodejs', title: 'Memory Management', summary: 'Heap limits, leaks, and GC tuning basics.', stage: 'intermediate' },
    { id: 'node-http', topicId: 'nodejs', title: 'HTTP Server Patterns', summary: 'Keep-alive, connection limits, and timeouts.', stage: 'foundation' },
    { id: 'node-security', topicId: 'nodejs', title: 'Security Hygiene', summary: 'Dependency scanning, SSRF/XXE guards, and sandboxing untrusted input.', stage: 'intermediate' },
    { id: 'node-observability', topicId: 'nodejs', title: 'Observability', summary: 'Async context propagation, tracing, structured logs, and health checks.', stage: 'foundation' },
    { id: 'node-build-deploy', topicId: 'nodejs', title: 'Build & Deploy', summary: 'Packaging, native deps, and zero-downtime rollout.', stage: 'advanced' },
  ],
  scenarioHooks: [
    {
      id: 'node-hot-path',
      topicId: 'nodejs',
      title: 'CPU spike during traffic',
      backdrop: 'Latency climbs during traffic spike.',
      trigger: 'Profiling needed to find synchronous hot path.',
      compatibleFamilies: ['node-performance-family'],
      relatedConcepts: ['node-performance', 'node-event-loop'],
    },
    {
      id: 'node-stream-backpressure',
      topicId: 'nodejs',
      title: 'Streaming upload stalls',
      backdrop: 'Uploads pause unpredictably.',
      trigger: 'Backpressure not handled between services.',
      compatibleFamilies: ['node-streaming-family'],
      relatedConcepts: ['node-streams'],
    },
    {
      id: 'node-esm-cjs',
      topicId: 'nodejs',
      title: 'ESM/CJS interop bug',
      backdrop: 'Package.json type changed to module.',
      trigger: 'Interop errors across codebase.',
      compatibleFamilies: ['node-interop-family'],
      relatedConcepts: ['node-module-resolution'],
    },
    {
      id: 'node-event-loop-explainer-a',
      topicId: 'nodejs',
      title: 'Explaining async to a teammate',
      backdrop: 'You are onboarding a new developer to a Node.js service.',
      trigger: 'They ask how one server process can keep moving between multiple async tasks.',
      compatibleFamilies: ['node-event-loop-family'],
      relatedConcepts: ['node-event-loop'],
    },
    {
      id: 'node-event-loop-phase-walkthrough',
      topicId: 'nodejs',
      title: 'Walking through callback order',
      backdrop: 'You are working on a Node.js project with a small async demo script.',
      trigger: 'A teammate asks you to explain why timers, promises, and I/O callbacks do not run in the same order.',
      compatibleFamilies: ['node-event-loop-family'],
      relatedConcepts: ['node-event-loop'],
    },
    {
      id: 'node-event-loop-request-flow',
      topicId: 'nodejs',
      title: 'Request flow explanation',
      backdrop: 'You are helping a teammate understand how a Node.js API handles incoming requests.',
      trigger: 'They want a simple explanation of what the event loop is doing while async work is pending.',
      compatibleFamilies: ['node-event-loop-family'],
      relatedConcepts: ['node-event-loop', 'node-http'],
    },
    {
      id: 'node-package-json-basics',
      topicId: 'nodejs',
      title: 'Project setup walkthrough',
      backdrop: 'You are working on a small Node.js service and a teammate asks what the project manifest controls.',
      trigger: 'They want to understand package.json fields, scripts, and dependency declarations before making changes.',
      compatibleFamilies: ['node-package-json-family'],
      relatedConcepts: ['node-module-resolution', 'node-build-deploy'],
    },
    {
      id: 'node-package-json-scripts-tour',
      topicId: 'nodejs',
      title: 'Explaining project scripts',
      backdrop: 'You are working on a Node.js app and reviewing the project files with a teammate.',
      trigger: 'They ask what the scripts and dependency sections in package.json are used for.',
      compatibleFamilies: ['node-package-json-family'],
      relatedConcepts: ['node-module-resolution', 'node-build-deploy'],
    },
    {
      id: 'node-package-json-field-overview-a',
      topicId: 'nodejs',
      title: 'Manifest field overview',
      backdrop: 'You are starting a new Node.js project with another developer.',
      trigger: 'They ask which package.json fields matter first when setting up the app.',
      compatibleFamilies: ['node-package-json-family'],
      relatedConcepts: ['node-module-resolution', 'node-build-deploy'],
    },
    {
      id: 'node-buffer-basics',
      topicId: 'nodejs',
      title: 'Binary data in a feature',
      backdrop: 'You are adding a file upload and image-processing step to a Node.js project.',
      trigger: 'The team wants a simple explanation of why Buffer exists and when it is used instead of plain strings.',
      compatibleFamilies: ['node-buffer-family'],
      relatedConcepts: ['node-streams', 'node-memory'],
    },
    {
      id: 'node-buffer-file-upload-help',
      topicId: 'nodejs',
      title: 'File upload bytes walkthrough',
      backdrop: 'You are building a simple upload feature in a Node.js project.',
      trigger: 'A teammate asks why the file data shows up as a Buffer instead of a regular string.',
      compatibleFamilies: ['node-buffer-family'],
      relatedConcepts: ['node-streams', 'node-memory'],
    },
    {
      id: 'node-buffer-encoding-explainer-b',
      topicId: 'nodejs',
      title: 'Encoding and binary basics',
      backdrop: 'You are working on a Node.js utility that reads files and network data.',
      trigger: 'You need to explain when Buffer is useful for binary data and how it relates to text encodings.',
      compatibleFamilies: ['node-buffer-family'],
      relatedConcepts: ['node-streams', 'node-memory'],
    },
    {
      id: 'node-interop-import-migration-a',
      topicId: 'nodejs',
      title: 'Module syntax migration question',
      backdrop: 'You are updating a Node.js project where some files use import and others use require.',
      trigger: 'A teammate asks how CommonJS and ES modules differ before they change more files.',
      compatibleFamilies: ['node-interop-family'],
      relatedConcepts: ['node-module-resolution'],
    },
    {
      id: 'node-interop-exports-overview-b',
      topicId: 'nodejs',
      title: 'Explaining module loading basics',
      backdrop: 'You are pairing on a Node.js library with a teammate.',
      trigger: 'They ask how Node.js decides what code gets loaded when a package is imported.',
      compatibleFamilies: ['node-interop-family'],
      relatedConcepts: ['node-module-resolution'],
    },
    {
      id: 'node-memory-leak',
      topicId: 'nodejs',
      title: 'Memory leak after release',
      backdrop: 'Heap keeps growing on workers.',
      trigger: 'Out-of-memory kills pods.',
      compatibleFamilies: ['node-performance-family'],
      relatedConcepts: ['node-memory', 'node-event-loop'],
    },
    {
      id: 'node-sigterm',
      topicId: 'nodejs',
      title: 'Graceful shutdown',
      backdrop: 'Service receives SIGTERM during deploy.',
      trigger: 'In-flight requests dropped.',
      compatibleFamilies: ['node-shutdown-family'],
      relatedConcepts: ['node-http', 'node-error-handling'],
    },
    {
      id: 'node-worker-pool-saturation',
      topicId: 'nodejs',
      title: 'Worker pool saturation',
      backdrop: 'An image-processing service offloads CPU work to worker threads, but throughput flattens as traffic rises.',
      trigger: 'Request latency spikes because workers queue behind oversized jobs and serialization overhead.',
      compatibleFamilies: ['node-worker-threads-family', 'node-performance-family'],
      relatedConcepts: ['node-worker-threads', 'node-performance'],
    },
    {
      id: 'node-trace-context-loss',
      topicId: 'nodejs',
      title: 'Lost async trace context',
      backdrop: 'Incident timelines show logs from one request stitched into another after a library upgrade.',
      trigger: 'AsyncLocalStorage context disappears across background callbacks and queue handoffs.',
      compatibleFamilies: ['node-async-context-family'],
      relatedConcepts: ['node-observability', 'node-event-loop'],
    },
    {
      id: 'node-keepalive-exhaustion',
      topicId: 'nodejs',
      title: 'Keep-alive socket exhaustion',
      backdrop: 'A gateway keeps thousands of client connections open while upstream services occasionally stall.',
      trigger: 'Sockets accumulate until new requests time out and shutdown takes too long.',
      compatibleFamilies: ['node-http-timeouts-family', 'node-shutdown-family'],
      relatedConcepts: ['node-http', 'node-error-handling'],
    },
    {
      id: 'node-error-first-callback-basics',
      topicId: 'nodejs',
      title: 'Explaining callback signatures',
      backdrop: 'You are working on a Node.js project with a teammate who is reading older async code.',
      trigger: 'They ask why many callbacks start with an err parameter before the result.',
      compatibleFamilies: ['node-error-first-callback-family'],
      relatedConcepts: ['node-error-handling'],
    },
    {
      id: 'node-error-first-callback-review',
      topicId: 'nodejs',
      title: 'Reviewing async callback code',
      backdrop: 'You are helping a teammate understand a small Node.js utility that uses callbacks.',
      trigger: 'They ask what the first callback argument means and how to handle it correctly.',
      compatibleFamilies: ['node-error-first-callback-family'],
      relatedConcepts: ['node-error-handling'],
    },
    {
      id: 'node-event-emitter-teammate',
      topicId: 'nodejs',
      title: 'Teaching event listeners',
      backdrop: 'You are working on a Node.js project that uses custom events between modules.',
      trigger: 'A teammate asks how listeners get registered and triggered.',
      compatibleFamilies: ['node-event-emitter-family'],
      relatedConcepts: ['node-observability', 'node-event-loop'],
    },
    {
      id: 'node-event-emitter-custom-events',
      topicId: 'nodejs',
      title: 'Creating custom events',
      backdrop: 'You are pairing with a teammate on a Node.js feature that emits internal events.',
      trigger: 'They ask how to create a custom event and clean up listeners afterward.',
      compatibleFamilies: ['node-event-emitter-family'],
      relatedConcepts: ['node-observability', 'node-event-loop'],
    },
    {
      id: 'node-child-process-overview',
      topicId: 'nodejs',
      title: 'Choosing a child process API',
      backdrop: 'You are working on a Node.js tool that needs to run another program.',
      trigger: 'A teammate asks when to use spawn, exec, or fork.',
      compatibleFamilies: ['node-child-process-family'],
      relatedConcepts: ['node-performance', 'node-build-deploy'],
    },
    {
      id: 'node-child-process-explainer',
      topicId: 'nodejs',
      title: 'Explaining external process support',
      backdrop: 'You are helping a teammate add a small command-line integration to a Node.js project.',
      trigger: 'They ask how Node.js can run external processes without blocking the main flow.',
      compatibleFamilies: ['node-child-process-family'],
      relatedConcepts: ['node-performance', 'node-build-deploy'],
    },
    {
      id: 'node-callback-hell-refactor',
      topicId: 'nodejs',
      title: 'Refactoring nested callbacks',
      backdrop: 'You are reviewing a Node.js helper that chains several async steps together.',
      trigger: 'A teammate asks why the code is hard to read and what pattern would clean it up.',
      compatibleFamilies: ['node-callback-hell-family'],
      relatedConcepts: ['node-error-handling', 'node-event-loop'],
    },
    {
      id: 'node-callback-hell-teaching',
      topicId: 'nodejs',
      title: 'Teaching async control flow',
      backdrop: 'You are onboarding a developer who is new to older Node.js callback code.',
      trigger: 'They ask what callback hell means and what usually replaces it.',
      compatibleFamilies: ['node-callback-hell-family'],
      relatedConcepts: ['node-error-handling', 'node-event-loop'],
    },
    {
      id: 'node-process-object-basics',
      topicId: 'nodejs',
      title: 'Reading process information',
      backdrop: 'You are working on a small Node.js script with a teammate.',
      trigger: 'They ask where command-line arguments and environment variables are available.',
      compatibleFamilies: ['node-process-object-family'],
      relatedConcepts: ['node-build-deploy', 'node-error-handling'],
    },
    {
      id: 'node-process-object-exit-codes',
      topicId: 'nodejs',
      title: 'Explaining process exit behavior',
      backdrop: 'You are reviewing a simple Node.js CLI project with another developer.',
      trigger: 'They ask what process.exit does and how exit codes are used.',
      compatibleFamilies: ['node-process-object-family'],
      relatedConcepts: ['node-build-deploy', 'node-error-handling'],
    },
    {
      id: 'node-libuv-thread-pool-basics',
      topicId: 'nodejs',
      title: 'Explaining libuv basics',
      backdrop: 'You are teaching a teammate how Node.js handles asynchronous work behind the scenes.',
      trigger: 'They ask what libuv does and why Node.js relies on it.',
      compatibleFamilies: ['node-libuv-family'],
      relatedConcepts: ['node-event-loop', 'node-performance'],
    },
    {
      id: 'node-libuv-io-overview',
      topicId: 'nodejs',
      title: 'Walking through async internals',
      backdrop: 'You are discussing Node.js internals with a teammate during a code walkthrough.',
      trigger: 'They ask which tasks use the libuv thread pool and how that differs from the event loop.',
      compatibleFamilies: ['node-libuv-family'],
      relatedConcepts: ['node-event-loop', 'node-performance'],
    },
  ],
  constraintTemplates: [
    { id: 'node-latency', topicId: 'nodejs', label: 'Latency', text: 'p99 API latency < 120ms', tags: ['latency'] },
    { id: 'node-memory-cap', topicId: 'nodejs', label: 'Memory', text: 'Stay within 512MB heap per worker', tags: ['performance'] },
    { id: 'node-compat', topicId: 'nodejs', label: 'Compatibility', text: 'Must run on Node 20 and remain ESM-safe', tags: ['compatibility'] },
    { id: 'node-safe-shutdown', topicId: 'nodejs', label: 'Delivery', text: 'Graceful shutdown within 20 seconds', tags: ['reliability'] },
  ],
  rubricTemplates: [
    {
      id: 'node-event-loop-rubric',
      topicId: 'nodejs',
      archetype: 'runtime',
      mustHave: [
        'Explains event loop phases (timers, poll, check)',
        'Identifies blocking vs non-blocking operations',
        'Explains microtask queue vs macrotask queue',
      ],
      niceToHave: ['Mentions async_hooks/tracing'],
      redFlags: ['Long sync loops', 'Ignoring promise rejections'],
      scoringWeights: { clarity: 0.2, correctness: 0.26, depth: 0.2, pragmatism: 0.18, safety: 0.16 },
    },
    {
      id: 'node-streaming-rubric',
      topicId: 'nodejs',
      archetype: 'performance',
      mustHave: [
        'Explains backpressure mechanism',
        'Uses pipe() or pipeline() correctly',
        'Handles stream errors without crashing',
      ],
      niceToHave: ['Mentions highWaterMark or buffering tradeoffs'],
      redFlags: ['Unbounded buffering', 'Ignoring stream error events'],
      scoringWeights: { clarity: 0.2, correctness: 0.24, depth: 0.22, pragmatism: 0.18, safety: 0.16 },
    },
    {
      id: 'node-interop-rubric',
      topicId: 'nodejs',
      archetype: 'architecture',
      mustHave: [
        'Distinguishes CommonJS require() from ESM import',
        'Explains package.json exports field',
        'Handles circular dependency risks',
      ],
      niceToHave: ['Mentions conditional exports or module type boundaries'],
      redFlags: ['Mixes CJS and ESM without a migration boundary'],
      scoringWeights: { clarity: 0.2, correctness: 0.26, depth: 0.2, pragmatism: 0.18, safety: 0.16 },
    },
    {
      id: 'node-shutdown-rubric',
      topicId: 'nodejs',
      archetype: 'reliability',
      mustHave: [
        'Graceful shutdown on SIGTERM',
        'Health check endpoint implementation',
        'Connection draining before shutdown',
      ],
      niceToHave: ['Circuit breakers or bulkheads'],
      redFlags: ['Process.exit used for control flow'],
      scoringWeights: { clarity: 0.2, correctness: 0.24, depth: 0.2, pragmatism: 0.2, safety: 0.16 },
    },
    {
      id: 'node-performance-rubric',
      topicId: 'nodejs',
      archetype: 'performance',
      mustHave: [
        'Identifies CPU-bound vs I/O-bound bottleneck',
        'Uses profiling tools (clinic.js, --prof)',
        'Avoids synchronous operations on hot path',
      ],
      niceToHave: ['Mentions worker_threads or perf_hooks where appropriate'],
      redFlags: ['Optimizes before profiling', 'Leaves sync work on request path'],
      scoringWeights: { clarity: 0.2, correctness: 0.26, depth: 0.22, pragmatism: 0.18, safety: 0.14 },
    },
    {
      id: 'node-worker-threads-family-rubric',
      topicId: 'nodejs',
      archetype: 'performance',
      mustHave: [
        'Distinguishes libuv thread pool work from worker_threads execution',
        'Explains message passing or Transferable/SharedArrayBuffer costs between threads',
        'Compares worker-per-request with bounded worker pool designs under CPU-bound load',
      ],
      niceToHave: ['Mentions resourceLimits or worker lifecycle cleanup'],
      redFlags: ['Assumes worker_threads share mutable JS objects without synchronization', 'Spawns unbounded workers on the request path'],
      scoringWeights: { clarity: 0.2, correctness: 0.25, depth: 0.21, pragmatism: 0.18, safety: 0.16 },
    },
    {
      id: 'node-memory-leak-family-rubric',
      topicId: 'nodejs',
      archetype: 'reliability',
      mustHave: [
        'Separates heap leak symptoms from external memory or buffer growth',
        'Uses heap snapshots or allocation profiling to isolate retaining references',
        'Explains how timers, caches, or event listeners can prevent garbage collection',
      ],
      niceToHave: ['Mentions clinic heapprof or --inspect snapshot comparisons'],
      redFlags: ['Treats restarting the process as the root-cause fix', 'Blames V8 GC without inspecting retainers'],
      scoringWeights: { clarity: 0.2, correctness: 0.24, depth: 0.22, pragmatism: 0.18, safety: 0.16 },
    },
    {
      id: 'node-async-context-family-rubric',
      topicId: 'nodejs',
      archetype: 'runtime',
      mustHave: [
        'Explains how AsyncLocalStorage propagates request context across async boundaries',
        'Identifies callback or event-emitter boundaries where context can be lost',
        'Describes how to attach correlation IDs to logs, traces, or downstream requests safely',
      ],
      niceToHave: ['Mentions context propagation tradeoffs in background jobs or worker threads'],
      redFlags: ['Uses global mutable request state shared across concurrent requests'],
      scoringWeights: { clarity: 0.2, correctness: 0.25, depth: 0.2, pragmatism: 0.19, safety: 0.16 },
    },
    {
      id: 'node-http-timeouts-family-rubric',
      topicId: 'nodejs',
      archetype: 'reliability',
      mustHave: [
        'Sets and differentiates requestTimeout, headersTimeout, and keepAliveTimeout behavior',
        'Explains connection draining for keep-alive sockets during deploys or incident response',
        'Describes aborting or timing out slow upstream calls to avoid socket exhaustion',
      ],
      niceToHave: ['Mentions Agent maxSockets or per-upstream connection budgeting'],
      redFlags: ['Leaves default infinite timeouts on internet-facing servers', 'Kills the process before draining active sockets'],
      scoringWeights: { clarity: 0.2, correctness: 0.24, depth: 0.2, pragmatism: 0.2, safety: 0.16 },
    },
    {
      id: 'node-package-json-family-rubric',
      topicId: 'nodejs',
      archetype: 'architecture',
      mustHave: [
        'Explains that package.json stores project metadata plus runtime or development dependency declarations',
        'Identifies common executable fields such as scripts, name/version, and dependency sections',
        'Describes how npm uses package.json during install, run-script execution, and package resolution',
      ],
      niceToHave: ['Mentions package-lock.json as a separate lockfile', 'Calls out fields like type, main, or exports at a basic level'],
      redFlags: ['Says package.json itself installs packages automatically', 'Confuses package.json with the node_modules directory'],
      scoringWeights: { clarity: 0.2, correctness: 0.25, depth: 0.19, pragmatism: 0.2, safety: 0.16 },
    },
    {
      id: 'node-buffer-family-rubric',
      topicId: 'nodejs',
      archetype: 'runtime',
      mustHave: [
        'Explains that Buffer represents raw binary data in Node.js',
        'Connects Buffer usage to files, network payloads, streams, or protocol data instead of plain text-only values',
        'Describes basic conversion or encoding behavior such as creating buffers from strings and reading them back safely',
      ],
      niceToHave: ['Mentions Buffer.alloc versus Buffer.from at a conceptual level', 'Notes that buffers have a fixed length once created'],
      redFlags: ['Claims Buffer is just a normal JavaScript string', 'Treats binary payload handling as identical to plain object serialization'],
      scoringWeights: { clarity: 0.2, correctness: 0.25, depth: 0.2, pragmatism: 0.19, safety: 0.16 },
    },
    {
      id: 'node-native-build-family-rubric',
      topicId: 'nodejs',
      archetype: 'architecture',
      mustHave: [
        'Explains ABI compatibility risk for native addons across Node versions and OS images',
        'Describes reproducible build strategy for optional native dependencies in CI and containers',
        'Covers rollback or fallback plan when prebuilt binaries are missing in production',
      ],
      niceToHave: ['Mentions Node-API stability or distroless image tradeoffs'],
      redFlags: ['Assumes native modules built on one base image always work everywhere'],
      scoringWeights: { clarity: 0.2, correctness: 0.25, depth: 0.21, pragmatism: 0.18, safety: 0.16 },
    },
    {
      id: 'node-error-first-callback-family-rubric',
      topicId: 'nodejs',
      archetype: 'fundamentals' as never,
      mustHave: [
        'First argument is always an error object (null if no error)',
        'Caller must check err before using data',
        'Pattern enables async error propagation without try/catch',
      ],
      niceToHave: ['Mentions the common callback shape as err, data', 'Notes this pattern appears heavily in older Node.js APIs'],
      redFlags: ['Says the first callback argument is the success value', 'Assumes try/catch alone handles asynchronous callback errors'],
      scoringWeights: { clarity: 0.21, correctness: 0.25, depth: 0.18, pragmatism: 0.18, safety: 0.18 },
    },
    {
      id: 'node-event-emitter-family-rubric',
      topicId: 'nodejs',
      archetype: 'fundamentals' as never,
      mustHave: [
        'EventEmitter.on() registers a listener for a named event',
        'EventEmitter.emit() triggers the event and calls listeners',
        'removeListener() or off() prevents memory leaks from uncleaned listeners',
      ],
      niceToHave: ['Mentions once() for one-time listeners', 'Explains that custom classes can extend EventEmitter'],
      redFlags: ['Claims emit() runs without any named event', 'Ignores listener cleanup when listeners are no longer needed'],
      scoringWeights: { clarity: 0.2, correctness: 0.25, depth: 0.19, pragmatism: 0.18, safety: 0.18 },
    },
    {
      id: 'node-child-process-family-rubric',
      topicId: 'nodejs',
      archetype: 'fundamentals' as never,
      mustHave: [
        'spawn streams output, exec buffers it — use spawn for large output',
        'fork is a special spawn for Node.js scripts that sets up IPC channel',
        'child processes enable CPU-heavy work off the main thread',
      ],
      niceToHave: ['Mentions execFile() as a variant without a shell', 'Notes shell usage tradeoffs and command-injection concerns'],
      redFlags: ['Says exec streams output by default for large output', 'Says fork is identical to worker_threads'],
      scoringWeights: { clarity: 0.2, correctness: 0.26, depth: 0.2, pragmatism: 0.18, safety: 0.16 },
    },
    {
      id: 'node-callback-hell-family-rubric',
      topicId: 'nodejs',
      archetype: 'fundamentals' as never,
      mustHave: [
        'Callback hell: deeply nested callbacks from chained async operations, hard to read and maintain',
        'Promises flatten the chain and enable .catch() error handling',
        'async/await makes async code read synchronously',
      ],
      niceToHave: ['Mentions extracting named functions to reduce nesting', 'Explains that promise chaining centralizes error handling'],
      redFlags: ['Claims callback hell only means too many callbacks anywhere in a file', 'Says async/await makes async work synchronous at runtime'],
      scoringWeights: { clarity: 0.21, correctness: 0.25, depth: 0.19, pragmatism: 0.18, safety: 0.17 },
    },
    {
      id: 'node-process-object-family-rubric',
      topicId: 'nodejs',
      archetype: 'fundamentals' as never,
      mustHave: [
        'process.env reads environment variables at runtime',
        'process.argv contains command-line arguments as an array',
        'process.exit(code) terminates the process; code 0 = success, non-zero = error',
      ],
      niceToHave: ['Mentions process.cwd() or process.pid as useful process metadata', 'Notes that environment variables are strings unless explicitly parsed'],
      redFlags: ['Claims process.argv is an object of flags by default', 'Says process.exit(0) signals an error condition'],
      scoringWeights: { clarity: 0.21, correctness: 0.25, depth: 0.18, pragmatism: 0.18, safety: 0.18 },
    },
    {
      id: 'node-libuv-family-rubric',
      topicId: 'nodejs',
      archetype: 'fundamentals' as never,
      mustHave: [
        'libuv is a C library that abstracts async I/O across platforms',
        'It provides the thread pool (default 4 threads) for file system and DNS operations',
        'The event loop itself runs on libuv — it is not part of V8',
      ],
      niceToHave: ['Mentions UV_THREADPOOL_SIZE can tune the pool for some workloads', 'Explains that not every async operation uses the thread pool directly'],
      redFlags: ['Claims libuv is part of V8', 'Says all async Node.js operations run inside the libuv thread pool'],
      scoringWeights: { clarity: 0.2, correctness: 0.26, depth: 0.2, pragmatism: 0.17, safety: 0.17 },
    },
  ],
  // Warm-up coverage is intentionally broader so short introductory sessions can fill natively.
  questionFamilies: [
    {
      key: 'node-event-loop-family',
      topicId: 'nodejs',
      archetype: 'runtime',
      difficulty: 'warm_up',
      stem: 'Debug event loop ordering in a failing request.',
      framing: 'Timers, microtasks, and I/O callbacks under load.',
      primaryConcepts: ['node-event-loop', 'node-http'],
      defaultConstraints: ['node-latency'],
      defaultRubricId: 'node-event-loop-family-rubric',
      phrasingSkeleton:
        'What is the Node.js event loop and how does it process callbacks? / How does the event loop allow Node.js to handle async operations on a single thread? / Explain the phases of the Node.js event loop.',
    },
    {
      key: 'node-package-json-family',
      topicId: 'nodejs',
      archetype: 'architecture',
      difficulty: 'warm_up',
      stem: 'Explain the purpose of package.json in a Node.js project.',
      framing: 'Project metadata, scripts, and dependency declarations at a beginner-friendly level.',
      primaryConcepts: ['node-module-resolution', 'node-build-deploy'],
      defaultConstraints: ['node-compat'],
      defaultRubricId: 'node-package-json-family-rubric',
      phrasingSkeleton:
        'What is package.json in a Node.js project? / How does package.json work in Node.js? / Explain what package.json is used for in Node.js.',
    },
    {
      key: 'node-buffer-family',
      topicId: 'nodejs',
      archetype: 'runtime',
      difficulty: 'warm_up',
      stem: 'Explain what a Buffer is in Node.js.',
      framing: 'Binary data basics for files, streams, and network I/O.',
      primaryConcepts: ['node-streams', 'node-memory'],
      defaultConstraints: ['node-memory-cap'],
      defaultRubricId: 'node-buffer-family-rubric',
      phrasingSkeleton:
        'What is a Buffer in Node.js? / How does a Buffer work in Node.js? / Explain what a Buffer is used for in Node.js.',
    },
    {
      key: 'node-streaming-family',
      topicId: 'nodejs',
      archetype: 'performance',
      difficulty: 'medium',
      stem: 'Fix a streaming pipeline with backpressure.',
      framing: 'Pipeline(), buffering, and error boundaries.',
      primaryConcepts: ['node-streams', 'node-error-handling'],
      defaultConstraints: ['node-latency'],
      defaultRubricId: 'node-streaming-family-rubric',
      phrasingSkeleton: 'Handle backpressure in a Node.js streaming flow.',
    },
    {
      key: 'node-interop-family',
      topicId: 'nodejs',
      archetype: 'architecture',
      difficulty: 'warm_up',
      stem: 'Resolve ESM/CJS interoperability issues.',
      framing: 'Packaging, loaders, and migration path.',
      primaryConcepts: ['node-module-resolution'],
      defaultConstraints: ['node-compat'],
      defaultRubricId: 'node-interop-family-rubric',
      phrasingSkeleton:
        'What does the require() function do in Node.js? / What is the difference between CommonJS and ES modules in Node.js? / Explain how Node.js resolves and loads modules.',
    },
    {
      key: 'node-shutdown-family',
      topicId: 'nodejs',
      archetype: 'reliability',
      difficulty: 'medium',
      stem: 'Implement graceful shutdown.',
      framing: 'SIGTERM handling, in-flight requests, and draining.',
      primaryConcepts: ['node-http', 'node-error-handling'],
      defaultConstraints: ['node-safe-shutdown'],
      defaultRubricId: 'node-shutdown-family-rubric',
      phrasingSkeleton: 'Shut down a Node.js server without dropping requests.',
    },
    {
      key: 'node-performance-family',
      topicId: 'nodejs',
      archetype: 'performance',
      difficulty: 'hard',
      stem: 'Profile and fix a hot path.',
      framing: 'Collect CPU profile, find sync blockers, propose fix.',
      primaryConcepts: ['node-performance', 'node-event-loop'],
      supportingConcepts: ['node-worker-threads'],
      defaultConstraints: ['node-memory-cap'],
      defaultRubricId: 'node-performance-family-rubric',
      phrasingSkeleton: 'Profile Node.js CPU spikes and remove the blocker.',
    },
    {
      key: 'node-worker-threads-family',
      topicId: 'nodejs',
      archetype: 'performance',
      difficulty: 'hard',
      stem: 'Offload CPU-heavy work without collapsing throughput.',
      framing: 'Worker thread pools, serialization cost, and protecting the request path.',
      primaryConcepts: ['node-worker-threads', 'node-performance'],
      supportingConcepts: ['node-memory'],
      defaultConstraints: ['node-latency', 'node-memory-cap'],
      defaultRubricId: 'node-worker-threads-family-rubric',
      phrasingSkeleton: 'When would you use worker_threads for CPU-bound work in Node.js, and how would you size the pool and control handoff overhead?',
    },
    {
      key: 'node-memory-leak-family',
      topicId: 'nodejs',
      archetype: 'reliability',
      difficulty: 'hard',
      stem: 'Find a memory leak before pods keep getting OOM-killed.',
      framing: 'Heap snapshots, retainer paths, and distinguishing heap growth from buffer pressure.',
      primaryConcepts: ['node-memory', 'node-performance'],
      supportingConcepts: ['node-error-handling'],
      defaultConstraints: ['node-memory-cap'],
      defaultRubricId: 'node-memory-leak-family-rubric',
      phrasingSkeleton: 'A Node.js service grows from 300MB to 1.5GB heap over a day; how would you isolate the leak and prove the fix worked?',
    },
    {
      key: 'node-async-context-family',
      topicId: 'nodejs',
      archetype: 'runtime',
      difficulty: 'medium',
      stem: 'Preserve request context across asynchronous boundaries.',
      framing: 'AsyncLocalStorage, tracing correlation, and background callback pitfalls.',
      primaryConcepts: ['node-observability', 'node-event-loop'],
      supportingConcepts: ['node-error-handling'],
      defaultConstraints: ['node-latency'],
      defaultRubricId: 'node-async-context-family-rubric',
      phrasingSkeleton: 'How would you keep a correlation ID attached to logs and downstream calls across promises, event emitters, and background tasks in Node.js?',
    },
    {
      key: 'node-http-timeouts-family',
      topicId: 'nodejs',
      archetype: 'reliability',
      difficulty: 'medium',
      stem: 'Tune HTTP timeouts and keep-alive behavior safely.',
      framing: 'Slow clients, upstream hangs, and graceful draining during deploys.',
      primaryConcepts: ['node-http', 'node-error-handling'],
      supportingConcepts: ['node-observability'],
      defaultConstraints: ['node-safe-shutdown'],
      defaultRubricId: 'node-http-timeouts-family-rubric',
      phrasingSkeleton: 'A Node.js API starts timing out because keep-alive connections pile up during upstream slowness; what timeout and draining strategy would you use?',
    },
    {
      key: 'node-native-build-family',
      topicId: 'nodejs',
      archetype: 'architecture',
      difficulty: 'hard',
      stem: 'Ship native dependencies without fragile builds.',
      framing: 'Node-API compatibility, container images, and fallback paths for missing binaries.',
      primaryConcepts: ['node-build-deploy', 'node-module-resolution'],
      supportingConcepts: ['node-security'],
      defaultConstraints: ['node-compat'],
      defaultRubricId: 'node-native-build-family-rubric',
      phrasingSkeleton: 'How would you package and deploy a Node.js service that depends on native addons so releases stay reproducible across environments?',
    },
    {
      key: 'node-error-first-callback-family',
      topicId: 'nodejs',
      archetype: 'fundamentals' as never,
      difficulty: 'warm_up',
      stem: 'Explain the error-first callback pattern in Node.js.',
      framing: 'Basic async callback conventions in Node.js.',
      primaryConcepts: ['node-error-handling', 'node-event-loop'],
      supportingConcepts: ['node-http'],
      defaultRubricId: 'node-error-first-callback-family-rubric',
      phrasingSkeleton:
        'What is an error-first callback? / Why does Node.js use error-first callbacks? / What is the convention for the first argument in a Node.js callback?',
    },
    {
      key: 'node-event-emitter-family',
      topicId: 'nodejs',
      archetype: 'fundamentals' as never,
      difficulty: 'warm_up',
      stem: 'Explain EventEmitter and event listeners in Node.js.',
      framing: 'Core event-driven patterns in Node.js modules.',
      primaryConcepts: ['node-observability', 'node-event-loop'],
      supportingConcepts: ['node-error-handling'],
      defaultRubricId: 'node-event-emitter-family-rubric',
      phrasingSkeleton:
        'What are Event Listeners? / How does EventEmitter work in Node.js? / How do you create a custom event in Node.js?',
    },
    {
      key: 'node-child-process-family',
      topicId: 'nodejs',
      archetype: 'fundamentals' as never,
      difficulty: 'warm_up',
      stem: 'Explain child_process basics in Node.js.',
      framing: 'Running external programs and Node.js child scripts.',
      primaryConcepts: ['node-performance', 'node-build-deploy'],
      supportingConcepts: ['node-worker-threads', 'node-event-loop'],
      defaultRubricId: 'node-child-process-family-rubric',
      phrasingSkeleton:
        'Could we run an external process with Node.js? / What is the difference between spawn and exec? / When would you use fork vs spawn?',
    },
    {
      key: 'node-callback-hell-family',
      topicId: 'nodejs',
      archetype: 'fundamentals' as never,
      difficulty: 'warm_up',
      stem: 'Explain callback hell and modern alternatives.',
      framing: 'Nested async flow, readability, and error handling basics.',
      primaryConcepts: ['node-error-handling', 'node-event-loop'],
      supportingConcepts: ['node-observability'],
      defaultRubricId: 'node-callback-hell-family-rubric',
      phrasingSkeleton:
        'What is Callback Hell? / How do you avoid callback hell in Node.js? / What patterns replace nested callbacks?',
    },
    {
      key: 'node-process-object-family',
      topicId: 'nodejs',
      archetype: 'fundamentals' as never,
      difficulty: 'warm_up',
      stem: 'Explain the process global object in Node.js.',
      framing: 'Runtime metadata, environment variables, and exit behavior.',
      primaryConcepts: ['node-build-deploy', 'node-error-handling'],
      supportingConcepts: ['node-http'],
      defaultRubricId: 'node-process-object-family-rubric',
      phrasingSkeleton:
        'What is the process object in Node.js? / How do you read environment variables in Node.js? / What does process.exit() do?',
    },
    {
      key: 'node-libuv-family',
      topicId: 'nodejs',
      archetype: 'fundamentals' as never,
      difficulty: 'warm_up',
      stem: 'Explain what libuv does in Node.js.',
      framing: 'Event loop internals and background I/O support.',
      primaryConcepts: ['node-event-loop', 'node-performance'],
      supportingConcepts: ['node-worker-threads', 'node-http'],
      defaultRubricId: 'node-libuv-family-rubric',
      phrasingSkeleton:
        'What is libuv? / Why does Node.js use libuv? / What operations use the libuv thread pool?',
    },
  ],
  learningResources: [
    { title: 'Node.js Event Loop Guide', url: 'https://nodejs.org/en/learn/asynchronous-work/event-loop-timers-and-nexttick' },
    { title: 'Node.js Streams', url: 'https://nodejs.org/api/stream.html' },
    { title: 'Diagnosing Memory Leaks', note: 'Internal runbook placeholder' },
  ],
};

export default nodeJsPack;
