import { TopicPack } from '../topic-pack.types';

export const nodeJsPack: TopicPack = {
  topicId: 'nodejs',
  label: 'Node.js',
  description: 'Runtime internals, reliability, and performance patterns for Node.js services.',
  archetypes: ['runtime', 'performance', 'reliability', 'architecture'],
  concepts: [
    { id: 'node-event-loop', topicId: 'nodejs', title: 'Event Loop Phases', summary: 'Timers, I/O callbacks, check, close, and microtask queues.', stage: 'foundation' },
    { id: 'node-streams', topicId: 'nodejs', title: 'Streams & Backpressure', summary: 'Flowing vs paused, highWaterMark, pipeline(), and buffering.', stage: 'foundation' },
    { id: 'node-module-resolution', topicId: 'nodejs', title: 'Module Resolution', summary: 'CJS vs ESM, package exports, and conditional exports.', stage: 'foundation' },
    { id: 'node-error-handling', topicId: 'nodejs', title: 'Error Handling', summary: 'Operational vs programmer errors, domains vs async_hooks, and process guards.', stage: 'foundation' },
    { id: 'node-worker-threads', topicId: 'nodejs', title: 'Workers & Clustering', summary: 'Thread pools, message passing, and clustering impact on state.', stage: 'intermediate' },
    { id: 'node-performance', topicId: 'nodejs', title: 'Profiling & Hot Paths', summary: 'CPU profiling, flamegraphs, perf_hooks, and bottleneck hunting.', stage: 'intermediate' },
    { id: 'node-memory', topicId: 'nodejs', title: 'Memory Management', summary: 'Heap limits, leaks, and GC tuning basics.', stage: 'intermediate' },
    { id: 'node-http', topicId: 'nodejs', title: 'HTTP Server Patterns', summary: 'Keep-alive, connection limits, and timeouts.', stage: 'foundation' },
    { id: 'node-security', topicId: 'nodejs', title: 'Security Hygiene', summary: 'Dependency scanning, SSRF/XXE guards, and sandboxing untrusted input.', stage: 'intermediate' },
    { id: 'node-observability', topicId: 'nodejs', title: 'Observability', summary: 'Async context propagation, tracing, structured logs, and health checks.', stage: 'foundation' },
    { id: 'node-build-deploy', topicId: 'nodejs', title: 'Build & Deploy', summary: 'Packaging, native deps, and zero-downtime rollout.', stage: 'advanced' },
  ],
  scenarioHooks: [
    {
      id: 'node-hot-path',
      topicId: 'nodejs',
      title: 'CPU spike during traffic',
      backdrop: 'Latency climbs during traffic spike.',
      trigger: 'Profiling needed to find synchronous hot path.',
      compatibleFamilies: ['node-performance-family', 'node-event-loop-family'],
      relatedConcepts: ['node-performance', 'node-event-loop'],
    },
    {
      id: 'node-stream-backpressure',
      topicId: 'nodejs',
      title: 'Streaming upload stalls',
      backdrop: 'Uploads pause unpredictably.',
      trigger: 'Backpressure not handled between services.',
      compatibleFamilies: ['node-streaming-family'],
      relatedConcepts: ['node-streams'],
    },
    {
      id: 'node-esm-cjs',
      topicId: 'nodejs',
      title: 'ESM/CJS interop bug',
      backdrop: 'Package.json type changed to module.',
      trigger: 'Interop errors across codebase.',
      compatibleFamilies: ['node-interop-family'],
      relatedConcepts: ['node-module-resolution'],
    },
    {
      id: 'node-memory-leak',
      topicId: 'nodejs',
      title: 'Memory leak after release',
      backdrop: 'Heap keeps growing on workers.',
      trigger: 'Out-of-memory kills pods.',
      compatibleFamilies: ['node-performance-family', 'node-event-loop-family'],
      relatedConcepts: ['node-memory', 'node-event-loop'],
    },
    {
      id: 'node-sigterm',
      topicId: 'nodejs',
      title: 'Graceful shutdown',
      backdrop: 'Service receives SIGTERM during deploy.',
      trigger: 'In-flight requests dropped.',
      compatibleFamilies: ['node-shutdown-family'],
      relatedConcepts: ['node-http', 'node-error-handling'],
    },
  ],
  constraintTemplates: [
    { id: 'node-latency', topicId: 'nodejs', label: 'Latency', text: 'p99 API latency < 120ms', tags: ['latency'] },
    { id: 'node-memory-cap', topicId: 'nodejs', label: 'Memory', text: 'Stay within 512MB heap per worker', tags: ['performance'] },
    { id: 'node-compat', topicId: 'nodejs', label: 'Compatibility', text: 'Must run on Node 20 and remain ESM-safe', tags: ['compatibility'] },
    { id: 'node-safe-shutdown', topicId: 'nodejs', label: 'Delivery', text: 'Graceful shutdown within 20 seconds', tags: ['reliability'] },
  ],
  rubricTemplates: [
    {
      id: 'node-event-loop-rubric',
      topicId: 'nodejs',
      archetype: 'runtime',
      mustHave: [
        'Explains event loop phases (timers, poll, check)',
        'Identifies blocking vs non-blocking operations',
        'Explains microtask queue vs macrotask queue',
      ],
      niceToHave: ['Mentions async_hooks/tracing'],
      redFlags: ['Long sync loops', 'Ignoring promise rejections'],
      scoringWeights: { clarity: 0.2, correctness: 0.26, depth: 0.2, pragmatism: 0.18, safety: 0.16 },
    },
    {
      id: 'node-streaming-rubric',
      topicId: 'nodejs',
      archetype: 'performance',
      mustHave: [
        'Explains backpressure mechanism',
        'Uses pipe() or pipeline() correctly',
        'Handles stream errors without crashing',
      ],
      niceToHave: ['Mentions highWaterMark or buffering tradeoffs'],
      redFlags: ['Unbounded buffering', 'Ignoring stream error events'],
      scoringWeights: { clarity: 0.2, correctness: 0.24, depth: 0.22, pragmatism: 0.18, safety: 0.16 },
    },
    {
      id: 'node-interop-rubric',
      topicId: 'nodejs',
      archetype: 'architecture',
      mustHave: [
        'Distinguishes CommonJS require() from ESM import',
        'Explains package.json exports field',
        'Handles circular dependency risks',
      ],
      niceToHave: ['Mentions conditional exports or module type boundaries'],
      redFlags: ['Mixes CJS and ESM without a migration boundary'],
      scoringWeights: { clarity: 0.2, correctness: 0.26, depth: 0.2, pragmatism: 0.18, safety: 0.16 },
    },
    {
      id: 'node-shutdown-rubric',
      topicId: 'nodejs',
      archetype: 'reliability',
      mustHave: [
        'Graceful shutdown on SIGTERM',
        'Health check endpoint implementation',
        'Connection draining before shutdown',
      ],
      niceToHave: ['Circuit breakers or bulkheads'],
      redFlags: ['Process.exit used for control flow'],
      scoringWeights: { clarity: 0.2, correctness: 0.24, depth: 0.2, pragmatism: 0.2, safety: 0.16 },
    },
    {
      id: 'node-performance-rubric',
      topicId: 'nodejs',
      archetype: 'performance',
      mustHave: [
        'Identifies CPU-bound vs I/O-bound bottleneck',
        'Uses profiling tools (clinic.js, --prof)',
        'Avoids synchronous operations on hot path',
      ],
      niceToHave: ['Mentions worker_threads or perf_hooks where appropriate'],
      redFlags: ['Optimizes before profiling', 'Leaves sync work on request path'],
      scoringWeights: { clarity: 0.2, correctness: 0.26, depth: 0.22, pragmatism: 0.18, safety: 0.14 },
    },
  ],
  // minimum 2 warm_up families required for 5-question sessions
  questionFamilies: [
    {
      key: 'node-event-loop-family',
      topicId: 'nodejs',
      archetype: 'runtime',
      difficulty: 'warm_up',
      stem: 'Debug event loop ordering in a failing request.',
      framing: 'Timers, microtasks, and I/O callbacks under load.',
      primaryConcepts: ['node-event-loop', 'node-http'],
      defaultConstraints: ['node-latency'],
      defaultRubricId: 'node-event-loop-rubric',
      phrasingSkeleton: 'Trace the Node.js event loop for a request under load.',
    },
    {
      key: 'node-streaming-family',
      topicId: 'nodejs',
      archetype: 'performance',
      difficulty: 'medium',
      stem: 'Fix a streaming pipeline with backpressure.',
      framing: 'Pipeline(), buffering, and error boundaries.',
      primaryConcepts: ['node-streams', 'node-error-handling'],
      defaultConstraints: ['node-latency'],
      defaultRubricId: 'node-streaming-rubric',
      phrasingSkeleton: 'Handle backpressure in a Node.js streaming flow.',
    },
    {
      key: 'node-interop-family',
      topicId: 'nodejs',
      archetype: 'architecture',
      difficulty: 'warm_up',
      stem: 'Resolve ESM/CJS interoperability issues.',
      framing: 'Packaging, loaders, and migration path.',
      primaryConcepts: ['node-module-resolution'],
      defaultConstraints: ['node-compat'],
      defaultRubricId: 'node-interop-rubric',
      phrasingSkeleton: 'Fix module resolution problems after moving to ESM.',
    },
    {
      key: 'node-shutdown-family',
      topicId: 'nodejs',
      archetype: 'reliability',
      difficulty: 'medium',
      stem: 'Implement graceful shutdown.',
      framing: 'SIGTERM handling, in-flight requests, and draining.',
      primaryConcepts: ['node-http', 'node-error-handling'],
      defaultConstraints: ['node-safe-shutdown'],
      defaultRubricId: 'node-shutdown-rubric',
      phrasingSkeleton: 'Shut down a Node.js server without dropping requests.',
    },
    {
      key: 'node-performance-family',
      topicId: 'nodejs',
      archetype: 'performance',
      difficulty: 'hard',
      stem: 'Profile and fix a hot path.',
      framing: 'Collect CPU profile, find sync blockers, propose fix.',
      primaryConcepts: ['node-performance', 'node-event-loop'],
      supportingConcepts: ['node-worker-threads'],
      defaultConstraints: ['node-memory-cap'],
      defaultRubricId: 'node-performance-rubric',
      phrasingSkeleton: 'Profile Node.js CPU spikes and remove the blocker.',
    },
  ],
  learningResources: [
    { title: 'Node.js Event Loop Guide', url: 'https://nodejs.org/en/learn/asynchronous-work/event-loop-timers-and-nexttick' },
    { title: 'Node.js Streams', url: 'https://nodejs.org/api/stream.html' },
    { title: 'Diagnosing Memory Leaks', note: 'Internal runbook placeholder' },
  ],
};

export default nodeJsPack;
