import { TopicPack } from '../topic-pack.types';

export const queuesPack: TopicPack = {
  topicId: 'queues',
  label: 'Queues',
  description: 'Asynchronous processing, delivery semantics, and backpressure controls.',
  archetypes: ['reliability', 'performance', 'integration', 'architecture'],
  concepts: [
    {
      id: 'queue-delivery-semantics',
      topicId: 'queues',
      title: 'Delivery Semantics',
      summary: 'At-least-once, at-most-once, exactly-once with idempotency/ordering tradeoffs.',
      stage: 'foundation',
    },
    {
      id: 'queue-backpressure',
      topicId: 'queues',
      title: 'Backpressure & Flow Control',
      summary: 'Consumer lag, rate limits, and visibility timeouts.',
      stage: 'foundation',
    },
    {
      id: 'queue-scaling',
      topicId: 'queues',
      title: 'Scaling Consumers',
      summary: 'Shard-aware consumers, batching, and concurrency knobs.',
      stage: 'intermediate',
    },
    {
      id: 'queue-dlq',
      topicId: 'queues',
      title: 'Dead-letter Strategy',
      summary: 'Poison message handling, retry limits, and replay policies.',
      stage: 'foundation',
    },
    {
      id: 'queue-ordering',
      topicId: 'queues',
      title: 'Ordering Guarantees',
      summary: 'Partition keys, sequence tokens, and reordering tactics.',
      stage: 'intermediate',
    },
    {
      id: 'queue-replay',
      topicId: 'queues',
      title: 'Replay & Reprocessing',
      summary: 'Event versioning, compaction, and re-run safety.',
      stage: 'advanced',
    },
    {
      id: 'queue-observability',
      topicId: 'queues',
      title: 'Lag & Health Signals',
      summary: 'Lag metrics, age-of-oldest, DLQ trends, and saturation.',
      stage: 'foundation',
    },
    {
      id: 'queue-scheduling',
      topicId: 'queues',
      title: 'Scheduling & Priorities',
      summary: 'Priority queues, fairness, and starvation avoidance.',
      stage: 'advanced',
    },
    {
      id: 'queue-security',
      topicId: 'queues',
      title: 'Security & Isolation',
      summary: 'Tenant isolation, auth between producers/consumers, encryption in transit/at rest.',
      stage: 'intermediate',
    },
    {
      id: 'queue-schema',
      topicId: 'queues',
      title: 'Message Schema',
      summary: 'Versioning, compatibility modes, and payload sizing.',
      stage: 'intermediate',
    },
  ],
  scenarioHooks: [
    {
      id: 'queue-surge',
      topicId: 'queues',
      title: 'Job surge after marketing campaign',
      backdrop: 'Background jobs multiply during campaign.',
      trigger: 'Lag climbs; upstreams time out waiting for results.',
      relatedConcepts: ['queue-backpressure', 'queue-scaling'],
    },
    {
      id: 'queue-poison',
      topicId: 'queues',
      title: 'Poison message storm',
      backdrop: 'A malformed payload causes repeated retries.',
      trigger: 'DLQ volume grows; consumers churn CPU.',
      relatedConcepts: ['queue-dlq', 'queue-schema'],
    },
    {
      id: 'queue-order-break',
      topicId: 'queues',
      title: 'Ordering regression',
      backdrop: 'Refund events processed before charge events.',
      trigger: 'Partition keys were changed during refactor.',
      relatedConcepts: ['queue-ordering', 'queue-replay'],
    },
    {
      id: 'queue-priority',
      topicId: 'queues',
      title: 'Priority inversion',
      backdrop: 'Low priority jobs starve high priority fraud alerts.',
      trigger: 'Single queue with mixed priorities.',
      relatedConcepts: ['queue-scheduling', 'queue-scaling'],
    },
    {
      id: 'queue-multi-tenant',
      topicId: 'queues',
      title: 'Tenant isolation breach',
      backdrop: 'One tenant’s jobs delay others.',
      trigger: 'Shared queue without limits.',
      relatedConcepts: ['queue-security', 'queue-backpressure'],
    },
  ],
  constraintTemplates: [
    { id: 'queue-sla-2s', topicId: 'queues', label: 'SLA', text: '95% of jobs must finish within 2 seconds', tags: ['latency'] },
    { id: 'queue-retry-limits', topicId: 'queues', label: 'Retries', text: 'Max 3 retries then DLQ with alert', tags: ['reliability'] },
    { id: 'queue-cost', topicId: 'queues', label: 'Cost', text: 'Cannot add new shards this quarter', tags: ['cost'] },
    { id: 'queue-compliance', topicId: 'queues', label: 'Compliance', text: 'Message payloads must be encrypted at rest and in transit', tags: ['security'] },
  ],
  rubricTemplates: [
    {
      id: 'queue-reliability-rubric',
      topicId: 'queues',
      archetype: 'reliability',
      mustHave: ['Defines delivery semantics', 'Has DLQ/retry policy', 'Handles backpressure and lag'],
      niceToHave: ['Replay strategy'],
      redFlags: ['Unbounded retries', 'No isolation'],
      scoringWeights: { clarity: 0.2, correctness: 0.22, depth: 0.2, pragmatism: 0.2, safety: 0.18 },
    },
    {
      id: 'queue-performance-rubric',
      topicId: 'queues',
      archetype: 'performance',
      mustHave: ['Batching/concurrency tuning', 'Lag monitoring', 'Fair scheduling plan'],
      niceToHave: ['Autoscaling hook'],
      redFlags: ['Ignores consumer saturation'],
      scoringWeights: { clarity: 0.2, correctness: 0.22, depth: 0.2, pragmatism: 0.2, safety: 0.18 },
    },
  ],
  questionFamilies: [
    {
      key: 'queue-ingestion',
      topicId: 'queues',
      archetype: 'architecture',
      stem: 'Design an ingestion pipeline using queues.',
      framing: 'Producers, partitions, and failure isolation.',
      primaryConcepts: ['queue-delivery-semantics', 'queue-schema'],
      supportingConcepts: ['queue-security'],
      defaultConstraints: ['queue-compliance'],
      defaultRubricId: 'queue-reliability-rubric',
      phrasingSkeleton: 'Describe a queue-based ingestion path and durability story.',
    },
    {
      key: 'queue-backpressure-plan',
      topicId: 'queues',
      archetype: 'reliability',
      stem: 'Protect upstreams when consumers fall behind.',
      framing: 'Visibility timeouts, rate limits, and load shedding.',
      primaryConcepts: ['queue-backpressure', 'queue-dlq'],
      defaultConstraints: ['queue-retry-limits'],
      defaultRubricId: 'queue-reliability-rubric',
      phrasingSkeleton: 'Handle consumer lag with clear throttling and DLQ rules.',
    },
    {
      key: 'queue-scaling-plan',
      topicId: 'queues',
      archetype: 'performance',
      stem: 'Scale consumers for bursty traffic.',
      framing: 'Concurrency knobs, batching, autoscaling signals.',
      primaryConcepts: ['queue-scaling', 'queue-observability'],
      defaultConstraints: ['queue-cost'],
      defaultRubricId: 'queue-performance-rubric',
      phrasingSkeleton: 'Explain how you would scale consumers during bursts.',
    },
    {
      key: 'queue-ordering-plan',
      topicId: 'queues',
      archetype: 'architecture',
      stem: 'Guarantee ordering where it matters.',
      framing: 'Partition strategy and compensating actions for out-of-order events.',
      primaryConcepts: ['queue-ordering', 'queue-replay'],
      defaultConstraints: ['queue-sla-2s'],
      defaultRubricId: 'queue-reliability-rubric',
      phrasingSkeleton: 'Maintain ordering across partitions with recovery path.',
    },
    {
      key: 'queue-priority-handling',
      topicId: 'queues',
      archetype: 'integration',
      stem: 'Mix priorities without starving critical work.',
      framing: 'Routing, multiple queues, or priority scheduling.',
      primaryConcepts: ['queue-scheduling', 'queue-backpressure'],
      defaultConstraints: ['queue-sla-2s'],
      defaultRubricId: 'queue-performance-rubric',
      phrasingSkeleton: 'Handle multiple priorities in a queue-based system.',
    },
  ],
  learningResources: [
    { title: 'Kafka Patterns', url: 'https://kafka.apache.org/documentation/' },
    { title: 'SQS Developer Guide', url: 'https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/welcome.html' },
    { title: 'Event Delivery Semantics', note: 'Internal primer' },
  ],
};

export default queuesPack;
