import { TopicPack } from '../topic-pack.types';

export const queuesPack: TopicPack = {
  topicId: 'queues',
  label: 'Queues',
  description: 'Asynchronous processing, delivery semantics, and backpressure controls.',
  archetypes: ['reliability', 'performance', 'integration', 'architecture'],
  concepts: [
    {
      id: 'queue-delivery-semantics',
      topicId: 'queues',
      title: 'Delivery Semantics',
      summary: 'At-least-once, at-most-once, exactly-once with idempotency/ordering tradeoffs.',
      stage: 'foundation',
    },
    {
      id: 'queue-backpressure',
      topicId: 'queues',
      title: 'Backpressure & Flow Control',
      summary: 'Consumer lag, rate limits, and visibility timeouts.',
      stage: 'foundation',
    },
    {
      id: 'queue-scaling',
      topicId: 'queues',
      title: 'Scaling Consumers',
      summary: 'Shard-aware consumers, batching, and concurrency knobs.',
      stage: 'intermediate',
    },
    {
      id: 'queue-dlq',
      topicId: 'queues',
      title: 'Dead-letter Strategy',
      summary: 'Poison message handling, retry limits, and replay policies.',
      stage: 'foundation',
    },
    {
      id: 'queue-ordering',
      topicId: 'queues',
      title: 'Ordering Guarantees',
      summary: 'Partition keys, sequence tokens, and reordering tactics.',
      stage: 'intermediate',
    },
    {
      id: 'queue-replay',
      topicId: 'queues',
      title: 'Replay & Reprocessing',
      summary: 'Event versioning, compaction, and re-run safety.',
      stage: 'advanced',
    },
    {
      id: 'queue-observability',
      topicId: 'queues',
      title: 'Lag & Health Signals',
      summary: 'Lag metrics, age-of-oldest, DLQ trends, and saturation.',
      stage: 'foundation',
    },
    {
      id: 'queue-scheduling',
      topicId: 'queues',
      title: 'Scheduling & Priorities',
      summary: 'Priority queues, fairness, and starvation avoidance.',
      stage: 'advanced',
    },
    {
      id: 'queue-security',
      topicId: 'queues',
      title: 'Security & Isolation',
      summary: 'Tenant isolation, auth between producers/consumers, encryption in transit/at rest.',
      stage: 'intermediate',
    },
    {
      id: 'queue-schema',
      topicId: 'queues',
      title: 'Message Schema',
      summary: 'Versioning, compatibility modes, and payload sizing.',
      stage: 'intermediate',
    },
  ],
  scenarioHooks: [
    {
      id: 'queue-surge',
      topicId: 'queues',
      title: 'Job surge after marketing campaign',
      backdrop: 'Background jobs multiply during campaign.',
      trigger: 'Lag climbs; upstreams time out waiting for results.',
      compatibleFamilies: ['queue-backpressure-plan', 'queue-scaling-plan'],
      relatedConcepts: ['queue-backpressure', 'queue-scaling'],
    },
    {
      id: 'queue-poison',
      topicId: 'queues',
      title: 'Poison message storm',
      backdrop: 'A malformed payload causes repeated retries.',
      trigger: 'DLQ volume grows; consumers churn CPU.',
      compatibleFamilies: ['queue-backpressure-plan'],
      relatedConcepts: ['queue-dlq', 'queue-schema'],
    },
    {
      id: 'queue-order-break',
      topicId: 'queues',
      title: 'Ordering regression',
      backdrop: 'Refund events processed before charge events.',
      trigger: 'Partition keys were changed during refactor.',
      compatibleFamilies: ['queue-ordering-plan'],
      relatedConcepts: ['queue-ordering', 'queue-replay'],
    },
    {
      id: 'queue-priority',
      topicId: 'queues',
      title: 'Priority inversion',
      backdrop: 'Low priority jobs starve high priority fraud alerts.',
      trigger: 'Single queue with mixed priorities.',
      compatibleFamilies: ['queue-scaling-plan', 'queue-priority-handling'],
      relatedConcepts: ['queue-scheduling', 'queue-scaling'],
    },
    {
      id: 'queue-multi-tenant',
      topicId: 'queues',
      title: 'Tenant isolation breach',
      backdrop: 'One tenant’s jobs delay others.',
      trigger: 'Shared queue without limits.',
      compatibleFamilies: ['queue-ingestion', 'queue-backpressure-plan'],
      relatedConcepts: ['queue-security', 'queue-backpressure'],
    },
    {
      id: 'queue-replay-backlog',
      topicId: 'queues',
      title: 'Replay backlog grows',
      backdrop: 'A bad deploy corrupted downstream materialized views, so the team needs to replay three days of events.',
      trigger: 'Replay traffic competes with live consumption and threatens ordering plus latency SLAs.',
      compatibleFamilies: ['queue-dlq-replay-governance', 'queue-ordering-plan', 'queue-scaling-plan'],
      relatedConcepts: ['queue-replay', 'queue-ordering'],
    },
    {
      id: 'queue-schema-split',
      topicId: 'queues',
      title: 'Mixed schema consumers',
      backdrop: 'Producers start publishing a new payload version while older consumers are still deployed in half the fleet.',
      trigger: 'Deserialization failures rise and messages begin piling up in retry loops.',
      compatibleFamilies: ['queue-schema-evolution', 'queue-backpressure-plan'],
      relatedConcepts: ['queue-schema', 'queue-dlq'],
    },
    {
      id: 'queue-fairness-breach',
      topicId: 'queues',
      title: 'Fairness breach across tenants',
      backdrop: 'A premium tenant submits enormous batch jobs that monopolize shared workers.',
      trigger: 'Small tenants miss job deadlines even though overall consumer utilization looks healthy.',
      compatibleFamilies: ['queue-fairness-isolation', 'queue-priority-handling', 'queue-batch-processing'],
      relatedConcepts: ['queue-scheduling', 'queue-security'],
    },
  ],
  constraintTemplates: [
    { id: 'queue-sla-2s', topicId: 'queues', label: 'SLA', text: '95% of jobs must finish within 2 seconds', tags: ['latency'] },
    { id: 'queue-retry-limits', topicId: 'queues', label: 'Retries', text: 'Max 3 retries then DLQ with alert', tags: ['reliability'] },
    { id: 'queue-cost', topicId: 'queues', label: 'Cost', text: 'Cannot add new shards this quarter', tags: ['cost'] },
    { id: 'queue-compliance', topicId: 'queues', label: 'Compliance', text: 'Message payloads must be encrypted at rest and in transit', tags: ['security'] },
  ],
  rubricTemplates: [
    {
      id: 'queue-reliability-rubric',
      topicId: 'queues',
      archetype: 'reliability',
      mustHave: ['Defines delivery semantics', 'Has DLQ/retry policy', 'Handles backpressure and lag'],
      niceToHave: ['Replay strategy'],
      redFlags: ['Unbounded retries', 'No isolation'],
      scoringWeights: { clarity: 0.2, correctness: 0.22, depth: 0.2, pragmatism: 0.2, safety: 0.18 },
    },
    {
      id: 'queue-performance-rubric',
      topicId: 'queues',
      archetype: 'performance',
      mustHave: ['Batching/concurrency tuning', 'Lag monitoring', 'Fair scheduling plan'],
      niceToHave: ['Autoscaling hook'],
      redFlags: ['Ignores consumer saturation'],
      scoringWeights: { clarity: 0.2, correctness: 0.22, depth: 0.2, pragmatism: 0.2, safety: 0.18 },
    },
    {
      id: 'queue-idempotent-consumers-rubric',
      topicId: 'queues',
      archetype: 'reliability',
      mustHave: [
        'Defines the at-least-once duplicate scenario that the consumer must survive',
        'Implements deduplication with an idempotency key, processed offset table, or equivalent durable marker',
        'Explains side-effect ordering so downstream writes remain safe on retries',
      ],
      niceToHave: ['Mentions dedupe TTL or compaction strategy for processed markers'],
      redFlags: ['Assumes the broker alone guarantees exactly-once end-to-end behavior'],
      scoringWeights: { clarity: 0.2, correctness: 0.24, depth: 0.2, pragmatism: 0.19, safety: 0.17 },
    },
    {
      id: 'queue-dlq-replay-governance-rubric',
      topicId: 'queues',
      archetype: 'reliability',
      mustHave: [
        'Defines replay eligibility criteria instead of blindly reprocessing all dead-lettered messages',
        'Explains how replay rate is throttled to avoid starving live traffic or recreating the incident',
        'Covers poison-message quarantine or version fixes before messages re-enter the main flow',
      ],
      niceToHave: ['Mentions replay audit trail or operator approval workflow'],
      redFlags: ['Replays the DLQ directly into production consumers with no guardrails'],
      scoringWeights: { clarity: 0.2, correctness: 0.24, depth: 0.22, pragmatism: 0.18, safety: 0.16 },
    },
    {
      id: 'queue-schema-evolution-rubric',
      topicId: 'queues',
      archetype: 'integration',
      mustHave: [
        'Explains backward and forward compatibility expectations for message fields',
        'Uses schema versioning or registry validation to block incompatible producers',
        'Describes deployment sequencing so producers and consumers can coexist during rollout',
      ],
      niceToHave: ['Mentions default values or tolerant readers for optional fields'],
      redFlags: ['Changes required fields in place without a compatibility window'],
      scoringWeights: { clarity: 0.2, correctness: 0.25, depth: 0.2, pragmatism: 0.19, safety: 0.16 },
    },
    {
      id: 'queue-fairness-isolation-rubric',
      topicId: 'queues',
      archetype: 'architecture',
      mustHave: [
        'Explains how queue partitioning, quotas, or per-tenant concurrency limits preserve fairness',
        'Defines starvation signals such as age-of-oldest or tenant-level lag',
        'Balances isolation against cost and operational complexity of extra queues or consumers',
      ],
      niceToHave: ['Mentions weighted fair scheduling or burst credits for premium tiers'],
      redFlags: ['Uses one global queue with no tenant-level controls and calls it sufficient'],
      scoringWeights: { clarity: 0.2, correctness: 0.24, depth: 0.21, pragmatism: 0.19, safety: 0.16 },
    },
    {
      id: 'queue-batch-processing-rubric',
      topicId: 'queues',
      archetype: 'performance',
      mustHave: [
        'Chooses batch size based on processing cost, visibility timeout, and downstream limits',
        'Explains partial-batch failure handling so one bad record does not poison the entire batch indefinitely',
        'Measures the throughput benefit of batching against latency added to individual messages',
      ],
      niceToHave: ['Mentions adaptive batch sizing during low versus high traffic'],
      redFlags: ['Batches blindly until consumer memory pressure or timeout failures appear'],
      scoringWeights: { clarity: 0.2, correctness: 0.24, depth: 0.2, pragmatism: 0.2, safety: 0.16 },
    },
  ],
  questionFamilies: [
    {
      key: 'queue-ingestion',
      topicId: 'queues',
      archetype: 'architecture',
      difficulty: 'hard',
      stem: 'Design an ingestion pipeline using queues.',
      framing: 'Producers, partitions, and failure isolation.',
      primaryConcepts: ['queue-delivery-semantics', 'queue-schema'],
      supportingConcepts: ['queue-security'],
      defaultConstraints: ['queue-compliance'],
      defaultRubricId: 'queue-ingestion-rubric',
      phrasingSkeleton: 'Describe a queue-based ingestion path and durability story.',
    },
    {
      key: 'queue-backpressure-plan',
      topicId: 'queues',
      archetype: 'reliability',
      difficulty: 'medium',
      stem: 'Protect upstreams when consumers fall behind.',
      framing: 'Visibility timeouts, rate limits, and load shedding.',
      primaryConcepts: ['queue-backpressure', 'queue-dlq'],
      defaultConstraints: ['queue-retry-limits'],
      defaultRubricId: 'queue-backpressure-plan-rubric',
      phrasingSkeleton: 'Handle consumer lag with clear throttling and DLQ rules.',
    },
    {
      key: 'queue-scaling-plan',
      topicId: 'queues',
      archetype: 'performance',
      difficulty: 'medium',
      stem: 'Scale consumers for bursty traffic.',
      framing: 'Concurrency knobs, batching, autoscaling signals.',
      primaryConcepts: ['queue-scaling', 'queue-observability'],
      defaultConstraints: ['queue-cost'],
      defaultRubricId: 'queue-scaling-plan-rubric',
      phrasingSkeleton: 'Explain how you would scale consumers during bursts.',
    },
    {
      key: 'queue-ordering-plan',
      topicId: 'queues',
      archetype: 'architecture',
      difficulty: 'hard',
      stem: 'Guarantee ordering where it matters.',
      framing: 'Partition strategy and compensating actions for out-of-order events.',
      primaryConcepts: ['queue-ordering', 'queue-replay'],
      defaultConstraints: ['queue-sla-2s'],
      defaultRubricId: 'queue-ordering-plan-rubric',
      phrasingSkeleton: 'Maintain ordering across partitions with recovery path.',
    },
    {
      key: 'queue-priority-handling',
      topicId: 'queues',
      archetype: 'integration',
      difficulty: 'hard',
      stem: 'Mix priorities without starving critical work.',
      framing: 'Routing, multiple queues, or priority scheduling.',
      primaryConcepts: ['queue-scheduling', 'queue-backpressure'],
      defaultConstraints: ['queue-sla-2s'],
      defaultRubricId: 'queue-priority-handling-rubric',
      phrasingSkeleton: 'Handle multiple priorities in a queue-based system.',
    },
    {
      key: 'queue-idempotent-consumers',
      topicId: 'queues',
      archetype: 'reliability',
      difficulty: 'medium',
      stem: 'Make consumers safe under duplicate delivery.',
      framing: 'Idempotency keys, dedupe state, and side-effect ordering for at-least-once systems.',
      primaryConcepts: ['queue-delivery-semantics', 'queue-schema'],
      supportingConcepts: ['queue-dlq'],
      defaultConstraints: ['queue-retry-limits'],
      defaultRubricId: 'queue-idempotent-consumers-rubric',
      phrasingSkeleton: 'How would you design a queue consumer so duplicate messages do not create duplicate side effects?',
    },
    {
      key: 'queue-dlq-replay-governance',
      topicId: 'queues',
      archetype: 'reliability',
      difficulty: 'hard',
      stem: 'Replay failed messages without repeating the outage.',
      framing: 'DLQ triage, throttled replay, and poison-message containment.',
      primaryConcepts: ['queue-dlq', 'queue-replay'],
      supportingConcepts: ['queue-observability'],
      defaultConstraints: ['queue-retry-limits', 'queue-sla-2s'],
      defaultRubricId: 'queue-dlq-replay-governance-rubric',
      phrasingSkeleton: 'A DLQ contains millions of failed messages after a bad deploy; how would you decide what to replay, at what rate, and with what safeguards?',
    },
    {
      key: 'queue-schema-evolution',
      topicId: 'queues',
      archetype: 'integration',
      difficulty: 'medium',
      stem: 'Evolve message schemas without breaking consumers.',
      framing: 'Compatibility modes, deployment sequencing, and validation boundaries.',
      primaryConcepts: ['queue-schema', 'queue-delivery-semantics'],
      supportingConcepts: ['queue-security'],
      defaultConstraints: ['queue-compliance'],
      defaultRubricId: 'queue-schema-evolution-rubric',
      phrasingSkeleton: 'How would you roll out a new message version while older consumers are still processing the previous schema?',
    },
    {
      key: 'queue-fairness-isolation',
      topicId: 'queues',
      archetype: 'architecture',
      difficulty: 'hard',
      stem: 'Keep tenants fair on shared asynchronous infrastructure.',
      framing: 'Per-tenant quotas, separate queues, and starvation detection.',
      primaryConcepts: ['queue-scheduling', 'queue-security'],
      supportingConcepts: ['queue-backpressure'],
      defaultConstraints: ['queue-cost', 'queue-compliance'],
      defaultRubricId: 'queue-fairness-isolation-rubric',
      phrasingSkeleton: 'One tenant floods a shared queue and smaller tenants start missing deadlines; how would you redesign for fairness without exploding cost?',
    },
    {
      key: 'queue-batch-processing',
      topicId: 'queues',
      archetype: 'performance',
      difficulty: 'medium',
      stem: 'Batch queue work without hiding failures.',
      framing: 'Batch size, visibility windows, and partial success semantics.',
      primaryConcepts: ['queue-scaling', 'queue-backpressure'],
      supportingConcepts: ['queue-observability'],
      defaultConstraints: ['queue-sla-2s'],
      defaultRubricId: 'queue-batch-processing-rubric',
      phrasingSkeleton: 'When would you batch message handling, and how would you tune batch size so throughput improves without turning one bad message into repeated batch failure?',
    },
  ],
  learningResources: [
    { title: 'Kafka Patterns', url: 'https://kafka.apache.org/documentation/' },
    { title: 'SQS Developer Guide', url: 'https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/welcome.html' },
    { title: 'Event Delivery Semantics', note: 'Internal primer' },
  ],
};

export default queuesPack;
