import { TopicPack } from '../topic-pack.types';

export const systemDesignPack: TopicPack = {
  topicId: 'system-design',
  label: 'System Design',
  description: 'Architecture fundamentals, scale, reliability, and delivery tradeoffs for backend systems.',
  archetypes: ['architecture', 'performance', 'reliability', 'data', 'delivery'],
  concepts: [
    {
      id: 'sd-service-boundaries',
      topicId: 'system-design',
      title: 'Service Boundaries',
      summary: 'Define cohesive service responsibilities and align APIs with domain capabilities.',
      stage: 'foundation',
      signals: ['Identifies clear owners', 'Avoids chatty calls'],
    },
    {
      id: 'sd-read-write-paths',
      topicId: 'system-design',
      title: 'Read/Write Paths',
      summary: 'Trace critical user flows with latency, consistency, and durability expectations.',
      stage: 'foundation',
      prerequisites: ['sd-service-boundaries'],
    },
    {
      id: 'sd-consistency-models',
      topicId: 'system-design',
      title: 'Consistency Models',
      summary: 'Choose eventual vs strong consistency with failure and replay considerations.',
      stage: 'intermediate',
    },
    {
      id: 'sd-capacity-planning',
      topicId: 'system-design',
      title: 'Capacity Planning',
      summary: 'Traffic modeling, SLOs, headroom, and graceful degradation budgets.',
      stage: 'intermediate',
      signals: ['P99 targets', 'Error budget usage'],
    },
    {
      id: 'sd-idempotency',
      topicId: 'system-design',
      title: 'Idempotency & Ordering',
      summary: 'Prevent duplicate effects under retries, dedupe, and ordering guards.',
      stage: 'intermediate',
    },
    {
      id: 'sd-cache-strategy',
      topicId: 'system-design',
      title: 'Cache Strategy',
      summary: 'Layered caches, invalidation, TTL vs write-through vs write-back tradeoffs.',
      stage: 'intermediate',
    },
    {
      id: 'sd-queue-vs-stream',
      topicId: 'system-design',
      title: 'Queue vs Stream',
      summary: 'Select delivery semantics, ordering, backpressure handling, and consumer patterns.',
      stage: 'intermediate',
    },
    {
      id: 'sd-sharding',
      topicId: 'system-design',
      title: 'Sharding & Partitioning',
      summary: 'Key design, hot partition mitigation, rebalancing strategies.',
      stage: 'advanced',
      prerequisites: ['sd-read-write-paths', 'sd-consistency-models'],
    },
    {
      id: 'sd-replication',
      topicId: 'system-design',
      title: 'Replication & Failover',
      summary: 'Leader/follower, quorum, failover detection, split-brain avoidance.',
      stage: 'advanced',
    },
    {
      id: 'sd-backpressure',
      topicId: 'system-design',
      title: 'Backpressure & Load Shedding',
      summary: 'Protect upstreams with queues, timeouts, and admission control.',
      stage: 'advanced',
    },
    {
      id: 'sd-observability',
      topicId: 'system-design',
      title: 'Observability',
      summary: 'Tracing, metrics, structured logs, and SLO dashboards tied to user journeys.',
      stage: 'foundation',
    },
    {
      id: 'sd-safe-delivery',
      topicId: 'system-design',
      title: 'Safe Delivery',
      summary: 'Blue/green, canary, feature flags, and config rollout with guardrails.',
      stage: 'advanced',
      prerequisites: ['sd-observability'],
    },
  ],
  scenarioHooks: [
    {
      id: 'sd-traffic-spike',
      topicId: 'system-design',
      title: 'Product launch spike',
      backdrop: 'A new product launch causes 20x traffic for 48 hours.',
      trigger: 'API latency creeps past 400ms p99 and error budget is burning fast.',
      failureSignals: ['Queue depth rising', 'Cache hit rate dropping'],
      compatibleFamilies: ['sd-api-gateway', 'sd-cache-invalidation', 'sd-async-workflows', 'sd-cost-optimization', 'sd-rate-limiter-family'],
      relatedConcepts: ['sd-capacity-planning', 'sd-cache-strategy', 'sd-backpressure'],
    },
    {
      id: 'sd-geo-expansion',
      topicId: 'system-design',
      title: 'Multi-region expansion',
      backdrop: 'Service expanding from one region to three.',
      trigger: 'Users in APAC see inconsistent reads and higher write latency.',
      compatibleFamilies: ['sd-multi-region-failover', 'sd-data-compliance-family'],
      relatedConcepts: ['sd-replication', 'sd-consistency-models', 'sd-sharding'],
    },
    {
      id: 'sd-batch-to-stream',
      topicId: 'system-design',
      title: 'Batch to streaming migration',
      backdrop: 'Daily batch ETL is missing freshness SLAs.',
      trigger: 'Business wants near-real-time analytics with minimal rework.',
      compatibleFamilies: ['sd-write-path', 'sd-async-workflows'],
      relatedConcepts: ['sd-queue-vs-stream', 'sd-sharding'],
    },
    {
      id: 'sd-hot-partition',
      topicId: 'system-design',
      title: 'Hot partition in datastore',
      backdrop: 'One tenant dominates write traffic.',
      trigger: 'Partition key skew creates throttling and burst errors.',
      compatibleFamilies: ['sd-write-path', 'sd-search-autocomplete'],
      relatedConcepts: ['sd-sharding', 'sd-backpressure'],
    },
    {
      id: 'sd-third-party-sla',
      topicId: 'system-design',
      title: 'Slow third-party dependency',
      backdrop: 'Checkout relies on a payment provider with 800ms p95.',
      trigger: 'Downstream slowness leaks into user-facing SLOs.',
      compatibleFamilies: ['sd-api-gateway', 'sd-async-workflows', 'sd-rate-limiter-family'],
      relatedConcepts: ['sd-backpressure', 'sd-idempotency'],
    },
    {
      id: 'sd-data-compliance',
      topicId: 'system-design',
      title: 'Data retention and deletion',
      backdrop: 'New regulatory requirement to delete user data within 30 days.',
      trigger: 'Existing backups and replicas still hold retired data.',
      compatibleFamilies: ['sd-multi-region-failover', 'sd-observability-delivery', 'sd-data-compliance-family'],
      relatedConcepts: ['sd-replication', 'sd-safe-delivery'],
    },
  ],
  constraintTemplates: [
    { id: 'sd-slo-200ms', topicId: 'system-design', label: 'Latency SLO', text: 'p99 < 200ms for read path', tags: ['latency'] },
    { id: 'sd-budget-lean', topicId: 'system-design', label: 'Team budget', text: '2 engineers for 6 weeks; prefer managed services', tags: ['resourcing'] },
    { id: 'sd-availability', topicId: 'system-design', label: 'Availability', text: 'Target 99.9% with graceful degradation during outages', tags: ['reliability'] },
    { id: 'sd-cost-cap', topicId: 'system-design', label: 'Cost cap', text: 'Monthly infra budget capped at $8k', tags: ['cost'] },
    { id: 'sd-migration', topicId: 'system-design', label: 'Migration safety', text: 'Must support blue/green and automatic rollback', tags: ['delivery'] },
    { id: 'sd-data-sovereignty', topicId: 'system-design', label: 'Data locality', text: 'EU user data must stay within EU regions', tags: ['compliance'] },
  ],
  rubricTemplates: [
    {
      id: 'sd-architecture-rubric',
      topicId: 'system-design',
      archetype: 'architecture',
      mustHave: ['Defines API and data flows', 'Addresses scaling path', 'Covers failure modes and mitigation'],
      niceToHave: ['Considers developer ergonomics', 'Mentions observability'],
      redFlags: ['No SLOs', 'Ignores data constraints', 'No rollback plan'],
      scoringWeights: { clarity: 0.2, correctness: 0.25, depth: 0.25, pragmatism: 0.2, safety: 0.1 },
    },
    {
      id: 'sd-performance-rubric',
      topicId: 'system-design',
      archetype: 'performance',
      mustHave: ['Quantifies throughput and latency', 'Identifies bottlenecks', 'Proposes cache or partition strategy'],
      niceToHave: ['Capacity headroom plan', 'Data locality awareness'],
      redFlags: ['Hand-wavy estimates', 'No profiling plan'],
      scoringWeights: { clarity: 0.2, correctness: 0.2, depth: 0.25, pragmatism: 0.2, safety: 0.15 },
    },
    {
      id: 'sd-reliability-rubric',
      topicId: 'system-design',
      archetype: 'reliability',
      mustHave: ['Clear failure domains', 'Health checks and timeouts', 'Rollback/circuit breaker path'],
      niceToHave: ['Chaos or game day ideas'],
      redFlags: ['Single region only', 'No incident signals'],
      scoringWeights: { clarity: 0.2, correctness: 0.2, depth: 0.2, pragmatism: 0.2, safety: 0.2 },
    },
  ],
  questionFamilies: [
    {
      key: 'sd-api-gateway',
      topicId: 'system-design',
      archetype: 'architecture',
      difficulty: 'hard',
      stem: 'Design an API entry layer that protects backends and balances traffic.',
      framing: 'Cover routing, auth, caching, and rollout controls.',
      primaryConcepts: ['sd-service-boundaries', 'sd-backpressure', 'sd-cache-strategy'],
      defaultConstraints: ['sd-availability', 'sd-slo-200ms'],
      defaultRubricId: 'sd-api-gateway-rubric',
      phrasingSkeleton: 'Design an API gateway or edge layer for <system>.',
      learningObjectives: ['Balance protection and latency', 'Choose cache and routing patterns'],
    },
    {
      key: 'sd-write-path',
      topicId: 'system-design',
      archetype: 'data',
      difficulty: 'hard',
      stem: 'Design a write path that survives spikes and keeps data ordered enough.',
      framing: 'Explain ingestion, storage, and idempotency strategy.',
      primaryConcepts: ['sd-read-write-paths', 'sd-idempotency', 'sd-queue-vs-stream'],
      defaultConstraints: ['sd-cost-cap'],
      defaultRubricId: 'sd-write-path-rubric',
      phrasingSkeleton: 'Walk through a write path with ordering and retries.',
    },
    {
      key: 'sd-cache-invalidation',
      topicId: 'system-design',
      archetype: 'performance',
      difficulty: 'medium',
      stem: 'Plan a cache strategy that balances freshness and cost.',
      framing: 'Cover what to cache, invalidation, and failure handling.',
      primaryConcepts: ['sd-cache-strategy', 'sd-consistency-models'],
      supportingConcepts: ['sd-observability'],
      defaultConstraints: ['sd-slo-200ms'],
      defaultRubricId: 'sd-cache-invalidation-rubric',
      phrasingSkeleton: 'Propose a caching approach and invalidation story.',
    },
    {
      key: 'sd-async-workflows',
      topicId: 'system-design',
      archetype: 'reliability',
      difficulty: 'hard',
      stem: 'Move expensive work off the request thread safely.',
      framing: 'Choose between queues vs streams and handle failures.',
      primaryConcepts: ['sd-queue-vs-stream', 'sd-backpressure'],
      supportingConcepts: ['sd-safe-delivery'],
      defaultConstraints: ['sd-budget-lean'],
      defaultRubricId: 'sd-async-workflows-rubric',
      phrasingSkeleton: 'Decide how to offload background work with retries.',
    },
    {
      key: 'sd-multi-region-failover',
      topicId: 'system-design',
      archetype: 'reliability',
      difficulty: 'epic',
      stem: 'Handle regional failures without violating data constraints.',
      framing: 'Explain replication, failover triggers, and client impact.',
      primaryConcepts: ['sd-replication', 'sd-consistency-models'],
      defaultConstraints: ['sd-data-sovereignty', 'sd-availability'],
      defaultRubricId: 'sd-multi-region-failover-rubric',
      phrasingSkeleton: 'Design failover across regions with consistency story.',
    },
    {
      key: 'sd-observability-delivery',
      topicId: 'system-design',
      archetype: 'delivery',
      difficulty: 'medium',
      stem: 'Ship changes safely with signals and rollback hooks.',
      framing: 'Describe canary/blue-green and metrics for rollback.',
      primaryConcepts: ['sd-safe-delivery', 'sd-observability'],
      defaultConstraints: ['sd-migration'],
      defaultRubricId: 'sd-observability-delivery-rubric',
      phrasingSkeleton: 'Explain safe rollout plan with observability gates.',
    },
    {
      key: 'sd-data-compliance-family',
      topicId: 'system-design',
      archetype: 'data',
      difficulty: 'hard',
      stem: 'Handle data retention and deletion at scale.',
      framing: 'Cover backups, replicas, and guarantees for deletes.',
      primaryConcepts: ['sd-replication', 'sd-safe-delivery'],
      defaultConstraints: ['sd-data-sovereignty'],
      defaultRubricId: 'sd-data-compliance-family-rubric',
      phrasingSkeleton: 'Design compliant data deletion across regions.',
    },
    {
      key: 'sd-cost-optimization',
      topicId: 'system-design',
      archetype: 'performance',
      difficulty: 'medium',
      stem: 'Reduce infra cost without breaking SLOs.',
      framing: 'Identify high-cost paths and propose mitigations.',
      primaryConcepts: ['sd-capacity-planning', 'sd-cache-strategy'],
      defaultConstraints: ['sd-cost-cap'],
      defaultRubricId: 'sd-cost-optimization-rubric',
      phrasingSkeleton: 'Lower cost while keeping latency within SLOs.',
    },
    {
      key: 'sd-search-autocomplete',
      topicId: 'system-design',
      archetype: 'architecture',
      difficulty: 'epic',
      stem: 'Design a search autocomplete service.',
      framing: 'Data model, ranking, caching, and freshness.',
      primaryConcepts: ['sd-sharding', 'sd-cache-strategy'],
      defaultConstraints: ['sd-slo-200ms'],
      defaultRubricId: 'sd-search-autocomplete-rubric',
      phrasingSkeleton: 'Build autocomplete with scale and freshness.',
    },
    {
      key: 'sd-rate-limiter-family',
      topicId: 'system-design',
      archetype: 'reliability',
      difficulty: 'hard',
      stem: 'Protect backends with a rate limiter.',
      framing: 'Global vs per-tenant, fairness, and fallback responses.',
      primaryConcepts: ['sd-backpressure', 'sd-service-boundaries'],
      defaultConstraints: ['sd-availability'],
      defaultRubricId: 'sd-rate-limiter-family-rubric',
      phrasingSkeleton: 'Design a rate limiter that degrades gracefully.',
    },
  ],
  learningResources: [
    { title: 'System Design Primer', url: 'https://github.com/donnemartin/system-design-primer' },
    { title: 'Availability and Consistency Notes', url: 'https://martin.kleppmann.com/' },
    { title: 'Production Readiness Checklist', note: 'Internal placeholder' },
  ],
};

export default systemDesignPack;
