import { Difficulty, ExperienceBand, QuestionType, Topic } from '../domain/enums';
import { Concept, QuestionTemplate, Rubric } from '../domain/interfaces';

export const javascriptConcepts: Concept[] = [
  {
    id: 'js-closure-scope',
    topic: Topic.JAVASCRIPT,
    subtopic: 'language-core',
    name: 'Closures & Scope',
    description: 'Lexical scope, closures, and common pitfalls with loops and var/let.',
  },
  {
    id: 'js-async-await',
    topic: Topic.JAVASCRIPT,
    subtopic: 'async',
    name: 'Async/Await Semantics',
    description: 'Promise lifecycle, microtasks, and error bubbling in async functions.',
  },
  {
    id: 'js-event-loop',
    topic: Topic.JAVASCRIPT,
    subtopic: 'runtime',
    name: 'Browser Event Loop',
    description: 'Task vs microtask queues, rendering steps, and starvation risks.',
  },
  {
    id: 'js-immutability',
    topic: Topic.JAVASCRIPT,
    subtopic: 'state',
    name: 'Immutability & Copying',
    description: 'Structural sharing, spread pitfalls, and perf trade-offs in state updates.',
  },
  {
    id: 'js-types-safety',
    topic: Topic.JAVASCRIPT,
    subtopic: 'typing',
    name: 'Type Safety Patterns',
    description: 'Using TypeScript discriminated unions, narrowing, and exhaustive checks.',
  },
];

export const javascriptRubrics: Rubric[] = [
  {
    id: 'js-coding-rubric',
    topic: Topic.JAVASCRIPT,
    type: QuestionType.CODING,
    mustHave: [
      'Produces correct, runnable code',
      'Handles edge cases and input validation',
      'Avoids needless mutations that break references',
    ],
    niceToHave: ['Adds simple tests or examples', 'Considers time and space trade-offs'],
    validStrategies: ['Use pure functions where possible', 'Favor readability over cleverness', 'Explain alternative approaches'],
    redFlags: ['Relies on global mutable state', 'Introduces hidden async paths', 'Uses anti-patterns like implicit any'],
    scoringWeights: {
      relevance: 0.2,
      correctness: 0.25,
      completeness: 0.2,
      reasoning: 0.2,
      communication: 0.15,
    },
  },
  {
    id: 'js-debugging-rubric',
    topic: Topic.JAVASCRIPT,
    type: QuestionType.DEBUGGING,
    mustHave: [
      'Reproduces the issue deterministically',
      'Inspects call stack and async timing',
      'Considers environment differences (browser vs node)',
    ],
    niceToHave: ['Builds a minimal failing example', 'Notes tooling like breakpoints or performance markers'],
    validStrategies: ['Use console timeline or performance panel', 'Add guards and assertions', 'Check promise rejection handling'],
    redFlags: ['Guesses without testing', 'Mutates shared state to “fix” symptoms', 'Ignores race conditions'],
    scoringWeights: {
      relevance: 0.2,
      correctness: 0.25,
      completeness: 0.2,
      reasoning: 0.2,
      communication: 0.15,
    },
  },
  {
    id: 'js-architecture-rubric',
    topic: Topic.JAVASCRIPT,
    type: QuestionType.ARCHITECTURE,
    mustHave: ['Chooses appropriate state management', 'Considers rendering cost and batching', 'Defines contracts between UI and data layers'],
    niceToHave: ['Mentions accessibility or UX impact', 'Plans observability and error boundaries'],
    validStrategies: ['Use composition over inheritance', 'Prefer predictable data flow', 'Document assumptions in code'],
    redFlags: ['Deeply nested prop drilling without reason', 'Tight coupling to specific runtime', 'Ignores performance budgets'],
    scoringWeights: {
      relevance: 0.2,
      correctness: 0.25,
      completeness: 0.2,
      reasoning: 0.2,
      communication: 0.15,
    },
  },
];

export const javascriptQuestionTemplates: QuestionTemplate[] = [
  {
    id: 'js-closure-capture',
    topic: Topic.JAVASCRIPT,
    subtopic: 'language-core',
    concepts: ['js-closure-scope'],
    type: QuestionType.THEORY,
    difficulty: Difficulty.EASY,
    experienceBands: [ExperienceBand.JUNIOR, ExperienceBand.MID],
    template: 'Explain how closures capture variables inside loops and how let/const change the behavior compared to var.',
    rubricId: 'js-coding-rubric',
  },
  {
    id: 'js-async-await-error-bubble',
    topic: Topic.JAVASCRIPT,
    subtopic: 'async',
    concepts: ['js-async-await', 'js-event-loop'],
    type: QuestionType.THEORY,
    difficulty: Difficulty.MEDIUM,
    experienceBands: [ExperienceBand.JUNIOR, ExperienceBand.MID],
    template: 'Show how async/await handles errors differently than raw promises and what happens with unhandled rejections.',
    rubricId: 'js-debugging-rubric',
  },
  {
    id: 'js-microtask-timing',
    topic: Topic.JAVASCRIPT,
    subtopic: 'runtime',
    concepts: ['js-event-loop'],
    type: QuestionType.DEBUGGING,
    difficulty: Difficulty.MEDIUM,
    experienceBands: [ExperienceBand.MID, ExperienceBand.SENIOR],
    template: 'A UI freezes after a promise chain. Walk through diagnosing microtask starvation and how to fix it.',
    rubricId: 'js-debugging-rubric',
  },
  {
    id: 'js-immutable-state-update',
    topic: Topic.JAVASCRIPT,
    subtopic: 'state',
    concepts: ['js-immutability'],
    type: QuestionType.CODING,
    difficulty: Difficulty.MEDIUM,
    experienceBands: [ExperienceBand.JUNIOR, ExperienceBand.MID],
    template: 'Given nested state, implement an update without mutating the original object. Discuss perf trade-offs.',
    rubricId: 'js-coding-rubric',
  },
  {
    id: 'js-types-discriminated-union',
    topic: Topic.JAVASCRIPT,
    subtopic: 'typing',
    concepts: ['js-types-safety'],
    type: QuestionType.CODING,
    difficulty: Difficulty.MEDIUM,
    experienceBands: [ExperienceBand.MID, ExperienceBand.SENIOR],
    template: 'Model a discriminated union for API responses and show exhaustive checking at compile time.',
    rubricId: 'js-coding-rubric',
  },
  {
    id: 'js-ui-arch-tradeoffs',
    topic: Topic.JAVASCRIPT,
    subtopic: 'architecture',
    concepts: ['js-immutability', 'js-types-safety'],
    type: QuestionType.ARCHITECTURE,
    difficulty: Difficulty.HARD,
    experienceBands: [ExperienceBand.SENIOR, ExperienceBand.STAFF],
    template: 'Design a UI data flow for a large SPA that balances predictability with performance. Include how you would debug render thrash.',
    rubricId: 'js-architecture-rubric',
  },
];

export const javascriptSeeds = {
  topic: Topic.JAVASCRIPT,
  concepts: javascriptConcepts,
  rubrics: javascriptRubrics,
  questionTemplates: javascriptQuestionTemplates,
};
