import { Difficulty, ExperienceBand, QuestionType, Topic } from '../domain/enums';
import { Concept, QuestionTemplate, Rubric } from '../domain/interfaces';

// Seed data for Node.js topic; kept small and consistent for early planner experiments.
export const nodeJsConcepts: Concept[] = [
  {
    id: 'nodejs-event-loop',
    topic: Topic.NODEJS,
    subtopic: 'runtime',
    name: 'Event Loop Phases',
    description: 'How Node.js schedules macrotasks and microtasks across loop phases.',
    prerequisites: ['js-promises', 'js-callstack'],
  },
  {
    id: 'nodejs-streams-backpressure',
    topic: Topic.NODEJS,
    subtopic: 'streams',
    name: 'Streams & Backpressure',
    description: 'Flowing vs paused mode, buffering limits, and applying backpressure.',
    prerequisites: ['nodejs-event-loop'],
  },
  {
    id: 'nodejs-module-resolution',
    topic: Topic.NODEJS,
    subtopic: 'modules',
    name: 'ESM/CJS Resolution',
    description: 'How Node resolves CommonJS and ES modules, including package exports.',
  },
  {
    id: 'nodejs-error-handling',
    topic: Topic.NODEJS,
    subtopic: 'reliability',
    name: 'Operational vs Programmer Errors',
    description: 'Distinguishing error categories and safe recovery patterns.',
  },
  {
    id: 'nodejs-perf-profiling',
    topic: Topic.NODEJS,
    subtopic: 'performance',
    name: 'Profiling & Hot Paths',
    description: 'Using perf hooks, flamegraphs, and clustering to improve throughput.',
  },
];

export const nodeJsRubrics: Rubric[] = [
  {
    id: 'nodejs-coding-rubric',
    topic: Topic.NODEJS,
    type: QuestionType.CODING,
    mustHave: [
      'Produces runnable code covering happy path',
      'Handles asynchronous flow without deadlocks',
      'Uses Node.js standard patterns (callbacks, promises, streams) appropriately',
    ],
    niceToHave: ['Adds logging/hooks for observability', 'Shows progressive enhancement for performance'],
    validStrategies: [
      'Use async/await with proper error boundaries',
      'Lean on Node streams or pipeline for I/O heavy paths',
      'Break problems into small composable utilities',
    ],
    redFlags: [
      'Blocks the event loop with sync I/O or CPU loops',
      'Mixes callback and promise styles unsafely',
      'Swallows errors without propagation',
    ],
    scoringWeights: {
      relevance: 0.2,
      correctness: 0.25,
      completeness: 0.2,
      reasoning: 0.2,
      communication: 0.15,
    },
  },
  {
    id: 'nodejs-debugging-rubric',
    topic: Topic.NODEJS,
    type: QuestionType.DEBUGGING,
    mustHave: [
      'Forms a testable hypothesis about the failure',
      'Inspects logs or metrics before changing code',
      'Identifies async boundaries that hide stack traces',
    ],
    niceToHave: ['Uses minimal repro snippets', 'Considers dependency or runtime version drift'],
    validStrategies: [
      'Use --inspect or console profiling to trace timing',
      'Add targeted logging around async edges',
      'Verify error handling paths and promise chains',
    ],
    redFlags: ['Jumps to edits without evidence', 'Ignores race conditions', 'Deletes error handling to \"fix\" tests'],
    scoringWeights: {
      relevance: 0.2,
      correctness: 0.25,
      completeness: 0.2,
      reasoning: 0.2,
      communication: 0.15,
    },
  },
  {
    id: 'nodejs-architecture-rubric',
    topic: Topic.NODEJS,
    type: QuestionType.ARCHITECTURE,
    mustHave: ['Chooses stateless vs stateful appropriately', 'Considers horizontal scaling and backpressure', 'Addresses failure domains and retries'],
    niceToHave: ['Mentions observability and budgets', 'Plans feature flags or gradual rollout'],
    validStrategies: ['Queue-based load leveling', 'Sharding or worker pools', 'API contracts with graceful degradation'],
    redFlags: ['Single-thread assumptions', 'Missing circuit breakers', 'Ignores deployment/runtime constraints'],
    scoringWeights: {
      relevance: 0.2,
      correctness: 0.25,
      completeness: 0.2,
      reasoning: 0.2,
      communication: 0.15,
    },
  },
];

export const nodeJsQuestionTemplates: QuestionTemplate[] = [
  {
    id: 'nodejs-event-loop-sequencing',
    topic: Topic.NODEJS,
    subtopic: 'runtime',
    concepts: ['nodejs-event-loop'],
    type: QuestionType.THEORY,
    difficulty: Difficulty.MEDIUM,
    experienceBands: [ExperienceBand.JUNIOR, ExperienceBand.MID],
    template: 'Explain how the Node.js event loop orders timers, I/O callbacks, and microtasks. Provide an example where ordering matters.',
    engagementHook: 'Use a real-world bug you have seen where ordering was surprising.',
    rubricId: 'nodejs-architecture-rubric',
  },
  {
    id: 'nodejs-stream-backpressure-coding',
    topic: Topic.NODEJS,
    subtopic: 'streams',
    concepts: ['nodejs-streams-backpressure'],
    type: QuestionType.CODING,
    difficulty: Difficulty.MEDIUM,
    experienceBands: [ExperienceBand.MID, ExperienceBand.SENIOR],
    template: 'Given a large file upload proxy, write a snippet that applies backpressure using Node.js streams or pipeline.',
    engagementHook: 'Assume uploads can spike to 1Gbps for a few seconds.',
    rubricId: 'nodejs-coding-rubric',
  },
  {
    id: 'nodejs-esm-cjs-troubleshoot',
    topic: Topic.NODEJS,
    subtopic: 'modules',
    concepts: ['nodejs-module-resolution'],
    type: QuestionType.DEBUGGING,
    difficulty: Difficulty.MEDIUM,
    experienceBands: [ExperienceBand.MID, ExperienceBand.SENIOR],
    template: 'A package.json sets "type": "module" but an internal dependency is CommonJS. Walk through resolving import errors and interop.',
    rubricId: 'nodejs-debugging-rubric',
  },
  {
    id: 'nodejs-error-boundaries-design',
    topic: Topic.NODEJS,
    subtopic: 'reliability',
    concepts: ['nodejs-error-handling', 'nodejs-event-loop'],
    type: QuestionType.ARCHITECTURE,
    difficulty: Difficulty.HARD,
    experienceBands: [ExperienceBand.SENIOR, ExperienceBand.STAFF],
    template: 'Design an error-handling approach for an API server so operational errors do not crash workers while programmer errors still surface.',
    rubricId: 'nodejs-architecture-rubric',
  },
  {
    id: 'nodejs-perf-hotpath-investigation',
    topic: Topic.NODEJS,
    subtopic: 'performance',
    concepts: ['nodejs-perf-profiling', 'nodejs-event-loop'],
    type: QuestionType.DEBUGGING,
    difficulty: Difficulty.HARD,
    experienceBands: [ExperienceBand.SENIOR, ExperienceBand.STAFF],
    template: 'Given CPU spikes during peak traffic, outline how you would profile and isolate hot paths without downtime.',
    rubricId: 'nodejs-debugging-rubric',
  },
  {
    id: 'nodejs-streaming-architecture',
    topic: Topic.NODEJS,
    subtopic: 'streams',
    concepts: ['nodejs-streams-backpressure', 'nodejs-module-resolution'],
    type: QuestionType.ARCHITECTURE,
    difficulty: Difficulty.MEDIUM,
    experienceBands: [ExperienceBand.MID, ExperienceBand.SENIOR],
    template: 'Design a streaming ingestion service that normalizes JSON events and writes to storage while respecting downstream backpressure.',
    excludesWith: ['nodejs-stream-backpressure-coding'],
    rubricId: 'nodejs-architecture-rubric',
  },
];

export const nodeJsSeeds = {
  topic: Topic.NODEJS,
  concepts: nodeJsConcepts,
  rubrics: nodeJsRubrics,
  questionTemplates: nodeJsQuestionTemplates,
};
